### ISSUE TITLE
[Model Certification] - Adeo/Lexman Module On/Off

### ISSUE THREAD

**Issue by LD40** [zigbeefordomoticz/z4d-certified-devices#10]
Product name : Lexman 1 output On/Off
Brand : Lexman (Adeo)
URL : https://www.leroymerlin.fr/produits/electricite-domotique/domotique-et-objets-connectes/objets-connectes-compatibles-avec-enki/module-connecte-on-off-lexman-83424574.html

No problem to pair the device, Works when sending commands (On or Off) after introduction within Domoticz
but strange state changes occurs without doing anything (coming off to on or reverse ; not only the state in the app but the module state)

{"PluginInfos":{"HardwareID":17,"HomeFolder":"/home/pi/domoticz/plugins/Domoticz-Zigate/","StartupFolder":"/home/pi/domoticz/","UserDataFolder":"/home/pi/domoticz/","WebRoot":"","Database":"/home/pi/domoticz/domoticz.db","Language":"fr","Version":"7.1","Author":"pipiche38","Name":"Zigate","Address":"0.0.0.0","Port":"9999","SerialPort":"/dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0","Key":"Zigate","Mode1":"V1","Mode2":"USB","Mode3":"False","Mode4":"9440","Mode6":"2","DomoticzVersion":"2023.2","DomoticzHash":"19efd039c","DomoticzBuildTime":"2023-07-21 17:23:44","PluginBranch":"stable7","PluginVersion":"7.1.002","CertifiedDbVersion":"2.92","TimeStamp":1692894342,"available":0,"available-firmMajor":0,"available-firmMinor":0,"FirmwareVersion":"0320","FirmwareUpdate":false,"PluginUpdate":false,"LogLevel":7,"Zigpy":false,"CoordinatorModel":"ZiGate Classic PDM (OptiPDM)","CoordinatorFirmwareVersion":"0320","DisplayFirmwareVersion":"Zigate - 0320","CoordinatorIEEE":"00158d0001edb6bf","NetworkSize":"Total: 8 | Routers: 5 | End Devices: 3","NetworkDevices":{"1110":{"Profalux":["MAI-ZTS","BSO-Profalux"]},"1227":{"Adeo":["SIN-4-1-20_LEX"]},"1277":{"Adeo":["ZBEK-14"]}}},"Analytics":1,"Device":{"Version":"3","ZDeviceName":"","Status":"inDB","SQN":"66","Ep":{"01":{"1000":{},"0000":{"0004":"Adeo","0005":"SIN-4-1-20_LEX","0000":"8","0001":"2","0002":"103","0003":"34","0006":"2020","0007":"1"},"0003":{"0000":"0"},"0004":{},"0005":{},"0006":{"4001":"0","4002":"0","0000":"01"},"0007":{"0000":"00","0010":"02"},"fc57":{},"0019":{},"ClusterType":{"499":"Switch"}},"f2":{"0021":{}}},"Heartbeat":"99","RIA":"4","LQI":117,"Battery":{},"Model":"SIN-4-1-20_LEX","ForceAckCommands":[],"MacCapa":"8e","IEEE":"040d84fffee13019","Type":"Switch","ProfileID":"a1e0","ZDeviceID":"0066","App Version":"2","Attributes List":{"Request":{"01":{"1000":1689767833.0990064,"0000":1689767833.0961616,"0003":1689767833.0966246,"0004":1689767833.0970798,"0005":1689767833.0975435,"0006":1689767833.0979946,"0007":1689767833.0984569,"fc57":1689767833.1076245,"0019":1689767833.10809},"f2":{"0021":1689767833.1085863}}},"DeviceType":"FFD","HW Version":"34","Last Cmds":[[11,"02","132d","0092","010100"]],"LogicalType":"Router","Manufacturer":"1227","Manufacturer Name":"Adeo","NbEp":"2","PowerSource":"Main","ReadAttributes":{"Ep":{"01":{"0000":{"TimeStamp":1689763966,"iSQN":{"4000":222,"0004":218,"0005":218,"0000":12,"0001":219,"0002":219,"0003":219,"0006":220,"0007":220,"000a":220,"000f":221,"0010":221,"0015":221,"f000":222},"Attributes":{"4000":"86","0004":"00","0005":"00","0000":"00","0001":"00","0002":"00","0003":"00","0006":"00","0007":"00","000a":"86","000f":"86","0010":"86","0015":"86","f000":"86"},"ZigateRequest":{}},"0019":{"TimeStamp":1689763965,"iSQN":{"0001":213,"0002":213,"0003":213,"0004":214,"0005":214,"0006":214,"0007":215,"0008":215,"0009":215,"000a":216},"Attributes":{"0001":"86","0002":"86","0003":"86","0004":"86","0005":"86","0006":"86","0007":"86","0008":"86","0009":"86","000a":"86"},"ZigateRequest":{}},"0006":{"TimeStamp":1692893329,"iSQN":{"4001":217,"4002":217,"0000":12},"Attributes":{"4001":"00","4002":"00","0000":"00"},"ZigateRequest":{}},"0007":{"TimeStamp":1692877571,"iSQN":{},"Attributes":{"0000":"00","0010":"00"},"ZigateRequest":{}},"0003":{"TimeStamp":1692877571,"iSQN":{},"Attributes":{"0000":"00"},"ZigateRequest":{}}},"f2":{"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"ReceiveOnIdle":"On","Stack Version":"103","Stamp":{"time":1692894224.1887212,"Time":"2023-08-24 18:23:44","MsgType":"8011","LastSeen":1692894224,"LastPing":1690272872},"ZCL Version":"8","Health":"Live","macapa":"8e","ConfigureReporting":{"Ep":{"01":{"0006":{"TimeStamp":1689763963.147136,"iSQN":{"0000":212},"Attributes":{"0000":"00"},"ZigateRequest":{}}}}},"server_mask":"2c00","CertifiedDevice":false,"descriptor_capability":"00","Bind":{"01":{"1000":{"Target":"0000","Stamp":1689763964,"Phase":"binded","Status":"00","i_sqn":208},"0000":{"Target":"0000","Stamp":1689763963,"Phase":"binded","Status":"00","i_sqn":202},"0003":{"Target":"0000","Stamp":1689763963,"Phase":"binded","Status":"00","i_sqn":203},"0004":{"Target":"0000","Stamp":1689763963,"Phase":"binded","Status":"00","i_sqn":204},"0005":{"Target":"0000","Stamp":1689763963,"Phase":"binded","Status":"00","i_sqn":205},"0006":{"Target":"0000","Stamp":1689763964,"Phase":"binded","Status":"00","i_sqn":206},"0007":{"Target":"0000","Stamp":1689763964,"Phase":"binded","Status":"00","i_sqn":207},"fc57":{"Target":"0000","Stamp":1689763964,"Phase":"binded","Status":"00","i_sqn":209}},"f2":{"0021":{"Target":"0000","Stamp":1689763964,"Phase":"binded","Status":"82","i_sqn":210}}},"Capability":["Full-Function Device","Main Powered","Receiver during Idle","Standard security","NwkAddr should be allocated"],"BindingTable":{"SQN":0,"Status":"Success","TimeStamp":1689763967.0847695,"BindingTableSize":9,"Devices":[{"040d84fffee13019":{"sourceEp":"01","Cluster":"0006","targetIEEE":"040d84fffee13019","targetNickName":null,"targetEp":"01"}},{"040d84fffee13019":{"sourceEp":"01","Cluster":"0000","targetIEEE":"00158d0001edb6bf","targetNickName":"Zigate","targetEp":"01"}},{"040d84fffee13019":{"sourceEp":"01","Cluster":"0003","targetIEEE":"00158d0001edb6bf","targetNickName":"Zigate","targetEp":"01"}},{"040d84fffee13019":{"sourceEp":"01","Cluster":"0004","targetIEEE":"00158d0001edb6bf","targetNickName":"Zigate","targetEp":"01"}},{"040d84fffee13019":{"sourceEp":"01","Cluster":"0005","targetIEEE":"00158d0001edb6bf","targetNickName":"Zigate","targetEp":"01"}},{"040d84fffee13019":{"sourceEp":"01","Cluster":"0006","targetIEEE":"00158d0001edb6bf","targetNickName":"Zigate","targetEp":"01"}},{"040d84fffee13019":{"sourceEp":"01","Cluster":"0007","targetIEEE":"00158d0001edb6bf","targetNickName":"Zigate","targetEp":"01"}},{"040d84fffee13019":{"sourceEp":"01","Cluster":"1000","targetIEEE":"00158d0001edb6bf","targetNickName":"Zigate","targetEp":"01"}},{"040d84fffee13019":{"sourceEp":"01","Cluster":"fc57","targetIEEE":"00158d0001edb6bf","targetNickName":"Zigate","targetEp":"01"}}]},"SWBUILD_1":"2020","Log_UnknowDeviceFlag":1690272867.7355144,"Max Buffer Size":"52","WriteAttributes":{"Ep":{"01":{"1000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0003":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0004":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0005":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0007":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"fc57":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0019":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}},"f2":{"0021":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"ConfigSource":"8043","Max Tx":"01f4","_rawNodeDescriptor":"122701f401f42c00008e524001","GroupMemberShip":{"01":{}},"bitfield":"4001","Epv2":{"01":{"ClusterIn":{"1000":{},"0000":{},"0003":{},"0004":{},"0005":{},"0006":{},"0007":{},"fc57":{}},"ClusterOut":{"0003":{},"0006":{},"0019":{}},"ProfileID":"0104","ZDeviceID":"0100"},"f2":{"ClusterIn":{"0021":{}},"ClusterOut":{"0021":{}},"ProfileID":"a1e0","ZDeviceID":"0066"}},"Max Rx":"01f4","ReadConfigureReporting":{"Ep":{"01":{"0006":{"0000":{"TimeStamp":1689763966.9707563,"Status":"00","DataType":"10","MinInterval":"0001","MaxInterval":"012c"}}}},"TimeStamp":1689763966.970741},"ConsistencyCheck":"ok","RollingLQI":[99,117]}}

**Comment by pipiche38** [comment]
The described behaviour is indeed strange. Looks like an other French user doesn't have any issue

<img width="1230" alt="Screenshot 2023-08-24 at 19 34 06" src="https://github.com/zigbeefordomoticz/z4d-certified-devices/assets/8291674/a910117e-fd3e-4448-9fbc-6efa95c5e622">

**Comment by pipiche38** [comment]
Can you try to get the latest Certified Devices [2.94] , then when you have it running. Remove the device from Domoticz and from the plugin, restart the plugin and redo the pairing

**Comment by LD40** [comment]
> The described behaviour is indeed strange. Looks like an other French user doesn't have any issue

This comment is from me... before the problem.
All seemed to work well in the first days, then I noticed that some states were not those planned in the planning, and looking in details, identified these strange state changes.

I've just upgraded to stable7, and now upgrading certified devices from 2.92 to 2.94. I didn't find exactly how to check the version, neither how to upgrade, just do sudo python3 -m pip install git+https://github.com/zigbeefordomoticz/z4d-certified-devices, and then saw unstalling 2.92/installing 2.94)

But I will probably not be able to do repairing and other tests before end of middle of next week. 
Let me know what kind of logs could help you if it doesn't work.

**Comment by pipiche38** [comment]
the issue, now is that you have installed it directly from the github.
please do the following

`sudo python3 -m pip uninstall z4d-certified-devices`

from the home directory of the plugin
`sudo python3 -m pip install -r requirements.txt --upgrade`

let see what will happen, after a full reset of the device and a pairing with the config file. When there is no config file, the plugin try to discover and make some heavy query/bind/configuration which might put the device in bad shape

**Comment by pipiche38** [comment]
any update ?

**Comment by LD40** [comment]
Sorry, I was not able to test it yet.
But strangely the problem occurs only once sine my last message. I'm wondering if it's not a Domoticz planning issue rather than plugin (but not sure while looking at logs).
I let you know about further informations as soon as I can test repairing.

**Comment by pipiche38** [comment]
It would anyway be good to get the latest update

**Comment by LD40** [comment]
I executed the commands, delete device, reset and re-pair.
It seems to be OK after 4 days.
I'm wondering if it was a plugin problem or a Domoticz one.
I close the issue
