### ISSUE TITLE
[Model Certification] - Aqara Single Switch Module T1 (No Neutral)

### ISSUE THREAD

**Issue by tetedegenie** [zigbeefordomoticz/z4d-certified-devices#14]
Buy (certainly on aliexpress) an Aqara Single Switch Module T1 (No Neutral), shown as "lumi.switch.l0agl1" in plugin.

You can find more information here : https://zigbee.blakadder.com/Aqara_SSM-U02.html

This device is working perfectly but is seen as "non optimized" in plugin.

[export.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13060276/export.json)

**Comment by pipiche38** [comment]
should be fixed with 7.1.004 [2.114]

**Comment by tetedegenie** [comment]
Sorry for late review...
Have a message incoming every minutes for this device :
`------ We have detected a miss configuration reports for device 7639 on ep 01 and cluster 0006
- Attribut 0000 request to force a Configure Reporting due to field MinInterval '0000' != '0001' `

**Comment by pipiche38** [comment]
should be fixed with [2.148]

**Comment by tetedegenie** [comment]
Different message now : 
`------ We have detected a miss configuration reports for device 7639 on ep 01 and cluster 0006
- Attribut 0000 request to force a Configure Reporting due to field MaxInterval 'ffff' != '012C' `


But it's working fine

**Comment by tetedegenie** [comment]
Everything OK.

Thanks !
