### ISSUE TITLE
 [Model Certification] - two-way energy meter Tuya Smart Zigbee PC311-Z-TY

### ISSUE THREAD

**Issue by psytgc** [zigbeefordomoticz/z4d-certified-devices#16]
Version de DomoticZ : 2023.2
Version de Python utilisée par DomoticZ 3.9.2
Système sur lequel tourne DomoticZ avec le plugin : orangepi zero 2
Modèle de coordinateur : Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001
Version de coordinateur : USB
Version du firmware : Znp - Z-Stack 3.30+ (build 20210708)
Type de firmware : standard 
Version du Plugin: 7.1.004 [2.111]
Branche du plugin : stable7
Marque de l’équipement EARU Electric
Modèle de l’équipement PC311-Z-TY
Lien permettant de le commander [https://fr.aliexpress.com/item/10050059 ... pt=glo2fra](https://fr.aliexpress.com/item/1005005931365212.html?spm=a2g0o.order_list.order_list_main.23.21ef5e5bzvMNhs&gatewayAdapt=glo2fra)
Description du fonctionnement attendu remonter des mesure de Consommation sur les 2 pinces

besoin du retour de consommation sur les 2 pince mais pas forcement un ajout L1+L2

report RAW
18:
Version: "3"
ZDeviceName: ""
Status: "UNKNOW"
SQN: "22"
Ep: Object {"01":{"0000":{"0004":"_TZE200_rks0sgb7","0005":"TS0601"},"0004":{},"0005":{},"ef00":{},"ff66":{},"0019":{},"000a":{},"ClusterType":{}}}
Heartbeat: "15609"
RIA: "4"
LQI: 159
Battery: Object {}
Model: "TS0601"
ForceAckCommands: Array[0] []
MacCapa: "8e"
IEEE: "385cfbfffe2771ea"
Type: "DEMAIN"
ProfileID: "0104"
ZDeviceID: "0051"
App Version: ""
Attributes List: Object {}
DeviceType: "FFD"
HW Version: ""
Last Cmds: Array[0] []
LogicalType: "Router"
Manufacturer: "1002"
Manufacturer Name: "_TZE200_rks0sgb7"
NbEp: "1"
PowerSource: "Main"
ReadAttributes: Object {"Ep":{"01":{"0000":{"TimeStamp":"29/10/2023 21:46:43","iSQN":{"0004":"00","0005":"00"},"Attributes":{"0004":"00","0005":"00"},"ZigateRequest":{}}}}}
ReceiveOnIdle: "On"
Stack Version: ""
Stamp: Object {"time":1698690446.7254696,"Time":"2023-10-30 19:27:26","MsgType":"8002","LastSeen":"30/10/2023 19:27:26"}
ZCL Version: ""
Health: "Live"
Capability: Array[5] ["Full-Function Device","Main Powered","Receiver during Idle","Standard security","NwkAddr should be allocated"]
ZDPSQN: "03"
Epv2: Object {"01":{"ProfileID":"0104","ZDeviceID":"0051","ClusterIn":{"0000":{},"0004":{},"0005":{},"ef00":{},"ff66":{}},"ClusterOut":{"0019":{},"000a":{}}}}
ZCLSQN: "00"
ReqEpv2: Object {"01":1698612403.0773525}
RollingLQI: Array[11] [159,159,159,159,159,162,162,162,162,159,159]
WriteAttributes: Object {"Ep":{"01":{"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}}
ZDeviceVersion: "0001"
ConfigSource: "8043"
PairingInProgress: true
_rawNodeDescriptor: "1002005200522c00008e524001"
Max Buffer Size: "52"
Max Rx: "0052"
Max Tx: "0052"
macapa: "8e"
bitfield: "4001"
server_mask: "2c00"
descriptor_capability: "00"
ZCL-IN-SQN: Object {"000a":"72"}
SQN_000a: "72"
Tuya: Object {"Valve 0x01":"00000000","Valve 0x65":"00000000","Valve 0x67":"00000000","Valve 0x66":"00000000","Valve 0x68":"00000000","Valve 0x6a":"00000917","Valve 0x6b":"00000000","Valve 0x69":"00000000"}
Param: Object {}
CheckParam: true
NwkID: "4921"

**Comment by pipiche38** [comment]
Waiting for the device to be shipped
