### ISSUE TITLE
[Model Certification] - Electricity Energy Monitor PJ-1203A Dongguan Pnija Technology

### ISSUE THREAD

**Issue by IW2FAG-11** [zigbeefordomoticz/z4d-certified-devices#17]
PJ-1203A Dongguan Pnija Technology
[1. Provide the URL where you have purchase the device](https://it.aliexpress.com/item/1005006000937905.html?spm=a2g0o.order_list.order_list_main.55.6c093696jWdMkz&gatewayAdapt=glo2ita)

Current A & Current B
Power A &  Power B
Power Factor A & Power Factor B
Forward Energy A & Forward Energy B
Frequency
Voltage

[export.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13244478/export.json)

Thanks for Great Job You are doing

**Comment by pipiche38** [comment]
I'm currently waiting for an other model ( see #16 ), but in between you might want to try 

```
git checkout wip-stable7-1-005
sudo python3 -m pip install -r requirements.txt --upgrade
```

then restart the plugin and redo the pairing (make sure that there is no remaining of the device)

**Comment by IW2FAG-11** [comment]
ok i'll try. seems same

Il giorno gio 2 nov 2023 alle 22:28 Pipiche ***@***.***> ha
scritto:

**Comment by IW2FAG-11** [comment]
Looks working only if I stay on stable 7 with database 2.125
If Upgrade to wip-stable7-1-005 with database 2.125, device look not pairing

**Comment by pipiche38** [comment]
Any messages in the Domoticz or Plugin logs ?

**Comment by IW2FAG-11** [comment]
As You write i do :
git checkout wip-stable7-1-005    in mine plugind domoticz folder
sudo python3 -m pip install -r requirements.txt --upgrade
Then i restarted all mine Rpi 3.
In this case pairing was not workig.
Then i downgrade
git checkout stable7    in mine plugind domoticz folder
sudo python3 -m pip install -r requirements.txt --upgrade
rebooted mine Rpi3
Now pairing was ok.

Now i delete all device
redo upgrade
git checkout wip-stable7-1-005    in mine plugind domoticz folder
sudo python3 -m pip install -r requirements.txt --upgrade
Then i restarted all mine Rpi 3.
In this case pairing was not workig.
Down here recursive message on domoticz during pairing tentative
2023-11-03 10:21:53.110 Zigate: Assisted Pairing: Polling: []
2023-11-03 10:21:53.110 Zigate: --> Empty queue

**Comment by pipiche38** [comment]
please provide the file Logs/PluginLog-xx.log

**Comment by IW2FAG-11** [comment]
[Uploading PluginZigbee_09.zip…]()

**Comment by pipiche38** [comment]
doesn't work !

**Comment by IW2FAG-11** [comment]
Voltage is reported ok


Il giorno ven 3 nov 2023 alle 12:06 Pipiche ***@***.***> ha
scritto:

**Comment by pipiche38** [comment]
If Voltage is ok, would you mind providing once more the export.json with the device info

**Comment by IW2FAG-11** [comment]
[export.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13249511/export.json)
[export(1).json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13249512/export.1.json)

**Comment by IW2FAG-11** [comment]
![IMG_2487](https://github.com/zigbeefordomoticz/z4d-certified-devices/assets/69007986/e7eded19-247d-4299-9001-3b6b47aa5f0b)

**Comment by IW2FAG-11** [comment]
[_PluginZigbee_09(1).zip](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13250361/_PluginZigbee_09.1.zip)
Now with attatched power probe.
Some message with only prob A, and then with every two probe

**Comment by pipiche38** [comment]
I think we should fine tune , did you know what was the power expected on A ?

**Comment by IW2FAG-11** [comment]
[_PluginZigbee_09(1).zip](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13250361/_PluginZigbee_09.1.zip)
Now with attatched power probe.
Some message with only prob A, and then with every two probe

**Comment by IW2FAG-11** [comment]
![image](https://github.com/zigbeefordomoticz/z4d-certified-devices/assets/69007986/46c33576-20fb-4a5b-8215-e2c90596792f)

Current is 1000 time to big
Power is 10 time to big

**Comment by pipiche38** [comment]
ok, try to update the database and simply restart the plugin.

For Power Factor. Is that something requires / important ?

**Comment by IW2FAG-11** [comment]
i'm doing.

All data are interesting.
In Ac
V x I   = VA
V x I x power factor is W real power
V x I x (1-power factor) is W reactive power

reactive power is dissipated and non produce any elettici job work.

Now power looks ok.


Il giorno ven 3 nov 2023 alle 14:53 Pipiche ***@***.***> ha
scritto:

**Comment by pipiche38** [comment]
Ok. I did implement PowerFactor ;-)


```
git pull
sudo python3 -m pip install -r requirements.txt --upgrade
```

If you want to prevent having to repair, you can do the following:

- Remove all related widget minus one. Keep one widget (so the device is not removed)
- Go to WebUI > Provisioning > Recreate widget(s) of existing device
=> It will re-create all widgets and the Power Fcator. You will have only the widget you have not removed duplicated.

**Comment by IW2FAG-11** [comment]
Good morning, I am sorry to disturb you again.
I am doing some more tests.
- I delete all the widgets on the new Tuya_601, start with stable and then upgrade to certified device 2.123, the device is paired and I see some widgets.
- I delete all but one widget, update to wip-stable7-1-005, update to certified device 2.123, have the missing widgets recreated and they show up as for stable7, but I still don't see the one for PoweFactor.
- I delete all the widgets, staying with wip-stable7-1-005, try to pair the meter and the Domoticz log shows ......

2023-11-04 10:02:21.524 Zigate: Assisted Pairing: Polling: []
2023-11-04 10:02:21.524 Zigate: --> Empty queue

Is it possible to reduce the polling frequency by values?
Is it possible to make a "request" from the API via script in LUA or Pyton Domoticz to the device and update as required by the user ?

§§ Another question, I see that with Domoticz Version: 2023.2 (build 15589) 
messages appear 

2023-11-04 10:04:07.800 [WebServer] Deprecated RType (devices) for API request. Handled via fallback (getdevices), please use correct API Command! (192.168.0.100)

I looked at my LUA & Py scripts and I don't seem to be using the old API format, does it come from the Domoticz-Zigbee plugin?

Thanks


Translated with www.DeepL.com/Translator (free version)

**Comment by IW2FAG-11** [comment]
Good morning, I am sorry to disturb you again.
I am doing some more tests.
- I delete all the widgets on the new Tuya_601, start with stable and then upgrade to certified device 2.123, the device is paired and I see some widgets.
- I delete all but one widget, update to wip-stable7-1-005, update to certified device 2.123, have the missing widgets recreated and they show up as for stable7, but I still don't see the one for PoweFactor.
- I delete all the widgets, staying with wip-stable7-1-005, try to pair the meter and the Domoticz log shows ......

2023-11-04 10:02:21.524 Zigate: Assisted Pairing: Polling: []
2023-11-04 10:02:21.524 Zigate: --> Empty queue

Is it possible to reduce the polling frequency by values?
Is it possible to make a "request" from the API via script in LUA or Pyton Domoticz to the device and update as required by the user ?

§§ Another question, I see that with Domoticz Version: 2023.2 (build 15589) 
messages appear 

2023-11-04 10:04:07.800 [WebServer] Deprecated RType (devices) for API request. Handled via fallback (getdevices), please use correct API Command! (192.168.0.100)

I looked at my LUA & Py scripts and I don't seem to be using the old API format, does it come from the Domoticz-Zigbee plugin?

Thanks

**Comment by IW2FAG-11** [comment]
[_PluginZigbee_09.log](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13256216/_PluginZigbee_09.log)
During failing pairing

**Comment by pipiche38** [comment]
> Good morning, I am sorry to disturb you again. I am doing some more tests.
> 
>     * I delete all the widgets on the new Tuya_601, start with stable and then upgrade to certified device 2.123, the device is paired and I see some widgets.
> 
>     * I delete all but one widget, update to wip-stable7-1-005, update to certified device 2.123, have the missing widgets recreated and they show up as for stable7, but I still don't see the one for PoweFactor.
> 
>     * I delete all the widgets, staying with wip-stable7-1-005, try to pair the meter and the Domoticz log shows ......
> 
> 
> 2023-11-04 10:02:21.524 Zigate: Assisted Pairing: Polling: [] 2023-11-04 10:02:21.524 Zigate: --> Empty queue
> 

This looks very strange, and I do not see any issue on the log. Sniffing would be good to understand, what is happening.
I'll try to do some testing on my side.

> Is it possible to reduce the polling frequency by values? Is it possible to make a "request" from the API via script in LUA or Pyton Domoticz to the device and update as required by the user ?

The device itself is doing the reporting,  I know that there is an Update Frequency mecanism, but I'm waiting for the similar device as you to understand how it works with teh Tuya GW.

> 
> §§ Another question, I see that with Domoticz Version: 2023.2 (build 15589) messages appear
> 
> 2023-11-04 10:04:07.800 [WebServer] Deprecated RType (devices) for API request. Handled via fallback (getdevices), please use correct API Command! (192.168.0.100)
> 
> I looked at my LUA & Py scripts and I don't seem to be using the old API format, does it come from the Domoticz-Zigbee plugin?

Normaly the plugin z4d should be clean. Did you check also your dzVents scripts ?

**Comment by pipiche38** [comment]
There is a bug on ZNP which prevent pairing with the current working branch. Sorry, I need to fix it before moving forward

**Comment by IW2FAG-11** [comment]
Don't worry we are here to help you .... on this great job !!


Il giorno sab 4 nov 2023 alle 15:24 Pipiche ***@***.***> ha
scritto:

**Comment by pipiche38** [comment]
You should be able to pair now with the updated wip-stable7-1-005

**Comment by IW2FAG-11** [comment]
Yehaaaa  now pairing is ok.
Still some problem on data..... I'll try to test.

**Comment by IW2FAG-11** [comment]
I did some tests, now it's pairing but I see some problems.
Without loads I read PowerFactor 100% and it matches, then I see Power (usage) at 100W while it should be at '0' as it reads in the device log.
Putting a load of about 450W, I see that the current is shown at 1.9A, the PowerFactor goes to 90% while the Power (usage) which I guess is the instantaneous one shows 90W. It seems that the Power widget still shows the powerfactor.
Reading again in the log, the processed data seems to be correct.


Then paying closer attention, I notice that .....
Voltage refresh occurs, current, for a fraction of time it reads 400W in the Power which is then rewritten with the powerfactor value.

def ts0601_power_factor(self, Devices, nwkid, ep, value):
    self.log.logging( "Tuya0601", "Debug", "ts0601_current - Current %s %s" % (nwkid, ep, value), nwkid, )
    MajDomoDevice(self, Devices, nwkid, ep, "PowerFactor", value)
    store_tuya_attribute(self, nwkid, "PowerFactor_%s" %ep, value)
 
Does it return or is there a mismatch in the argument list ?

**Comment by pipiche38** [comment]
I have updated the code, it was just a mistake in the logging (bad copy paste).
I also think that I understand the issue of mixing Power and PowerFcator

Just pushed an update. So if you can simply do a `git pull` that would be enough

**Comment by IW2FAG-11** [comment]
Ok, now all widget are responsive.
Tomorro i'll test if they are calbrated.
I already know that voltage is perfect but  frequency isn't.

**Comment by pipiche38** [comment]
@IW2FAG-11  what is the out come ?

**Comment by IW2FAG-11** [comment]
Sorry i have had some problem and i'd never do any precision measure. 
Item looks like ok.

**Comment by pipiche38** [comment]
so we can close the issue ?
I think in all case measuring the PowerFactor with the clamp is not the best way ...

**Comment by IW2FAG-11** [comment]
yes.
You can close. Thanks.

I think that also frequency is reported with high error.
With this device i saw 49.13 Hz but with frequencimeter i read about
50.00Hz.

So the device report data also if is not tooo precise.



Il giorno mer 15 nov 2023 alle 13:58 Pipiche ***@***.***> ha
scritto:
