### ISSUE TITLE
[Model Certification] -Woolley Zigbee 3.0 Smart Plug, Mini Outlet Socket SA-030

### ISSUE THREAD

**Issue by Garyxxzx** [zigbeefordomoticz/z4d-certified-devices#18]
Woolley Zigbee 3.0 Smart Plug, Mini Outlet Socket Compatible with Alexa, Google Home and eWelink App, 13A/3120W Model SA-030

Available on Amazon and Aliexpress -  
(https://www.aliexpress.com/item/1005005501350439.html?spm=a2g0o.productlist.main.3.cbea223dkN3xc0&algo_pvid=c39a1078-4cb1-4aac-bb86-4c32a4cb4685&algo_exp_id=c39a1078-4cb1-4aac-bb86-4c32a4cb4685-1&pdp_npi=4%40dis%21EUR%219.47%210.47%21%21%2171.81%21%21%40210387a116989616504703154e3173%2112000035576735758%21sea%21UK%210%21AB&curPageLogUid=Cx9chxCiwDIG#nav-specification)

Appears to link, create widgets and function perfectly, only issue is reporting as non optimised.

[export-3.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13244955/export-3.json)

**Comment by pipiche38** [comment]
I don't think the export matches your description.
From the device info, it looks like a RGB Light. Do you confirm "Bathroom Light" is a plug ?

**Comment by Garyxxzx** [comment]
Hi, Thank you for the reply, actually there bathroom light is another non optimised device that works perfectly, it is an Osram Colour light bulb the same as in the link you posted, I was going to submit a separate issue for that. The smart plug is the first item in the file, listed as "Phone Charger" and shown as a Sonoff SA-030. If you need more information I'll be happy to send it.

**Comment by pipiche38** [comment]
This should be fixed with [2.132]
