### ISSUE TITLE
[Model Certification] - Smart Plug Zigbee 3.0 Boxed as SA-030-16A-BUP  but identified as CK-BL702-SWP-01(7020)

### ISSUE THREAD

**Issue by Garyxxzx** [zigbeefordomoticz/z4d-certified-devices#19]
Purchased from Aliexpress as Woolley SA-030, arrived boxed as unbranded SA-030-16A-BUP

[][(](https://www.aliexpress.com/item/1005006059420667.html?spm=a2g0o.productlist.main.1.32952704seGfEM&algo_pvid=badb7287-5646-4ef1-b231-a13e63ad801a&algo_exp_id=badb7287-5646-4ef1-b231-a13e63ad801a-0&pdp_npi=4%40dis%21EUR%2111.26%217.88%21%21%2111.68%21%21%402103879316990291212308971e8b6f%2112000035549715196%21sea%21UK%210%21AB&curPageLogUid=vmr1tF4QuAOv)url)

Device links with no issues ands creates widgets for Switch, Power, Meter and Current. Switching works fine from Domoticz and reports into Domoticz if device is switched locally however none of the meters display any value and it causes an alarm in the plugin (Alarm file included below) and causes multiple alarms in the Domoticz log as shown;

2023-11-03 16:45:41.197 Error: Zigbee Mesh: ReadCluster - Error/unknow 7e2a/01 Cluster: fc11 Attribute: 7004 Status: 00 DataType: 23 DataSize: 0004 Data: 000000e9
2023-11-03 16:45:41.346 Error: Zigbee Mesh: ReadCluster - Error/unknow 7e2a/01 Cluster: fc11 Attribute: 7005 Status: 00 DataType: 23 DataSize: 0004 Data: 0003c867
2023-11-03 16:45:41.428 Error: Zigbee Mesh: ReadCluster - Error/unknow 7e2a/01 Cluster: fc11 Attribute: 7006 Status: 00 DataType: 23 DataSize: 0004 Data: 0000934e

[export.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13252759/export.json)

[alarm.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13252762/alarm.json)

I would be really grateful for any assistance with these as I have five of them, ordered because the SA-030 I had worked fine!

**Comment by pipiche38** [comment]
it should be fixed with the latest device database.

Do the following command from the home directory of the plugin
`sudo python3 -m pip install -r requirements.txt --upgrade`

**Comment by pipiche38** [comment]
Please check the Power/Current/Voltage should be updated with the version [2.134]
Cross-check the value is correct, as it might have a missing 10 multiplier or divisor

This plug use a Manufacturer specific cluster and I tried to decode it based on what I found in the "Alarm" file (as the export.json was empty )

**Comment by Garyxxzx** [comment]
Thank you for the reply, I will try that and report back to let you know the results.

**Comment by Garyxxzx** [comment]
ok all my devices are shown as optimised so thank you for that! 
The only thing that doesn't seem to work are the meters for the smart plug, I've tried plugging in quite high drain devices (2 Kwh) and all three meters remain at zero. I did notice these alarms in the Domoticz log after I first paired the smart plug after updating the plug in but they have not recurred;

2023-11-03 20:07:10.984 Error: Zigbee Mesh: ReadCluster - Error/unknow 42ca/01 Cluster: fc11 Attribute: 7004 Status: 00 DataType: 23 DataSize: 0004 Data: 00000000
2023-11-03 20:07:11.136 Error: Zigbee Mesh: ReadCluster - Error/unknow 42ca/01 Cluster: fc11 Attribute: 7005 Status: 00 DataType: 23 DataSize: 0004 Data: 0003d7fe
2023-11-03 20:07:11.223 Error: Zigbee Mesh: ReadCluster - Error/unknow 42ca/01 Cluster: fc11 Attribute: 7006 Status: 00 DataType: 23 DataSize: 0004 Data: 00000000

There are no longer any errors from the plugin.

Here is the plug in raw device json file, the smart plug is named Zigbee Plug 2

[export-5.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13254587/export-5.json)

Thank you again for your assistance, I will make a donation to you through your Paypal link

**Comment by Garyxxzx** [comment]
I was looking for more info regarding these smart plugs and someone posted this bit of code which apparently got the meters working with quite accurate outputs, found it on the zigbee2mqtt GitHub page, seems to work as some sort of convertor not sure if it helps but here it is;

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const utils = require('zigbee-herdsman-converters/lib/utils');
const e = exposes.presets;
const ea = exposes.access;

const fzLocal = {
    who_knows: {
        cluster: '64529',
        type: ['attributeReport', 'readResponse'],
        convert: (model, msg, publish, options, meta) => {
            if (utils.hasAlreadyProcessedMessage(msg, model)) return;
            const lookup = [
                {key: '28678', name: 'power', factor: 'acPower'},
                {key: '28677', name: 'voltage', factor: 'acVoltage'},
                {key: '28676', name: 'current', factor: 'acCurrent'},
            ];
            const payload = {};
            for (const entry of lookup) {
                if (msg.data.hasOwnProperty(entry.key)) {
                    const property = utils.postfixWithEndpointName(entry.name, msg, model, meta);
                    const value = msg.data[entry.key] / 1000;
                    payload[property] = utils.calibrateAndPrecisionRoundOptions(value, options, entry.name);
                }
            }
            return payload;
        },
    },
};

const definition = {
    zigbeeModel: ['CK-BL702-SWP-01(7020)'],
    model: 'BSD29',
    vendor: 'Woolley',
    description: 'Zigbee 3.0 smart plug 13A (UK version)',
    fromZigbee: [fz.on_off_skip_duplicate_transaction, fzLocal.who_knows],
    toZigbee: [tz.on_off],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff']);
        await reporting.onOff(endpoint);
        device.powerSource = 'Mains (single phase)';
        device.save();
    },
    exposes: [e.power(), e.current(), e.voltage(), e.switch()],
};

module.exports = definition;

**Comment by pipiche38** [comment]
In fact, the device do not provide Metering. It does provide Voltage, Current and Power. So we should expect Domoticz to compute the Metering based on the Watts proivided

**Comment by Garyxxzx** [comment]
It would seem that is the case however it has created the following widgets in Domoticz 

![IMG_0484](https://github.com/zigbeefordomoticz/z4d-certified-devices/assets/100997299/9d7ccd7c-f6d1-425f-9b5a-c68b00f7b10c)

**Comment by pipiche38** [comment]
did you try to put some load on the plug ?

**Comment by Garyxxzx** [comment]
yeah I put about 2kw on it, people were having the same issue over on zigbee4mqtt but managed to somehow get the power, current & volts working with the piece of code I posted earlier.

**Comment by pipiche38** [comment]
please enable debug parameter TuyaTS0601 and Tuya youcan find it in the WebUI > Tool > Debug

Then leave the plugin running with few minutes with the load on the plug.

Finaly drop here the Logs/PluginZigbee_xx.log file

**Comment by Garyxxzx** [comment]
ok will do, thank you so much for helping!

**Comment by Garyxxzx** [comment]
ok debug parameters set, had load on Zigbee Plug 2 and Zigbee Plug 3 (both are the same type of plug in) If you need me to try anything else just let me know

[PluginZigbee_23.log](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13257815/PluginZigbee_23.log)

**Comment by pipiche38** [comment]
It doesn't look thet debug parameters were enabled.
Could you please enable Inputs, ZclCluster in addition (as it is shown in the screenshoot).

Please drop the full log file from the start of the plugin.

![Screenshot 2023-11-05 at 18 51 19](https://github.com/zigbeefordomoticz/z4d-certified-devices/assets/8291674/c189fd03-7742-4dfd-a4f4-74394370a405)

**Comment by Garyxxzx** [comment]
Ok all done, its quite a large file! The plug in with the most load on it is Zigbee Plug 2 (Microwave)


[PluginZigbee_23.log](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13260457/PluginZigbee_23.log)

**Comment by pipiche38** [comment]
can you try to update the Device Database

sudo python3 -m pip install -r requirements.txt --upgrade


restart the plugin

you should have [2.141]

And let see what is happening. If still not good, please drop the logs with this new version. thanks for your patience

**Comment by Garyxxzx** [comment]
updated to 2.141
restarted plugin, removed device Zigbee Plug 6 and re added as the same name. Have attached log file, plugin restart is 22:10.54 
Widgets created were switch/power/current/meter no voltage widget.

[PluginZigbee_23.log](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13273327/PluginZigbee_23.log)

Thank you again for trying to get this working, it is appreciated. If you need anything else just let me know.

**Comment by Garyxxzx** [comment]
Forgot to add, no readings from any of the meters.

**Comment by pipiche38** [comment]
my bad !

can you kindly update  with
`sudo python3 -m pip install -r requirements.txt --upgrade`

and then. restart the plugin, you should be running [2.144]

**Comment by Garyxxzx** [comment]
That's now working perfectly, thank you so much for your time and patience.
