### ISSUE TITLE
[Model Certification] - One more Tuya eTRV

### ISSUE THREAD

**Issue by Garyxxzx** [zigbeefordomoticz/z4d-certified-devices#23]
Tuya TS0601 TRV purchased from Aliexpress

Device is seen by the plugin but reports an error and no widgets are created in Domoticz. 
Purchased one of these to assess as possible replacements for now obsolete Maxcube TRV's. Chose this model as it should work out of the box. 
Error report attached, if the full pairing log is required let me know and i'll post it here.
Device is shown in the plugin as a TS0601, non optimised and shows createMD in the status column.
I would be grateful for some assistance with this.

[errors-4.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13300109/errors-4.json)

**Comment by pipiche38** [comment]
the error file doesn't help, and it looks like you have a similar error as on the previous issue./

Make sure that Domoticz Settings allow device creation.

Make sure when you do a retry that there is nothing related to this devicve left in domoticz nor in the plugin

Please follow what is documented here : https://github.com/zigbeefordomoticz/z4d-certified-devices/issues/new?assignees=&labels=Device+Integration&projects=&template=certified-device-model.md&title=%5BModel+Certification%5D+-+ for the information to be provided.

Last I strongly recommend you to use the forum first and then. 
`

**Comment by Garyxxzx** [comment]
Hi Pipiche, device removed from plugin, no trace of device in Domoticz. Domoticz Settings allow device creation.
carried out pairing procedure and got the following screen;

![Screenshot 2023-11-08 at 19 44 23](https://github.com/zigbeefordomoticz/z4d-certified-devices/assets/100997299/b836346d-61af-4253-8487-aa3274aefdb7)

Attached Plugin Raw Devices

[export-6.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13300809/export-6.json)

With regards the previous issue, there are 5 smart physical smart plugs connected to the plugin, I connected them all to check they were all functioning, apologies if this caused any confusion. Whenever I've removed a device for and re-paired I have deleted from Domoticz and the Plugin.

**Comment by pipiche38** [comment]
kindly update the Certified Database by doing

sudo python3 -m pip install -r requirements.txt --upgrade

and then restart the plugin.
Check that you get version [2.145]

And then do the pairing of the TRV

**Comment by Carlo069** [comment]
Hi,
  i came here to submit an issue following the guide on the plugin and I find this discussion.
I updated the Certified Database and restart and now the devices are creating in Domoticz.
It's the same on Aliexpress reported before, my model is Avatto ME167.
I can supply my log too, if you need.

I'm a beginner with these devices on Domoticz, for now I can't drive it but I have to look into it further.

Thanks for now.

**Comment by Garyxxzx** [comment]
Hi Pipiche, That has paired and created the following widgets in Domoticz;

Temp
Thermo Setpoint
ThermoMode
Heating Status

All appear to work perfectly with two way functionality. However there is no Valve position or battery level (both in Domoticz and the plugin) is that correct for this TRV? If so can you recommend an optimised TRV with those features?

Thank you once again for the first class support you provide.

**Comment by pipiche38** [comment]
As far as I know that TRV doesn't provide Valve% 

I think that one is providing the Valve% https://zigbee.blakadder.com/Haozee_TRV601.html

**Comment by Garyxxzx** [comment]
Thank you! I may well check one out, to be honest the battery level is probably more useful than the valve position.
