### ISSUE TITLE
Zigbee Tuya Temp Humidity sensor

### ISSUE THREAD

**Issue by mistiiic** [zigbeefordomoticz/z4d-certified-devices#25]
Hi,
I  recently bought a Temp sensor on aliexpress.
It is a Tuya sensor model ZTH01 but it's not reconized by the pluggin and nothing apears in domoticz.

The objet menu give me that:

`{"PluginInfos":{"HardwareID":8,"HomeFolder":"/home/pi/domoticz/plugins/Domoticz-Zigate/","StartupFolder":"/home/pi/domoticz/","UserDataFolder":"/home/pi/domoticz/","WebRoot":"","Database":"/home/pi/domoticz/domoticz.db","Language":"fr","Version":"6.3","Author":"pipiche38","Name":"PiZigateNew","Address":"0.0.0.0","Port":"9999","SerialPort":"/dev/ttyS0","Key":"Zigate","Mode1":"V2","Mode2":"PI","Mode3":"False","Mode4":"9440","Mode6":"2","DomoticzVersion":"2023.2","DomoticzHash":"19efd039c","DomoticzBuildTime":"2023-07-21 17:23:44","PluginBranch":"stable6","PluginVersion":"6.3.013","TimeStamp":1699962502,"available":0,"available-firmMajor":0,"available-firmMinor":0,"FirmwareVersion":"0321","FirmwareUpdate":false,"PluginUpdate":false,"Zigpy":false,"CoordinatorModel":"ZiGate+ (V2)","CoordinatorFirmwareVersion":"0321","DisplayFirmwareVersion":"Zigate - 0321","CoordinatorIEEE":"00158d000500724d","NetworkSize":"Total: 18 | Routers: 10 | End Devices: 8","NetworkDevices":{"1002":{"_TZ3000_hktqahrq":["TS0001"],"_TYZB01_bngwdjsr":["TS1001"],"_TZ3000_ji4araar":["TS0011"],"_TZ3000_qaaysllp":["TS0201-_TZ3000_qaaysllp"],"_TZ3000_tqlv4ug4":["TS0001"],"_TZ3210_mja6r5ix":["TS0505B"],"_TZ3000_o005nuxx":["TS011F"],"_TZ3000_dbou1ap4":["TS0505A"]},"1141":{"_TZ3000_cfnprab5":["TS011F"],"_TZ3000_oxslv1c9":["TS0203"],"_TZ3000_6zvw8ham":["TS0203"]},"1189":{"LEDVANCE":["Plug Z3"]},"0000":{"eWeLink":["TH01","DS01"]}}},"Analytics":0,"Device":{"Version":"3","ZDeviceName":"","Status":"UNKNOW","SQN":"03","Ep":{"01":{"0000":{"0004":"_TZE200_yjjdcqsq","0000":"3","0001":"72","0005":"TS0601","0007":"3","fffe":"0","ffe2":"56","ffe4":"0","ffdf":"%,f%,\u0012%,e"}}},"Heartbeat":"34","RIA":"6","LQI":96,"Battery":{},"Model":"TS0601","ForceAckCommands":[],"MacCapa":"80","IEEE":"a4c1386dfc756d62","Type":{},"ProfileID":{},"ZDeviceID":{},"App Version":"72","Attributes List":{},"DeviceType":"RFD","HW Version":"","Last Cmds":[[53862,"02","5305","0100","01010000000000000600040000000100050007fffe"],[53870,"02","5305","0110","010100000000000001ffde2013"],["None","02","5305","0110","010100000000000001ffde2013"]],"LogicalType":"End Device","Manufacturer":"1141","Manufacturer Name":"_TZE200_yjjdcqsq","NbEp":"1","PowerSource":"Battery","ReadAttributes":{"Ep":{"01":{"0000":{"TimeStamp":1699962314,"iSQN":{"0004":53862,"0000":53862,"0001":53862,"0005":53862,"0007":53862,"fffe":53862},"Attributes":{"0004":"00","0000":"00","0001":"00","0005":"00","0007":"00","fffe":"00","ffe2":"00","ffe4":"00","ffdf":"00"},"ZigateRequest":{}}}}},"ReceiveOnIdle":"Off","Stack Version":"","Stamp":{"time":1699962419.289369,"Time":"2023-11-14 12:46:59","MsgType":"8011","LastSeen":1699962419},"ZCL Version":"3","Health":"Live","Capability":["Reduced-Function Device","Standard security","NwkAddr should be allocated"],"ZDPSQN":"00","RollingLQI":[96,97,97,94,94,95,95,95,95,96,96],"WriteAttributes":{"Ep":{"01":{"0000":{"TimeStamp":1699962413,"iSQN":{"ffde":53870},"Attributes":{"ffde":"dc"},"ZigateRequest":{"ffde":{"Status":"fullfilled","DataType":"20","EPin":"01","EPout":"01","manuf_id":"0000","manuf_spec":"00","data":"13","ackIsDisabled":false}}}}}},"Epv2":{"01":{"ClusterIn":{},"ClusterOut":{},"ProfileID":{},"ZDeviceID":{}}},"PairingInProgress":true,"SQN_000a":"fc","ConsistencyCheck":"Bad Pairing","ZCLSQN":"04","Tuya":{"TuyaTransactionId":1},"_rawNodeDescriptor":"1141004200422a000080424002","Max Buffer Size":"42","Max Rx":"0042","Max Tx":"0042","macapa":"80","bitfield":"4002","server_mask":"2a00","descriptor_capability":"00"}}
`
Let me know if you need more info

Thanks

**Comment by pipiche38** [comment]
You are on an out-dated version of the plugin which is not supported anymore

![Screenshot 2023-11-14 at 21 58 16](https://github.com/zigbeefordomoticz/z4d-certified-devices/assets/8291674/037ee2c0-5c14-4e6a-9f14-7f4642d728ef)

You must be running bulleyes at least with python3.8 ( buster not supported anymore )

https://zigbeefordomoticz.github.io/wiki/en-eng/Release_7.1.html
