### ISSUE TITLE
[Model Certification] - Tuya - Human Presence Detector 5.8GHz ceiling Mount

### ISSUE THREAD

**Issue by bartw91** [zigbeefordomoticz/z4d-certified-devices#26]
you have helped me adding the wall mounted version to domoticz last week. 
can you help me with the problem i have adding the ceiling mount version?
https://zigbee.blakadder.com/Tuya_ZY-M100-L.html

The devices is succesfully added to zigbee plugin and domoticz, domoticz  just doesnt receive any data from the motion or lux sensor.

Zigbee plugin log:

[errors (4).json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13349911/errors.4.json)
[PluginZigbee_48.log](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13349949/PluginZigbee_48.log)

Domoticz log:
2023-11-14 15:22:16.699 Error: Zigbee : Receiving a leave from 0206/a4c1386fdc96a0e6 while device is Leave status
2023-11-14 15:22:16.712 Error: Zigbee : Receiving a leave from 0206/a4c1386fdc96a0e6 while device is Leave status

![domoticz](https://github.com/zigbeefordomoticz/z4d-certified-devices/assets/111068907/1cb79759-c4d7-4995-9b53-f548cc9ca3db)

**Comment by pipiche38** [comment]
Please provide some informations:

either the logs with the pairing
and the information on the devices

> 1. Got to the Tools Menu
> 1. Select Plugin Raw Devices (json)
> 1. Export
> 

It is probably a new comers but we should have the definition in house.

**Comment by bartw91** [comment]
[export (3).json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13355697/export.3.json)

**Comment by pipiche38** [comment]
Thanks for the information.
This should be supported out of the box. 

let me try to summarize the situation.

It looks the pairing works, then you get the Motion and Lux widgets created on Domoticz
From what I see the device seems to be located near to the Coordinator as the LQI is quiet hight
But pretty fast the device send a leave and exit the Zigbee network.

If I look to the mac address of your Coordinator that sound to be a Silicon Laboratories.
You have already a nice number of devices.

Can you try to enable "Disable direct pairing on Coordinator" option from the WebUI > Setting > Advanced
then restart the plugin , and do the pairing again.
I would also try to do the pairing, not closed to the coordinator, but more to a router

![Screenshot 2023-11-14 at 22 13 49](https://github.com/zigbeefordomoticz/z4d-certified-devices/assets/8291674/36767fd7-7cc3-4b03-9082-cb8cbc18aa22)

let see what will happen

**Comment by bartw91** [comment]
Yes that did the trick, Merci!

**Comment by bartw91** [comment]
I have a issue with changing the sensitivity and max range settings.
I have added the following extra parameters:
{ 'radar_sensitivity': 1, 'maximum_range': 1}

but i see no change in the sensitivity or range, am i doing something wrong?

**Comment by pipiche38** [comment]
For now, and for this specific device, the parameters are not integrated. And by default you don't have them

**Comment by bartw91** [comment]
That is too bad, because the motion radar is so sensitive, that it really needs to be tweaked depending on the installed location. I hope it will be added in the near future. Thanks again for the quick responds!

**Comment by pipiche38** [comment]
"TuyaRadarSensitivity": 7,   
        "TuyaPresenceSensitivity": 9,
        "TuyaRadarMaxRange": 550,   5.40 m ( that is the max , and you cannot go below 1.50 m )
        "TuyaFadingTime": 60

Here after are Tuya's quick setup.
Sleep: 
`TuyaPresenceSensitivity: 0x4 TuyaRadarSensitivity: 0x02 TuyaRadarMaxRange: 0x226 TuyaFadingTime: 0x12c`
Bathroom: 
`TuyaPresenceSensitivity: 0x6 TuyaRadarSensitivity: 0x04 TuyaRadarMaxRange: 0x15e TuyaFadingTime: 0x1e`
Bedroom: 
`TuyaPresenceSensitivity: 0x6 TuyaRadarSensitivity: 0x04 TuyaRadarMaxRange: 0x226 TuyaFadingTime: 0x78`
LivingRoom: 
`TuyaPresenceSensitivity: 0x6 TuyaRadarSensitivity: 0x04 TuyaRadarMaxRange: 0x226 TuyaFadingTime: 0x3c`

**Comment by pipiche38** [comment]
If you want to test the Radar parameters, please do the following

1- remove all parameters from the existing device. leave it like {} make sure it is save
2- update the plugin and switch to the 'tuya-human-sensor-parameters' branch

```
git pull
git checkout tuya-human-sensor-parameters
git pull
sudo python3 -m pip install -r requirements.txt --upgrade
```

This should move you to 7.1.005 [2.150] after the restart of the plugin

After the restart new parameters will be loaded to the Device parameters section ... You can play with that

**Comment by bartw91** [comment]
This works perfectly, merci!
