### ISSUE TITLE
[Model Certification] - ZY-W100

### ISSUE THREAD

**Issue by Snake40** [zigbeefordomoticz/z4d-certified-devices#28]
Désolé pour le raté précédent ...

Il y a peu, grâce à votre aide, j'ai intégré un capteur de présence à micro-onde dans Domoticz. Celui-ci fonctionne en détection de luminosité mais n'a jamais fait la moindre détection. Pour lever le doute sur son fonctionnement, j'ai fait l'achat d'un capteur similaire chez un autre fournisseur. Son intégration à zigbeefordomoticz donne un produit déclaré à nouveau "non optimisé" et Domoticz ne le reconnaît pas. L'objet de ma requête est donc de régler cette anomalie.

1 - Model ZY-W100
2 - URL where I have purchase the device
(https://fr.aliexpress.com/item/1005005477612297.html spm=a2g0o.order_list.order_list_main.23.21ef5e5bcj1cPc&gatewayAdapt=glo2fra)
3 - Json export :
{"PluginInfos":{"HardwareID":7,"HomeFolder":"/opt/domoticz/userdata/plugins/Domoticz-Zigbee/","StartupFolder":"/opt/domoticz/","UserDataFolder":"/opt/domoticz/userdata/","WebRoot":"","Database":"/opt/domoticz/userdata/domoticz.db","Language":"fr","Version":"7.1","Author":"pipiche38","Name":"Zigbee","Address":"0.0.0.0","Port":"9999","SerialPort":"/dev/ttyACM0","Key":"Zigate","Mode1":"ZigpyEZSP","Mode2":"USB","Mode3":"False","Mode4":"9440","Mode6":"2","DomoticzVersion":"2023.2 (build 15555)","DomoticzHash":"94ed578b5","DomoticzBuildTime":"2023-09-18 11:18:01","PluginBranch":"stable7","PluginVersion":"7.1.004","CertifiedDbVersion":"2.151","TimeStamp":1700730606,"available":0,"available-firmMajor":0,"available-firmMinor":0,"FirmwareVersion":"6.10.3.0 build 297","FirmwareUpdate":false,"PluginUpdate":false,"LogLevel":7,"Zigpy":true,"CoordinatorModel":"Unknown Silicon Labs","DisplayFirmwareVersion":"UNK - 6.10.3.0 build 297","CoordinatorIEEE":"e0798dfffe71910c","NetworkSize":"Total: 25 | Routers: 8 | End Devices: 17","NetworkDevices":{"1002":{"_TZE200_b6wax7g0":["TS0601-_TZE200_b6wax7g0"],"_TYZB01_ftdkanlj":["TS0222"],"_TZ3000_dowj6gyi":["TS0201"]},"1141":{"_TZ3000_gjnozsaz":["TS011F-plug"],"_TZ3000_dowj6gyi":["TS0201"],"_TZ3000_tqlv4ug4":["TS0001"],"_TZE204_t1blo2bj":["TS0601-_TZE200_t1blo2bj"],"_TZ3000_decxrtwa":["TS0203"]}}},"Analytics":1,"Device":{"Version":"3","ZDeviceName":"","Status":"UNKNOW","SQN":"b3","Ep":{"01":{"0000":{"0004":"_TZE204_qasjif9e","0000":3,"0001":74,"0005":"TS0601","0007":1,"fffe":0,"ffe2":56,"ffe4":1},"0004":{},"0005":{},"ef00":{},"0019":{},"000a":{}},"f2":{}},"Heartbeat":"158","RIA":"4","LQI":255,"Battery":{},"Model":"TS0601","ForceAckCommands":[],"MacCapa":"8e","IEEE":"a4c1381004b1ce95","Type":{},"ProfileID":"0104","ZDeviceID":"0051","App Version":74,"Attributes List":{},"DeviceType":"FFD","HW Version":"","Last Cmds":[],"LogicalType":"Router","Manufacturer":"1141","Manufacturer Name":"_TZE204_qasjif9e","NbEp":"2","PowerSource":"Main","ReceiveOnIdle":"On","Stack Version":"","Stamp":{"time":1700730405.3082445,"Time":"2023-11-23 10:06:45","MsgType":"8011","LastSeen":1700730405},"ZCL Version":3,"Health":"Live","Capability":["Full-Function Device","Main Powered","Receiver during Idle","Standard security","NwkAddr should be allocated"],"ZCLSQN":"00","ZDPSQN":"04","ZCL-IN-SQN":{"ef00":"b3","000a":"54","0000":"86"},"RollingLQI":[255,255,255,255,255,255,255,255,255,255,255],"Epv2":{"01":{"ProfileID":"0104","ZDeviceID":"0051","ClusterIn":{"0004":{},"0005":{},"ef00":{},"0000":{}},"ClusterOut":{"0019":{},"000a":{}}}},"ReqEpv2":{"01":1700729699.558496},"Tuya":{"Valve 0x68":"00000006","TUYA_MCU_VERSION_RSP":"42","Valve 0x65":"00000001","Valve 0x66":"00000032","Valve 0x01":"01"},"ZDeviceVersion":"0001","ConfigSource":"8043","PairingInProgress":true,"_rawNodeDescriptor":"1141004200422a00008e424001","Max Buffer Size":"42","Max Rx":"0042","Max Tx":"0042","macapa":"8e","bitfield":"4001","server_mask":"2a00","descriptor_capability":"00","SQN_000a":"54"}}

Merci.

**Comment by pipiche38** [comment]
should be fixed with [2.154]
Will require full re-pairing

**Comment by Snake40** [comment]
Merci encore pour ton aide ... Le détecteur est bien reconnu par le plugin, je suis passé du build 2151 au build 2155 et cette fois je récupère de la détection contrairement à mon modèle précédent qui doit être HS ...--------------------------envoyé : 23 novembre 2023 à 22:59de : Pipiche ***@***.***>à : zigbeefordomoticz/z4d-certified-devices ***@***.***>cc : Snake40 ***@***.***>, Author ***@***.***>objet : Re: [zigbeefordomoticz/z4d-certified-devices] [Model Certification] - ZY-W100 (Issue #28) should be fixed with [2.154] Will require full re-pairing—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
