### ISSUE TITLE
[Model Certification] - Philips Hue White Smart Bulb B22 1100 lumens LWA018

### ISSUE THREAD

**Issue by Garyxxzx** [zigbeefordomoticz/z4d-certified-devices#29]
Philips Hue White Smart Bulb B22 1100 lumens LWA018 9 watts - 75 watt equivalent

[[]](https://amzn.eu/d/3omQxnc)(url)

Product paired with no errors, widgets created correctly. No issues at all except for showing as non certified.

[export-8.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13468085/export-8.json)

**Comment by pipiche38** [comment]
Will be fixed with [2.156]

**Comment by Garyxxzx** [comment]
That’s great, thank you!
