### ISSUE TITLE
[Model Certification] - An other TS130F Blind switch

### ISSUE THREAD

**Issue by anthropo** [zigbeefordomoticz/z4d-certified-devices#30]
* TS130F
    * Aubess
    * https://fr.aliexpress.com/item/1005005136748015.html?spm=a2g0o.order_list.order_list_main.46.783c5e5bfo4EBS&gatewayAdapt=glo2fra
    * This object is recognized as not optimized

[export.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13479652/export.json)

**Comment by anthropo** [comment]
[PluginZigbee_04.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13479941/PluginZigbee_04.json)

The topology doesn't work, don't know if it is related

**Comment by pipiche38** [comment]
Please update the plugin so you get the latest certified device Db [2.157] 
Then remove the existing paired device
restart the plugin
redo the pairing

**Comment by anthropo** [comment]
Nickel !!!

I was just surprised the plugin update didn't upgrade the z4d-certified-devices directly (seems to first upgrade to different versions, previous in my case was 2.156)
So i upgraded like that : 

sudo python3 -m pip install z4d-certified-devices --upgrade --break-system-packages
Requirement already satisfied: z4d-certified-devices in /usr/local/lib/python3.11/dist-packages (2.156)
Collecting z4d-certified-devices
  Downloading z4d_certified_devices-2.157-py3-none-any.whl (357 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 357.1/357.1 kB 6.0 MB/s eta 0:00:00
Installing collected packages: z4d-certified-devices
  Attempting uninstall: z4d-certified-devices
    Found existing installation: z4d-certified-devices 2.156
    Uninstalling z4d-certified-devices-2.156:
      Successfully uninstalled z4d-certified-devices-2.156
Successfully installed z4d-certified-devices-2.157

**Comment by pipiche38** [comment]
It could be a timing issue, as the new version was maybe not yet published (I'm not controlling this aspect), as plugin upgrade should do the job as you did manually.

I leave it to you to close the issue :-) and enjoy

**Comment by anthropo** [comment]
Thank You !
