### ISSUE TITLE
[Model Certification] - Nous A4Z ZigBee Outdoor Smart Socket

### ISSUE THREAD

**Issue by kristoferw** [zigbeefordomoticz/z4d-certified-devices#31]
Nous A4Z ZigBee Outdoor Smart Socket
https://nous.technology/product/a4z.html

Two socket IP44 outdoor zigbee plug with power metering

Pairs with Zigbee for Domoticz as a single outlet without power metering.

[export (2).json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13537647/export.2.json)

**Comment by pipiche38** [comment]
Electric measurement is reported for the 2 plug, there is not electric measurement per plug

**Comment by pipiche38** [comment]
You need to update the plugin to get the latest Certified Db version [2.158]
Then you need to remove the domoticz widgets which have been created during the previous pairing

the restart the plugin and check that the device is not known anymore not in Domotciz and not in the plugin

then redo the pairing
