### ISSUE TITLE
[Model Certification] - Tuya siren Alarm TS0224

### ISSUE THREAD

**Issue by anthropo** [zigbeefordomoticz/z4d-certified-devices#32]
Tuya siren Alarm, bought at Aliexpress https://www.aliexpress.com/item/1005004701151756.html?spm=a2g0o.order_list.order_list_main.115.cb675e5bvQtWES

It is recognized as not optimized

DeConz - TS0224_Voltage-a4c138afe26578ba-01
DeConz - TS0224_Switch-a4c138afe26578ba-01
DeConz - TS0224_ColorControlRGBWW-a4c138afe26578ba-01
DeConz - TS0224_Door-a4c138afe26578ba-01
DeConz - TS0224_AlarmWD-a4c138afe26578ba-01 

[TS0224.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13544180/TS0224.json)
Thank you

**Comment by anthropo** [comment]
[PluginZigbee_02.log](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13545468/PluginZigbee_02.log)

**Comment by pipiche38** [comment]
https://zigbee.blakadder.com/iAlarm_SR01.html

**Comment by pipiche38** [comment]
Could you confirm if:

- DeConz - TS0224_Switch-a4c138afe26578ba-01 works ? means it switch On or Off the Alarm ?

**Comment by anthropo** [comment]
So siren lights, alarm sounds, strobe does nothing, stop does its job,

and i don't know whet is the purpose of armed and disarmed on this device.

I join a new log.
[PluginZigbee_02.log](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13551045/PluginZigbee_02.log)

**Comment by anthropo** [comment]
I resetted the device, here is the log again and what it does : 

DeConz - TS0224_ColorControlFull-a4c138afe26578ba-01 Does Nothing
DeConz - TS0224_Voltage-a4c138afe26578ba-01 is 0.2v

DeConz - TS0224_Switch-a4c138afe26578ba-01 Lights the device continuously (not flashes)
(Then DeConz - TS0224_Door-a4c138afe26578ba-01 reports its state)

And DeConz - TS0224_AlarmWD-a4c138afe26578ba-01 when i clic on it it scares my dog while sounding and flashing on 
Disarmed sounds it while armed stops the sound (no flashes at all)
Alarm sounds only
I confirm Siren only flashes the light
Strobe does nothing
Armed does Nothing
[TS0224.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13561609/TS0224.json)
[PluginZigbee_02.log](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13561610/PluginZigbee_02.log)

**Comment by pipiche38** [comment]
Where are you based ? Would you mind shipping it to me for integration and then I send it back to you ?

**Comment by pipiche38** [comment]
Support 

Switch to Switch On/Off the Light
Alarm is supported with the Burglar Warning Mode ( "alarmSirenCode": 1 )

Requires 7.1.010
