### ISSUE TITLE
[Model Certification] - QS-Zigbee-ECC02

### ISSUE THREAD

**Issue by anthropo** [zigbeefordomoticz/z4d-certified-devices#33]
QS-Zigbee-CP03 Tuya Zigéquation bought at Aliexpress https://fr.aliexpress.com/item/1005004305456533.html?spm=a2g0o.order_list.order_list_main.103.75865e5b6eW2fh&gatewayAdapt=glo2fra

It is not recognized as optimized but as TS130F. I have another TS130F that works (from Aubess, * https://fr.aliexpress.com/item/1005005136748015.html?spm=a2g0o.order_list.order_list_main.46.783c5e5bfo4EBS&gatewayAdapt=glo2fra)

I have the  the latest certified device Db [2.158]

[QS-Zigbee-ECC02.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13544327/QS-Zigbee-ECC02.json)

Thank you

**Comment by anthropo** [comment]
[PluginZigbee_17.log](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13545754/PluginZigbee_17.log)

Sorry but in the meantime the reset switch has broken.... I only have an old log file. But it has this device logged

Thank you

**Comment by pipiche38** [comment]
Unfortunatly I cannot find the necessary information.
Would you mind removing all Domoticz widgets associated to this device.
Checking that the device is not in the plugin anymore
and then redo the pairing.

Then provides the logs and the [QS-Zigbee-ECC02.json]

**Comment by anthropo** [comment]
[PluginZigbee_02.log](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13556689/PluginZigbee_02.log)

Thanks

**Comment by anthropo** [comment]
[QS-Zigbee-ECC02.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13556701/QS-Zigbee-ECC02.json)

**Comment by pipiche38** [comment]
to reset the module, you have to remove it from the distribution box and insert a clip into the hole.
 If you prefer to do power on-off on-off on-off and the device goes into adoption mode.
