### ISSUE TITLE
[Model Certification] - Tuya Zigequation-Capteur de température et d'humidité

### ISSUE THREAD

**Issue by anthropo** [zigbeefordomoticz/z4d-certified-devices#35]
I bought a  Tuya Zigequation-Capteur de température et d'humidité
https://fr.aliexpress.com/item/1005006030373016.html?spm=a2g0o.order_list.order_list_main.35.1b175e5bEuTjRn&gatewayAdapt=glo2fra

But it refuses to bind
[TS0601 Thermomètre.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13561953/TS0601.Thermometre.json)
[PluginZigbee_02.log](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13561954/PluginZigbee_02.log)
. 

Here are the logs.

Thank you

**Comment by pipiche38** [comment]
please update to the latest Certified Db [ 2.159 ]
Remove the existing widgets from domoticz
make sure that the device doesn't exist any more in the plugin
restart the plugin

do a pairing

**Comment by anthropo** [comment]
It works ! Thank you.

That said, i started the device yesterday and the battery is already empty... I hope it was a defctive battery, i changed it i'll see tomorrow

**Comment by anthropo** [comment]
In fact that device freezes it looses connection, hangs no more temperature changes....

A bad batch perhaps but i don't recommend buying it. The battery lasted one day ! I changed it but now the device seems dead.

Can you just tell me what you think about the plugin error please ?

**Comment by pipiche38** [comment]
Please use the Forum for such question.
https://easydomoticz.com/forum/viewtopic.php?p=117164&sid=6f27d3461a79aa273c59317cbba29ced#p117164
