### ISSUE TITLE
Zigbee plugin cannot optimize Sonoff TRVZB thermo

### ISSUE THREAD

**Issue by temolder** [zigbeefordomoticz/z4d-certified-devices#36]
[export.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13628930/export.json)
1. Please do provide device information such as Brand and Model name.
1. Provide the URL where you have purchase the device
    * Product Name
    * Brand
    * URL on a web site
    * What do you expect

1. Document as much what works, what doesn't work, what do you miss, what do you need

1. Got to the Tools Menu
1. Select Plugin Raw Devices (json)
1. Export

This will create an export.json file that you can save.

# Donations and Sponsorship

We warmly invite Manufacturers and sellers to contribute by sending us samples of their devices for integration. Your support in this regard is greatly appreciated as it enables us to expand our compatibility and offer a more comprehensive solution.

We extend our heartfelt gratitude to our generous donors whose contributions enable us to acquire additional equipment for rigorous testing and seamless integration. With your support, we can further enhance the plugin's capabilities and deliver an even more powerful and versatile experience for our users.

Donate via PayPal https://paypal.me/pipiche

**Comment by pipiche38** [comment]
Is the device working correctly ?

**Comment by temolder** [comment]
Yes, device is werking, but i receive error message like:


2023-12-10 21:00:05.568 Error: Zigbee: ReadCluster - Error/unknow 7a01/01
Cluster: fc11 Attribute: 6007 Status: 00 DataType: 21 DataSize: 0002 Data:
0535
2023-12-10 21:00:05.606 Error: Zigbee: ReadCluster - Error/unknow 7a01/01
Cluster: fc11 Attribute: 6009 Status: 00 DataType: 29 DataSize: 0002 Data:
09c4

Op zo 10 dec. 2023 20:33 schreef Pipiche ***@***.***>:

**Comment by pipiche38** [comment]
would be great if you could drop me the logfile ... I can investigate

is the Switch doing something ?
could you elaborate what is working 
Setpoint ?
Local temperature ?
System Mode ?
Switch ?

**Comment by temolder** [comment]
As far as I can see, the sonoff TRVZB Thermostat is working.

e.g. at 07:30 hours, the temperature in bathroom is set to 25 degrees. This
works. And I receive the local temparature. The system Thermo mode was set
to "auto". The TRVZB-switch is on.


At 07:31 I receive this mail:

Multiple errors received in the last 5 minutes:

2023-12-11 07:30:05.535 Error: Zigbee: ReadCluster - Error/unknow 7a01/01
Cluster: fc11 Attribute: 6007 Status: 00 DataType: 21 DataSize: 0002 Data:
0534
2023-12-11 07:30:05.658 Error: Zigbee: ReadCluster - Error/unknow 7a01/01
Cluster: fc11 Attribute: 6009 Status: 00 DataType: 29 DataSize: 0002 Data:
09c4

Attached the requested log-file.

**Comment by temolder** [comment]
Attached the logfile


---------- Forwarded message ---------
From: Andre te Molder ***@***.***>
Date: Mon, Dec 11, 2023 at 11:18 AM
Subject: Re: [zigbeefordomoticz/z4d-certified-devices] Zigbee plugin cannot
optimize Sonoff TRVZB thermo (Issue #36)
To: zigbeefordomoticz/z4d-certified-devices <
***@***.***>


As far as I can see, the sonoff TRVZB Thermostat is working.

e.g. at 07:30 hours, the temperature in bathroom is set to 25 degrees. This
works. And I receive the local temparature. The system Thermo mode was set
to "auto". The TRVZB-switch is on.


At 07:31 I receive this mail:

Multiple errors received in the last 5 minutes:

2023-12-11 07:30:05.535 Error: Zigbee: ReadCluster - Error/unknow 7a01/01
Cluster: fc11 Attribute: 6007 Status: 00 DataType: 21 DataSize: 0002 Data:
0534
2023-12-11 07:30:05.658 Error: Zigbee: ReadCluster - Error/unknow 7a01/01
Cluster: fc11 Attribute: 6009 Status: 00 DataType: 29 DataSize: 0002 Data:
09c4

Attached the requested log-file.

**Comment by temolder** [comment]
Good evening

I did some tests:
TRVZB switch: set to off
Automatically, this results in:
- Thermo mode goes to off
- Thermo setpoint goes to 7 degrees

A mail was received with content:
2023-12-13 19:01:16.509 Error: Zigbee: ReadCluster - Error/unknow 7a01/01
Cluster: fc11 Attribute: 6002 Status: 00 DataType: 29 DataSize: 0002 Data:
02bc



Next, zet Thermo setpoint to 15 degrees.
automatically, this results in:
- TRVZB switch is set to on
- Thermo mode is set to "cool"

A new mail was received with content:
2023-12-13 19:03:06.323 Error: Zigbee: ReadCluster - Error/unknow 7a01/01
Cluster: fc11 Attribute: 6009 Status: 00 DataType: 29 DataSize: 0002 Data:
05dc

Attached the log info I could find.

**Comment by temolder** [comment]
Good evening,

Just to let you know that everything is working fine after re-install
Zigbee plugin.
No errors anymore and object TRVZB is "optimized with the plugin" (green
checkmark in menu).

Regards,
Andre

---------- Forwarded message ---------
From: Andre te Molder ***@***.***>
Date: Wed, Dec 13, 2023 at 7:11 PM
Subject: Re: [zigbeefordomoticz/z4d-certified-devices] Zigbee plugin cannot
optimize Sonoff TRVZB thermo (Issue #36)
To: zigbeefordomoticz/z4d-certified-devices <
***@***.***>


Good evening

I did some tests:
TRVZB switch: set to off
Automatically, this results in:
- Thermo mode goes to off
- Thermo setpoint goes to 7 degrees

A mail was received with content:
2023-12-13 19:01:16.509 Error: Zigbee: ReadCluster - Error/unknow 7a01/01
Cluster: fc11 Attribute: 6002 Status: 00 DataType: 29 DataSize: 0002 Data:
02bc



Next, zet Thermo setpoint to 15 degrees.
automatically, this results in:
- TRVZB switch is set to on
- Thermo mode is set to "cool"

A new mail was received with content:
2023-12-13 19:03:06.323 Error: Zigbee: ReadCluster - Error/unknow 7a01/01
Cluster: fc11 Attribute: 6009 Status: 00 DataType: 29 DataSize: 0002 Data:
05dc

Attached the log info I could find.

**Comment by pipiche38** [comment]
Glad that it works. I think they are some room for improvment as I found a number of manufacturer specific infos, but if that is enought for you let's close this issue for now
