### ISSUE TITLE
[Model Certification] - NodOn SIN4-1-20

### ISSUE THREAD

**Issue by Bastien92** [zigbeefordomoticz/z4d-certified-devices#37]
Hello,

Just to report that the following device appears as un optimized. But i am able to switch it on and switch it off manually from Zigbee web interface.
Thanks for your job!

1. Please do provide device information such as Brand and Model name.
1. Provide the URL where you have purchase the device
    * Product Name : SIN-4-1-20
    * Brand : NodOn
    * URL on a web site : https://nodon.fr/en/nodon/zigbee-multifunction-relay-switch/?portfolioCats=369
    * What do you expect : 

1. Document as much what works, what doesn't work, what do you miss, what do you need

1. Got to the Tools Menu
1. Select Plugin Raw Devices (json)
1. Export

This will create an export.json file that you can save.

# Donations and Sponsorship

We warmly invite Manufacturers and sellers to contribute by sending us samples of their devices for integration. Your support in this regard is greatly appreciated as it enables us to expand our compatibility and offer a more comprehensive solution.

We extend our heartfelt gratitude to our generous donors whose contributions enable us to acquire additional equipment for rigorous testing and seamless integration. With your support, we can further enhance the plugin's capabilities and deliver an even more powerful and versatile experience for our users.

Donate via PayPal https://paypal.me/pipiche

**Comment by pipiche38** [comment]
please provide the Device Information. Without we cannot do much

**Comment by Bastien92** [comment]
Hello,

Is this helpfull:

{"PluginInfos":{"HardwareID":4,"HomeFolder":"/home/root/domoticz/plugins/Domoticz-Zigbee/","StartupFolder":"/home/root/domoticz/","UserDataFolder":"/home/root/domoticz/","WebRoot":"","Database":"/home/root/domoticz/domoticz.db","Language":"fr","Version":"7.1","Author":"pipiche38","Name":"Sonoff Gateway Zigbee","Address":"0.0.0.0","Port":"9999","SerialPort":"/dev/ttyACM0","Key":"Zigate","Mode1":"ZigpyEZSP","Mode2":"USB","Mode3":"True","Mode4":"9440","Mode6":"0","DomoticzVersion":"2023.2 (build 15457)","DomoticzHash":"25624ca14","DomoticzBuildTime":"2023-07-22 10:39:06","PluginBranch":"stable7","PluginVersion":"7.1.007","CertifiedDbVersion":"3.164","TimeStamp":1703107243,"available":"7.1.007","available-firmMajor":0,"available-firmMinor":0,"FirmwareVersion":"6.10.3.0 build 297","FirmwareUpdate":false,"PluginUpdate":false,"LogLevel":7,"Zigpy":true,"CoordinatorModel":"Unknown Silicon Labs","CoordinatorFirmwareVersion":"6.10.3.0 build 297","DisplayFirmwareVersion":"UNK - 6.10.3.0 build 297","CoordinatorIEEE":"e0798dfffec10aec","NetworkSize":"Total: 2 | Routers: 1 | End Devices: 1","NetworkDevices":{}},"Analytics":1,"Device":{"Version":"3","ZDeviceName":"Cumulus ","Status":"inDB","SQN":"51","Ep":{"01":{"1000":{},"0000":{"0004":"NodOn","0005":"SIN-4-1-20","0000":8,"0001":2,"0002":103,"0003":34,"0006":"2020","0007":1,"0014":0,"fffd":1},"0003":{"0000":0},"0004":{},"0005":{},"0006":{"4000":"01","4001":0,"4002":0,"4003":255,"0000":"00","fffd":1},"0007":{"0000":0,"0010":2},"fc57":{},"0019":{},"ClusterType":{"7":"Switch"}},"f2":{"0021":{}}},"Heartbeat":"312","RIA":"4","LQI":104,"Battery":{},"Model":"SIN-4-1-20","ForceAckCommands":[],"MacCapa":"8e","IEEE":"003c84fffed45305","Type":"Switch","ProfileID":"0104","ZDeviceID":"0100","App Version":2,"Attributes List":{"Ep":{"01":{"1000":{"fffd":"21"},"0000":{"0000":"20","0001":"20","0002":"20","0003":"20","0004":"42","0005":"42","0006":"42","0007":"30","0014":"18","fffd":"21"},"0003":{"0000":"21","fffd":"21"},"0004":{"0000":"18","fffd":"21"},"0005":{"0000":"20","0001":"20","0002":"21","0003":"10","0004":"18","fffd":"21"},"0006":{"4000":"10","4001":"21","4002":"21","4003":"30","0000":"10","fffd":"21"},"0007":{"0000":"30","0010":"30","fffd":"21"},"0019":{}}}},"DeviceType":"FFD","HW Version":34,"Last Cmds":[],"LogicalType":"Router","Manufacturer":"128b","Manufacturer Name":"NodOn","NbEp":"2","PowerSource":"Main","ReadAttributes":{"Ep":{"01":{"0000":{"TimeStamp":1703052984,"iSQN":{"4000":"12","8000":"12","0000":"0b","0001":"0b","0002":"0b","0003":"0c","0004":"0c","0005":"0c","0006":"0d","0007":"0d","0008":"0d","0009":"0e","000a":"0e","000b":"0e","000c":"0f","000d":"0f","000e":"0f","0010":"10","0011":"10","0012":"10","0013":"11","0014":"11","0015":"11","fffd":"12","fffe":"13","ffdf":"13","ffe0":"13","ffe1":"14","ffe2":"14","ffe4":"14"},"Attributes":{"4000":"86","8000":"86","0004":"00","0005":"00","0000":"00","0001":"00","0002":"00","0003":"00","0006":"00","0007":"00","0008":"86","0009":"86","000a":"86","000c":"86","000d":"86","0010":"86","0011":"86","0013":"86","0014":"00","0015":"86","fffd":"00","fffe":"86","ffdf":"86","ffe1":"86","ffe2":"86"},"ZigateRequest":{}},"0019":{"TimeStamp":1703052961,"iSQN":{"0000":"03","0001":"03","0002":"03","0003":"04","0004":"04","0005":"04","0006":"05","0007":"05","0008":"05","0009":"06","000a":"06","fffd":"06","fffe":"07"},"Attributes":{"0000":"86","0001":"86","0003":"86","0004":"86","0006":"86","0007":"86","0009":"86","000a":"86","fffe":"86"},"ZigateRequest":{}},"0006":{"TimeStamp":1703107169,"iSQN":{"4000":"08","4001":"08","4002":"09","4003":"09","fffd":"09","fffe":"0a","0000":"3e"},"Attributes":{"4000":"00","4001":"00","4002":"00","4003":"00","fffd":"00","fffe":"86","0000":"00"},"ZigateRequest":{}},"0007":{"TimeStamp":1703107211,"iSQN":{},"Attributes":{"0000":"00","0010":"00"},"ZigateRequest":{}},"0003":{"TimeStamp":1703107216,"iSQN":{},"Attributes":{"0000":"00"},"ZigateRequest":{}}},"f2":{"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"ReceiveOnIdle":"On","Stack Version":103,"Stamp":{"time":1703107216.9304013,"Time":"2023-12-20 22:20:16","MsgType":"8102","LastSeen":1703107216},"ZCL Version":8,"Health":"Live","Capability":["Full-Function Device","Main Powered","Receiver during Idle","Standard security","NwkAddr should be allocated"],"ZDPSQN":"2a","ZCL-IN-SQN":{"1000":"01","0006":"4e","0003":"51","fc57":"1d","0007":"4f","0019":"47"},"RollingLQI":[100,100,104,104,100,104,100,96,80,100,104],"_rawNodeDescriptor":"128b01f401f42c00008e524001","Max Buffer Size":"52","Max Rx":"01f4","Max Tx":"01f4","macapa":"8e","bitfield":"4001","server_mask":"2c00","descriptor_capability":"00","Epv2":{"01":{"ProfileID":"0104","ZDeviceID":"0100","ClusterIn":{"1000":{},"0000":{},"0003":{},"0004":{},"0005":{},"0006":{},"0007":{},"fc57":{}},"ClusterOut":{"0003":{},"0006":{},"0019":{}}},"f2":{"ProfileID":"a1e0","ZDeviceID":"0066","ClusterIn":{"0021":{}},"ClusterOut":{"0021":{}}}},"ZCLSQN":"3e","ZDeviceVersion":"0001","ConfigSource":"8043","WriteAttributes":{"Ep":{"01":{"1000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0003":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0004":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0005":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0007":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"fc57":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0019":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}},"f2":{"0021":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"PairingInProgress":false,"PairingTime":1703052953.08528,"Bind":{"01":{"1000":{"Target":"0000","Stamp":1703052956,"Phase":"binded","Status":"00","i_sqn":"0a"},"0000":{"Target":"0000","Stamp":1703052953,"Phase":"binded","Status":"00","i_sqn":"04"},"0003":{"Target":"0000","Stamp":1703052953,"Phase":"binded","Status":"00","i_sqn":"05"},"0004":{"Target":"0000","Stamp":1703052954,"Phase":"binded","Status":"00","i_sqn":"06"},"0005":{"Target":"0000","Stamp":1703052954,"Phase":"binded","Status":"00","i_sqn":"07"},"0006":{"Target":"0000","Stamp":1703052955,"Phase":"binded","Status":"00","i_sqn":"08"},"0007":{"Target":"0000","Stamp":1703052955,"Phase":"binded","Status":"00","i_sqn":"09"},"fc57":{"Target":"0000","Stamp":1703052956,"Phase":"binded","Status":"00","i_sqn":"0b"}},"f2":{"0021":{"Target":"0000","Stamp":1703052957,"Phase":"binded","Status":"82","i_sqn":"0c"}}},"BindingTable":{"SQN":0,"Status":"Success","TimeStamp":1703052977.1704388,"BindingTableSize":9,"Devices":[{"003c84fffed45305":{"sourceEp":"01","Cluster":"0006","targetIEEE":"003c84fffed45305","targetNickName":null,"targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0000","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0003","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0006","targetIEEE":"003c84fffed45305","targetNickName":null,"targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0000","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0003","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0004","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0005","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0006","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0004","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0005","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0006","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0004","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0005","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0006","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0004","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0005","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0006","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0007","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"1000","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"fc57","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0007","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"1000","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"fc57","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0007","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"1000","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"fc57","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0007","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"1000","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"fc57","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0007","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"1000","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"fc57","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0007","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"1000","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"fc57","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0007","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"1000","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"fc57","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"0007","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"1000","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"003c84fffed45305":{"sourceEp":"01","Cluster":"fc57","targetIEEE":"e0798dfffec10aec","targetNickName":"Zigbee Coordinator","targetEp":"01"}}]},"ConfigureReporting":{"Ep":{"01":{"0006":{"TimeStamp":1703052953.2113943,"iSQN":{"0000":"02"},"Attributes":{"0000":"00"},"ZigateRequest":{}}}}},"CertifiedDevice":false,"SWBUILD_1":"2020","ReadConfigureReporting":{"Ep":{"01":{"0006":{"0000":{"TimeStamp":1703052974.9948297,"Status":"00","DataType":"10","MinInterval":"0001","MaxInterval":"012c"}}}},"TimeStamp":1703052974.9948063},"Param":{},"CheckParam":false,"Neighbours":[{"SQN":0,"Status":"","TimeStamp":1703053161,"Time":1703053161,"Devices":[{"0000":{"_relationshp":"Parent","_devicetype":"Coordinator","_depth":0,"_lnkqty":74,"_rxonwhenidl":"Rx-On","_IEEE":"e0798dfffec10aec","_permitjnt":"??"}}]},{"SQN":0,"Status":"","TimeStamp":1703103827,"Time":1703103827,"Devices":[{"0000":{"_relationshp":"Parent","_devicetype":"Coordinator","_depth":0,"_lnkqty":84,"_rxonwhenidl":"Rx-On","_IEEE":"e0798dfffec10aec","_permitjnt":"??"}}]}],"RoutingTable":[{"SQN":0,"Status":"Success","TimeStamp":1703053161,"Time":1703053161,"RoutingTableTableSize":16,"Devices":[{"0000":{"Status":"Active (0)","MemoryConstrained":1,"ManyToOne":1,"RouteRecordRequired":0,"NextHopNwkId":"0000"}},{"0000":{"Status":"Active (0)","MemoryConstrained":1,"ManyToOne":1,"RouteRecordRequired":0,"NextHopNwkId":"0000"}}]},{"SQN":0,"Status":"Success","TimeStamp":1703103827,"Time":1703103827,"RoutingTableTableSize":16,"Devices":[{"0000":{"Status":"Active (0)","MemoryConstrained":1,"ManyToOne":1,"RouteRecordRequired":0,"NextHopNwkId":"0000"}},{"0000":{"Status":"Active (0)","MemoryConstrained":1,"ManyToOne":1,"RouteRecordRequired":0,"NextHopNwkId":"0000"}}]}],"NeighbourTableSize":1,"MapLQI":{"0000":101},"OTAClient":{"ManufacturerCode":"128b","ImageType":"000a","CurrentImageVersion":"00000216"}}}


[cid:b51ba4cc-3eef-4a31-975f-42054ed5b2c9]
________________________________
De : Pipiche ***@***.***>
Envoyé : mercredi 20 décembre 2023 21:54
À : zigbeefordomoticz/z4d-certified-devices ***@***.***>
Cc : Bastien92 ***@***.***>; Author ***@***.***>
Objet : Re: [zigbeefordomoticz/z4d-certified-devices] [Model Certification] - NodOn SIN4-1-20 (Issue #37)


please provide the Device Information. Without we cannot do much

**Comment by Bastien92** [comment]
The device is working fine on my domoticz configuration.
By the way here is the device SIN-4-1-20:
[cid:a168e335-4c7b-4103-8218-5f0e655ae19b]
________________________________
De : Pipiche ***@***.***>
Envoyé : mercredi 20 décembre 2023 21:54
À : zigbeefordomoticz/z4d-certified-devices ***@***.***>
Cc : Bastien92 ***@***.***>; Author ***@***.***>
Objet : Re: [zigbeefordomoticz/z4d-certified-devices] [Model Certification] - NodOn SIN4-1-20 (Issue #37)


please provide the Device Information. Without we cannot do much

**Comment by pipiche38** [comment]
Should be fix with [3.166]
