### ISSUE TITLE
[Model Certification] - SUNRICHER - Dimmer 2 wires - SR-ZG9040A

### ISSUE THREAD

**Issue by laffreuxjr** [zigbeefordomoticz/z4d-certified-devices#40]
1. https://www.sunricher.com/zigbee-series/zigbee-phase-dimmer.html
    * SR-ZG9040A
    * SUNRICHER
    * [URL on a web site](https://www.sunricher.com/zigbee-series/zigbee-phase-dimmer.html)

[export.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13800971/export.json)

**Comment by pipiche38** [comment]
Is the device behaving correctly ?

**Comment by laffreuxjr** [comment]
Oui, il fonctionne normalement.

@+
Régis

De : Pipiche ***@***.***>
Envoyé : dimanche 31 décembre 2023 12:50
À : zigbeefordomoticz/z4d-certified-devices ***@***.***>
Cc : laffreuxjr ***@***.***>; Author ***@***.***>
Objet : Re: [zigbeefordomoticz/z4d-certified-devices] [Model Certification] - SUNRICHER - Dimmer 2 wires - SR-ZG9040A (Issue #40)


Is the device behaving correctly ?

**Comment by pipiche38** [comment]
Should be ok with [3.172] Certified Db version

**Comment by laffreuxjr** [comment]
Bonjour,

Depuis que « HK-SL-DIM-A » est passé sur « optimisé », sur l’un de mes deux sites, j’ai ce message qui apparait dans les « log » :
2024-01-05 14:40:38.093 Status: Clef_ZigBee: ------ We have detected a miss configuration reports for device c341 on ep 01 and cluster 0b04
2024-01-05 14:40:38.099 Status: Clef_ZigBee: - Attribut 0505 request to force a Configure Reporting due to field MinInterval '0001' != '0258'
Pourriez-vous m’en dire plus ?
Merci de votre réponse et bonne journée.

@+
Régis

De : Pipiche ***@***.***>
Envoyé : dimanche 31 décembre 2023 13:17
À : zigbeefordomoticz/z4d-certified-devices ***@***.***>
Cc : laffreuxjr ***@***.***>; Author ***@***.***>
Objet : Re: [zigbeefordomoticz/z4d-certified-devices] [Model Certification] - SUNRICHER - Dimmer 2 wires - SR-ZG9040A (Issue #40)


Closed #40<https://github.com/zigbeefordomoticz/z4d-certified-devices/issues/40> as completed.

**Comment by pipiche38** [comment]
to be tested with [3.179]
