### ISSUE TITLE
[Model Certification] - 

### ISSUE THREAD

**Issue by vjdewit** [zigbeefordomoticz/z4d-certified-devices#42]
1. Please do provide device information such as Brand and Model name.

TRÅDFRI Led-lamp E27 1055 lumen

2. Provide the URL where you have purchase the device

https://www.ikea.com/nl/nl/p/tradfri-led-lamp-e27-1055-lumen-smart-draadloos-dimbaar-wit-spectrum-globe-60545673/

3. Document as much what works, what doesn't work, what do you miss, what do you need

Device is not optimized

This will create an export.json file that you can save.

[export_TRÅDFRI_Led-lamp_E27_1055_lumen.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13828300/export_TRADFRI_Led-lamp_E27_1055_lumen.json)

**Comment by pipiche38** [comment]
should be fixed with [3.175]
