### ISSUE TITLE
[Model Certification] - IKEA TRÅDFRI Led-lamp E14 470 lumen

### ISSUE THREAD

**Issue by vjdewit** [zigbeefordomoticz/z4d-certified-devices#43]
1. Please do provide device information such as Brand and Model name.

IKEA TRÅDFRI Led-lamp E14 470 lumen

2. Provide the URL where you have purchase the device
  
https://www.ikea.com/nl/nl/p/tradfri-led-lamp-e14-470-lumen-smart-draadloos-dimbaar-wit-spectrum-globe-50486787/

3. Document as much what works, what doesn't work, what do you miss, what do you need

It is not optimized.

[TRADFRIbulbE14WSglobeopal470lm.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13859647/TRADFRIbulbE14WSglobeopal470lm.json)

**Comment by pipiche38** [comment]
[3.181]
