### ISSUE TITLE
Zigbee Temperature & Humidity sensor

### ISSUE THREAD

**Issue by Rylfas** [zigbeefordomoticz/z4d-certified-devices#45]
1. Please do provide device information such as Brand and Model name.
Zigbee Temperature & Humidity sensor

1. Provide the URL where you have purchase the device
https://nl.aliexpress.com/item/1005004594112721.html?spm=a2g0o.order_list.order_list_main.79.7d0179d2GQg1tV&gatewayAdapt=glo2nld**

    * Product Name: TS0601-temphumi
    * Brand: Tuya
    * URL on a web site: See above
    * What do you expect: Showing temperature and humidity with 2 digits

1. Document as much what works, what doesn't work, what do you miss, what do you need
The sensor is working: temperature is showing OK but humidity is only 1 digit. Not 47% but showing 4%
[export.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13928322/export.json)

1. Got to the Tools Menu
1. Select Plugin Raw Devices (json)
1. Export

This will create an export.json file that you can save.

# Donations and Sponsorship

We warmly invite Manufacturers and sellers to contribute by sending us samples of their devices for integration. Your support in this regard is greatly appreciated as it enables us to expand our compatibility and offer a more comprehensive solution.

We extend our heartfelt gratitude to our generous donors whose contributions enable us to acquire additional equipment for rigorous testing and seamless integration. With your support, we can further enhance the plugin's capabilities and deliver an even more powerful and versatile experience for our users.

Donate via PayPal https://paypal.me/pipiche

**Comment by pipiche38** [comment]
I guess, Temperature is correctly reported, but Humidity value is divided by 10 ?

**Comment by pipiche38** [comment]
Should be ok with [3.187]

**Comment by pipiche38** [comment]
Did few correction, so 3.188 is needed
You need to remove the device from Domoticz and Plugin and then re-pair (when the [3.188] is loaded and running )

**Comment by Rylfas** [comment]
Removed the device, installed 3.188 and did a re-pair. Initial all looked good but after receiving data only 1 digit humidity value showed up (see pictures)
![Temp+hum1](https://github.com/zigbeefordomoticz/z4d-certified-devices/assets/156525677/0076dc50-df4b-44f4-828a-c423af234777)
![Temp+hum2](https://github.com/zigbeefordomoticz/z4d-certified-devices/assets/156525677/aa9b0083-a38b-4ad2-9364-731b939f981d)

**Comment by pipiche38** [comment]
Can you provide once more an export.json ( plugin devices raw)

**Comment by Rylfas** [comment]
Thank you for all your efforts. Enclosed the export.json file
[export(1).json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13931476/export.1.json)

**Comment by pipiche38** [comment]
In fact I'm sorry, but I have been confused with the 2 Temp+Humi devices you have
One is a TS0601 and the other one is a TS0201 whcih was also reporting bad humidity and should be corrected now

My apologize for that.

Now if you can get an up^date and have [3.190] running, do the same remove the existing widgets to get the device removed, and the redo the pairing

**Comment by Rylfas** [comment]
Sorry about the confusion. After installing 3.190 these are the results
![Temp+Humi TSO201 and TS0601](https://github.com/zigbeefordomoticz/z4d-certified-devices/assets/156525677/8ecea5d6-9d67-4906-848b-fc6df35cb5ff)
[export(1).json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13932779/export.1.json)

**Comment by Rylfas** [comment]
Problem solved. Thank you for all your efforts!

![Temp+humi](https://github.com/zigbeefordomoticz/z4d-certified-devices/assets/156525677/57cc6b34-287c-41d2-ad7a-a35c179a3e4d)
