### ISSUE TITLE
[Model Certification] - EOTEC SmartThings Zigbee Water Sensor Smart Water Detector

### ISSUE THREAD

**Issue by Doudy** [zigbeefordomoticz/z4d-certified-devices#46]
1. Please do provide device information such as Brand and Model name.
1. Provide the URL where you have purchase the device
    * Product Name
    * Brand
    * URL on a web site
    * What do you expect

1. Document as much what works, what doesn't work, what do you miss, what do you need

1. Got to the Tools Menu
1. Select Plugin Raw Devices (json)
1. Export

This will create an export.json file that you can save.

# Donations and Sponsorship

We warmly invite Manufacturers and sellers to contribute by sending us samples of their devices for integration. Your support in this regard is greatly appreciated as it enables us to expand our compatibility and offer a more comprehensive solution.

We extend our heartfelt gratitude to our generous donors whose contributions enable us to acquire additional equipment for rigorous testing and seamless integration. With your support, we can further enhance the plugin's capabilities and deliver an even more powerful and versatile experience for our users.

Donate via PayPal https://paypal.me/pipiche

**Comment by Doudy** [comment]
Hello,
1. AEOTEC SmartThings Zigbee Water Sensor Smart Water Detector Reliable Alarm for Water Leakage Water Alarm
2. https://www.amazon.de/-/en/gp/product/B08RGD1W4W/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
Product details
Batteries ‏ : ‎ 1 CR2 batteries required. (included)
Product Dimensions ‏ : ‎ 5.9 x 2 x 4.2 cm; 110 Grams
Date First Available ‏ : ‎ 28 Dec. 2020
Manufacturer ‏ : ‎ Smart Things
ASIN ‏ : ‎ B08RGD1W4W
Item model number ‏ : ‎ MED_WLS600
Country of origin ‏ : ‎ China
Guaranteed software updates until ‏ : ‎ unknown
Best Sellers Rank: 111,293 in DIY & Tools ([See Top 100 in DIY & Tools](https://www.amazon.de/-/en/gp/bestsellers/diy/ref=pd_zg_ts_diy))
3. The object is not optimized for the plugin
4/5/6
[errors.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/14049074/errors.json)
.  Json
{"PluginInfos":{"HardwareID":29,"HomeFolder":"/home/pi/domoticz/plugins/Domoticz-Zigbee/","StartupFolder":"/home/pi/domoticz/","UserDataFolder":"/home/pi/domoticz/","WebRoot":"","Database":"/home/pi/domoticz/domoticz.db","Language":"fr","Version":"7.1","Author":"pipiche38","Name":"ZigBeeForDomoticZ","Address":"0.0.0.0","Port":"9999","SerialPort":"/dev/ttyUSB11","Key":"Zigate","Mode1":"ZigpyZNP","Mode2":"USB","Mode3":"False","Mode4":"9440","Mode6":"0","DomoticzVersion":"2023.2","DomoticzHash":"19efd039c","DomoticzBuildTime":"2023-07-21 17:23:44","PluginBranch":"stable7","PluginVersion":"7.1.007","CertifiedDbVersion":"3.195","TimeStamp":1706171439,"available":"7.1.007","available-firmMajor":0,"available-firmMinor":0,"FirmwareVersion":"Z-Stack 3.30+ (build 20210708)","FirmwareUpdate":false,"PluginUpdate":false,"LogLevel":7,"Zigpy":true,"CoordinatorModel":"CC1352/CC2652, Z-Stack 3.30+ (znp)","CoordinatorFirmwareVersion":"Z-Stack 3.30+ (build 20210708)","DisplayFirmwareVersion":"Znp - Z-Stack 3.30+ (build 20210708)","CoordinatorIEEE":"00124b0024c0c47e","NetworkSize":"Total: 1 | Routers: 1 | End Devices: 0","NetworkDevices":{}},"Analytics":1,"Device":{"Version":"3","ZDeviceName":"ZB-Fuite-WC","Status":"UNKNOW","SQN":"35","Ep":{"01":{"0000":{"0004":"Samjin","0005":"water"}}},"Heartbeat":"578","RIA":"6","LQI":15,"Battery":{},"Model":"water","ForceAckCommands":[],"MacCapa":"80","IEEE":"286d970001124d7e","Type":{},"ProfileID":{},"ZDeviceID":{},"App Version":"","Attributes List":{},"DeviceType":"RFD","HW Version":"","Last Cmds":[],"LogicalType":"End Device","Manufacturer":"","Manufacturer Name":"Samjin","NbEp":"1","PowerSource":"","ReadAttributes":{"Ep":{"01":{"0000":{"TimeStamp":1706168526,"iSQN":{"0004":"02","0005":"02"},"Attributes":{"0004":"00","0005":"00"},"ZigateRequest":{}}}}},"ReceiveOnIdle":"","Stack Version":"","Stamp":{"time":1706168830.1443102,"Time":"2024-01-25 08:47:10","MsgType":"8011","LastSeen":1706168830},"ZCL Version":"","Health":"Live","Capability":["Reduced-Function Device","Standard security","NwkAddr should be allocated"],"ZDPSQN":"02","ZCLSQN":"02","Epv2":{},"RollingLQI":[36,36,36,15,15],"WriteAttributes":{"Ep":{"01":{"0500":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"PairingInProgress":true,"ConsistencyCheck":"Bad Pairing","ZCL-IN-SQN":{"0019":"35"},"OTAClient":{"ManufacturerCode":"1241","ImageType":"0030","CurrentImageVersion":"00000011"},"Param":{},"CheckParam":true}}

**Comment by pipiche38** [comment]
I'm lacking some essential information. This more-less what the plugin is telling.
In fact when pairing a device which is unknow, the plugin start to do a discovery of what are the functionality provided by this device, and here we are not getting any answers.


Can you try the following

(1) restart the plugin
(2) enable some debug parameters as show here after

<img width="1365" alt="Screenshot 2024-01-27 at 09 39 47" src="https://github.com/zigbeefordomoticz/z4d-certified-devices/assets/8291674/df089ac8-ce99-4076-a5da-fbbed292d7b0">


(3) do the pairing

and then. drop here the PluginZigbee_xx.log file that you can find in the Logs/ folder
