### ISSUE TITLE
[Model Certification] - Ikea PARASOLL DoorWindow Sensor

### ISSUE THREAD

**Issue by pipiche38** [zigbeefordomoticz/z4d-certified-devices#47]
`{"PluginInfos":{"HardwareID":15,"HomeFolder":"/home/root/domoticz/plugins/Domoticz-Zigbee/","StartupFolder":"/home/root/domoticz/","UserDataFolder":"/home/root/domoticz/","WebRoot":"","Database":"/home/root/domoticz/domoticz.db","Language":"nl","Version":"7.1","Author":"pipiche38","Name":"Zigbee","Address":"0.0.0.0","Port":"9999","SerialPort":"/dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0","Key":"Zigate","Mode1":"ZigpyZNP","Mode2":"USB","Mode3":"False","Mode4":"9440","Mode6":"2","DomoticzVersion":"2024.2","DomoticzHash":"73d655383","DomoticzBuildTime":"2024-01-15 16:48:07","PluginBranch":"stable7","PluginVersion":"7.1.007","CertifiedDbVersion":"3.191","TimeStamp":1705758188,"available":"7.1.007","available-firmMajor":0,"available-firmMinor":0,"FirmwareVersion":"Z-Stack 3.30+ (build 20220219)","FirmwareUpdate":false,"PluginUpdate":false,"LogLevel":7,"Zigpy":true,"CoordinatorModel":"CC1352/CC2652, Z-Stack 3.30+ (znp)","CoordinatorFirmwareVersion":"Z-Stack 3.30+ (build 20220219)","DisplayFirmwareVersion":"Znp - Z-Stack 3.30+ (build 20220219)","CoordinatorIEEE":"00124b0025e14d39","NetworkSize":"Total: 23 | Routers: 11 | End Devices: 12","NetworkDevices":{"1002":{"TZ3000typdpbpg":["TS011F-plug"]},"1141":{"TZE2003towulqd":["TS0601-motion"]},"1286":{"SONOFF":["ZBMINIL2"]},"117c":{"IKEA of Sweden":["TRADFRI transformer 10W","TRADFRI remote control","STARKVIND Air purifier","PARASOLL DoorWindow Sensor"]}}},"Analytics":1,"Device":{"Version":"3","ZDeviceName":"Achterdeur","Status":"inDB","SQN":"28","Ep":{"01":{"1000":{},"0000":{"0004":"IKEA of Sweden","0005":"PARASOLL Door/Window Sensor"},"0001":{},"0003":{},"0020":{},"0b05":{},"fc7c":{},"fc81":{},"0004":{},"0006":{},"0019":{},"ClusterType":{"8594":"Voltage","8595":"Switch"}},"02":{"0000":{"0004":"IKEA of Sweden","0005":"PARASOLL Door/Window Sensor"},"0003":{},"0500":{"0010":"00124b0025e14d39","0000":"01","0001":"0015","0002":"alarm1: 0, alarm2: 0, tamper: 0, battery: 0, Support Reporting: 0, restore Reporting: 0, trouble: 0, acmain: 0, test: 0, battdef: 0"},"ClusterType":{"8596":"Door"}}},"Heartbeat":"349","RIA":"4","LQI":47,"Battery":{},"Model":"PARASOLL DoorWindow Sensor","ForceAckCommands":[],"MacCapa":"80","IEEE":"142d41fffe58431e","Type":"Voltage/Switch/Door","ProfileID":"0104","ZDeviceID":"0402","App Version":"","Attributes List":{},"DeviceType":"RFD","HW Version":"","Last Cmds":[],"LogicalType":"End Device","Manufacturer":"117c","Manufacturer Name":"IKEA of Sweden","NbEp":"2","PowerSource":"Battery","ReadAttributes":{"Ep":{"01":{"0000":{"TimeStamp":1705756657,"iSQN":{"4000":"25","8000":"25","0000":"1e","0001":"1e","0002":"1e","0003":"1f","0004":"1f","0005":"1f","0006":"20","0007":"20","0008":"20","0009":"21","000a":"21","000b":"21","000c":"22","000d":"22","000e":"22","0010":"23","0011":"23","0012":"23","0013":"24","0014":"24","0015":"24","fffd":"25","fffe":"26","ffdf":"26","ffe0":"26","ffe1":"27","ffe2":"27","ffe4":"27"},"Attributes":{"0004":"00","0005":"00"},"ZigateRequest":{}},"0001":{"TimeStamp":1705756443,"iSQN":{"0000":"0d","0001":"0d","0010":"0d","0011":"0e","0012":"0e","0013":"0e","0020":"0f","0021":"0f","0030":"0f","0031":"10","0032":"10","0033":"10","0034":"11","0035":"11","0036":"11","0037":"12","0038":"12","0039":"12","003a":"13","003b":"13","003c":"13","003d":"14","003e":"14","fffd":"14","fffe":"15"},"Attributes":{},"ZigateRequest":{}},"0019":{"TimeStamp":1705756443,"iSQN":{"0000":"16","0001":"16","0002":"16","0003":"17","0004":"17","0005":"17","0006":"18","0007":"18","0008":"18","0009":"19","000a":"19","fffd":"19","fffe":"1a"},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":1705756443,"iSQN":{"4000":"1b","4001":"1b","4002":"1c","4003":"1c","0000":"1b","fffd":"1c","fffe":"1d"},"Attributes":{},"ZigateRequest":{}}},"02":{"0000":{"TimeStamp":1705756443,"iSQN":{"4000":"2f","8000":"2f","0000":"28","0001":"28","0002":"28","0003":"29","0004":"29","0005":"29","0006":"2a","0007":"2a","0008":"2a","0009":"2b","000a":"2b","000b":"2b","000c":"2c","000d":"2c","000e":"2c","0010":"2d","0011":"2d","0012":"2d","0013":"2e","0014":"2e","0015":"2e","fffd":"2f","fffe":"30","ffdf":"30","ffe0":"30","ffe1":"31","ffe2":"31","ffe4":"31"},"Attributes":{},"ZigateRequest":{}},"0500":{"TimeStamp":1705756439,"iSQN":{},"Attributes":{"0010":"00","0000":"00","0001":"00","0002":"00"},"ZigateRequest":{}}}}},"ReceiveOnIdle":"Off","Stack Version":"","Stamp":{"time":1705757079.7624273,"Time":"2024-01-20 14:24:39","MsgType":"8011","LastSeen":1705757079},"ZCL Version":"","Health":"Live","Capability":["Reduced-Function Device","Standard security","NwkAddr should be allocated"],"ZDPSQN":"10","rawNodeDescriptor":"117c005200522c000080524002","Max Buffer Size":"52","Max Rx":"0052","Max Tx":"0052","macapa":"80","bitfield":"4002","servermask":"2c00","descriptor_capability":"00","ZCLSQN":"40","Epv2":{"01":{"ProfileID":"0104","ZDeviceID":"0103","ClusterIn":{"1000":{},"0000":{},"0001":{},"0003":{},"0020":{},"0b05":{},"fc7c":{},"fc81":{}},"ClusterOut":{"1000":{},"0003":{},"0004":{},"0006":{},"0019":{}}},"02":{"ProfileID":"0104","ZDeviceID":"0402","ClusterIn":{"0000":{},"0003":{},"0500":{}},"ClusterOut":{"0003":{}}}},"PairingInProgress":false,"ZCL-IN-SQN":{"0500":"26","0000":"38","0003":"05","0004":"40","0019":"28"},"RollingLQI":[58,58,58,54,69,61,58,61,58,47,47],"WriteAttributes":{"Ep":{"02":{"0500":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0003":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}},"01":{"1000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0001":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0003":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0020":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0b05":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"fc7c":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"fc81":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0004":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0019":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"ZDeviceVersion":"0001","ConfigSource":"8043","IAS":{"Auto-Enrollment":{"Status":"Enrolled","Ep":{"02":{"Status":"Enrolled","ZoneId":"00"}}},"02":{"EnrolledStatus":1,"ZoneType":21,"ZoneTypeName":"contact","ZoneStatus":{"alarm1":1,"alarm2":0,"tamper":0,"battery":0,"Support Reporting":0,"Restore Reporting":0,"trouble":0,"acmain":0,"test":0,"battdef":0,"doorbell":0,"GlobalInfos":"1;0;0;0;0;0;0;0;0;0;0","TimeStamp":1705756439}}},"Bind":{"02":{"0500":{"Target":"0000","Stamp":1705756440,"Phase":"binded","Status":"00","i_sqn":"04"},"0000":{"Target":"0000","Stamp":1705756443,"Phase":"requested","Status":"","i_sqn":"0d"},"0003":{"Target":"0000","Stamp":1705756443,"Phase":"requested","Status":"","i_sqn":"0e"}},"01":{"1000":{"Target":"0000","Stamp":1705756443,"Phase":"requested","Status":"","i_sqn":"0a"},"0000":{"Target":"0000","Stamp":1705756443,"Phase":"requested","Status":"","i_sqn":"05"},"0001":{"Target":"0000","Stamp":1705756443,"Phase":"requested","Status":"","i_sqn":"06"},"0003":{"Target":"0000","Stamp":1705756443,"Phase":"requested","Status":"","i_sqn":"07"},"0020":{"Target":"0000","Stamp":1705756443,"Phase":"requested","Status":"","i_sqn":"08"},"0b05":{"Target":"0000","Stamp":1705756443,"Phase":"requested","Status":"","i_sqn":"09"},"fc7c":{"Target":"0000","Stamp":1705756443,"Phase":"requested","Status":"","i_sqn":"0b"},"fc81":{"Target":"0000","Stamp":1705756443,"Phase":"requested","Status":"","i_sqn":"0c"}}},"IASBattery":100,"PairingTime":1705756443.080846,"BindingTable":[{"Devices":[],"SQN":0,"Status":"","TimeStamp":1705756443,"Time":1705756443}],"ConfigureReporting":{"Ep":{"01":{"0001":{"TimeStamp":1705756443.107821,"iSQN":{"0000":"0a","0020":"0a","0021":"0a"},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":1705756443.1156592,"iSQN":{"0000":"0b"},"Attributes":{},"ZigateRequest":{}}},"02":{"0500":{"TimeStamp":1705756443.1213439,"iSQN":{"0000":"0c","0001":"0c","0002":"0c"},"Attributes":{},"ZigateRequest":{}}}}},"CertifiedDevice":false,"OTAClient":{"ManufacturerCode":"117c","ImageType":"3277","CurrentImageVersion":"01000019"},"Param":{},"CheckParam":false}}`

**Comment by rhuijben** [comment]
The sensors work.
Somehow they report both a sensor (open/closed) and a switch (off/on) in Domoticz. Don't think this duplication is necessary for Domoticz, but could be usefull for other cases.

**Comment by rhuijben** [comment]
The voltage sensor just reports 0 V. So not sure what to is supposed to report. There is just a new AAA battery in the sensor. The normal zigbee battery info reports ok.

**Comment by pipiche38** [comment]
The Open/Closed door sensor is what you need to keep.
The device do not report voltage. Just report battery shortage.

**Comment by pipiche38** [comment]
should be fixed with [3.198]
