### ISSUE TITLE
[Model Certification] - XIAOMI Mijia

### ISSUE THREAD

**Issue by MatthieuF44** [zigbeefordomoticz/z4d-certified-devices#48]
1. XIAOMI Mijia
2. [URL on a web site](https://fr.banggood.com/2Pcs-Xiaomi-Mijia-Smart-LCD-Screen-Digital-Thermometer-2-bluetooth-Temperature-Humidity-Sensor-Moisture-Meter-Mijia-App-p-2002173.html?cur_warehouse=CN)
Flashed in zigbee with https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html
4. The object is not optimized for the plugin :  
{
  "PluginInfos": {
    "HardwareID": 32,
    "HomeFolder": "/home/pi/domoticz/plugins/Domoticz-Zigbee/",
    "StartupFolder": "/home/pi/domoticz/",
    "UserDataFolder": "/home/pi/domoticz/",
    "WebRoot": "",
    "Database": "/home/pi/domoticz/domoticz.db",
    "Language": "fr",
    "Version": "6.3",
    "Author": "pipiche38",
    "Name": "Zigbee",
    "Address": "0.0.0.0",
    "Port": "9999",
    "SerialPort": "/dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0",
    "Key": "Zigate",
    "Mode1": "ZigpyZNP",
    "Mode2": "USB",
    "Mode3": "False",
    "Mode4": "9440",
    "Mode6": "2",
    "DomoticzVersion": "2024.2",
    "DomoticzHash": "73d655383",
    "DomoticzBuildTime": "2024-01-15 16:48:07",
    "PluginBranch": "stable6",
    "PluginVersion": "6.3.015",
    "TimeStamp": 1706455166,
    "available": 0,
    "available-firmMajor": 0,
    "available-firmMinor": 0,
    "FirmwareVersion": "Z-Stack 3.30+ (build 20210708)",
    "FirmwareUpdate": false,
    "PluginUpdate": false,
    "LogLevel": 7,
    "Zigpy": true,
    "CoordinatorModel": "CC1352/CC2652, Z-Stack 3.30+ (znp)",
    "CoordinatorFirmwareVersion": "Z-Stack 3.30+ (build 20210708)",
    "DisplayFirmwareVersion": "Znp - Z-Stack 3.30+ (build 20210708)",
    "CoordinatorIEEE": "00124b002a2e8faa",
    "NetworkSize": "Total: 1 | Routers: 1 | End Devices: 0",
    "NetworkDevices": {}
  },
  "Analytics": 1,
  "Device": {
    "Version": "3",
    "ZDeviceName": "",
    "Status": "UNKNOW",
    "SQN": "03",
    "Ep": {
      "01": {
        "0000": {
          "0004": "Xiaomi",
          "0000": "3",
          "0001": "0",
          "0005": "LYWSD03MMC",
          "0007": "3"
        }
      }
    },
    "Heartbeat": "89",
    "RIA": "7",
    "LQI": 96,
    "Battery": {},
    "Model": "LYWSD03MMC",
    "ForceAckCommands": [],
    "MacCapa": "80",
    "IEEE": "a4c138ce1ec2d90f",
    "Type": {},
    "ProfileID": {},
    "ZDeviceID": {},
    "App Version": "0",
    "Attributes List": {},
    "DeviceType": "RFD",
    "HW Version": "",
    "Last Cmds": [],
    "LogicalType": "End Device",
    "Manufacturer": "",
    "Manufacturer Name": "Xiaomi",
    "NbEp": "1",
    "PowerSource": "",
    "ReadAttributes": {
      "Ep": {
        "01": {
          "0000": {
            "TimeStamp": 1706454711,
            "iSQN": {
              "0004": "01",
              "0000": "01",
              "0001": "01",
              "0005": "01",
              "0007": "01",
              "fffe": "01"
            },
            "Attributes": {
              "0004": "00",
              "0000": "00",
              "0001": "00",
              "0005": "00",
              "0007": "00",
              "fffe": "86"
            },
            "ZigateRequest": {}
          }
        }
      }
    },
    "ReceiveOnIdle": "",
    "Stack Version": "",
    "Stamp": {
      "time": 1706454976.8087878,
      "Time": "2024-01-28 16:16:16",
      "MsgType": "  4d",
      "LastSeen": 1706454976
    },
    "ZCL Version": "3",
    "Health": "Live",
    "Capability": [
      "Reduced-Function Device",
      "Standard security",
      "NwkAddr should be allocated"
    ],
    "ZCLSQN": "01",
    "ZDPSQN": "03",
    "RollingLQI": [
      129,
      129,
      129,
      129,
      96,
      96,
      96
    ],
    "WriteAttributes": {
      "Ep": {
        "01": {
          "0000": {
            "TimeStamp": 0,
            "iSQN": {},
            "Attributes": {},
            "ZigateRequest": {}
          }
        }
      }
    },
    "PairingInProgress": true,
    "Epv2": {
      "01": {
        "ClusterIn": {},
        "ClusterOut": {},
        "ProfileID": {},
        "ZDeviceID": {}
      }
    },
    "ConsistencyCheck": "Bad Pairing"
  }
}

**Comment by pipiche38** [comment]
you look to be on a old an. not supported version of the plugin.
Please consider upgrading to stable7

https://zigbeefordomoticz.github.io/wiki/en-eng/Release_7.1.html (requires Python3.8 . If you are on RP you have to move to bullseye as buster doesn't support python3.8)

**Comment by pipiche38** [comment]
Which firmware did you flash ?

**Comment by MatthieuF44** [comment]
This issue is solved by updating the version of plugin.
