### ISSUE TITLE
[Model Certification] - TRADFRIbulbE27WSglobeopal1055lm 

### ISSUE THREAD

**Issue by j-b-n** [zigbeefordomoticz/z4d-certified-devices#49]
I have an old TRADFRIbulbE27WSglobeopal1055lm that works but the GUI report it as a Non-optimized- device. So perhaps not super important to fix but if it is an easy fix it will at least make my current install without non-optimized-devices.

Name: IKEA Trådfri Bulb
URL: https://zigbee.blakadder.com/Ikea_LED2003G10.html

[export.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/14151174/export.json)

**Comment by pipiche38** [comment]
thanks for reporting. Will be fixed in the next certified devices database

**Comment by pipiche38** [comment]
should be fixed with [3.211]
