### ISSUE TITLE
[Model Certification] - Royal Gardineer  ZX7155

### ISSUE THREAD

**Issue by jf67-07** [zigbeefordomoticz/z4d-certified-devices#5]
Hi,

I've a garden valve not optimized.
The model is: Royal Gardineer  ZX7155
It's supposed to be compatible with ELESION, Tuya Smart and Smart Life

I found it here: https://www.pearl.fr/article/ZX7155/valve-darrosage-connectee-pour-passerelle-zigbee-avec-commandes-vocales

French documentations
  * https://www.pearl.fr/support/notices/telecharger/14001
  * https://www.pearl.fr/support/notices/telecharger/14235

The product is seen by my  Zigate+ key, but the widget cannot be created in domoticz: 
`Error: ZigBee: processNotinDBDevices - Creat Domo Device Failed !!! for ae90 status: 8043`

Here is the content of the "not optimized" icon and the raw device export:
[json.zip](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/11990514/json.zip)

Thanks.

**Comment by jf67-07** [comment]
Found a solution with this patch code:
[5.txt](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/11990718/5.txt) 
Can't get the battery level (not sure if it's supposed to work), but I can switch the device On/Off

**Comment by pipiche38** [comment]
This should be fixed on the latest develop branch and z4d-certified-devices 2.73
