### ISSUE TITLE
[Model Certification] - Philips Hue White And Color Ambiance, Iris compatible Bluetooth

### ISSUE THREAD

**Issue by berher1** [zigbeefordomoticz/z4d-certified-devices#50]
1. Please do provide device information such as Brand and Model name.
Brand: Philips
Model: Philips Hue Iris
 
1. Provide the URL where you have purchase the device
    * https://www.amazon.fr/Philips-Lighting-White-Color-Ambiance/dp/B08CXZJWM9/ref=sr_1_4?__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=Z3VO8QH4BWDE&keywords=Philips%2BHue%2BWhite%2BAnd%2BColor%2BAmbiance%2C%2BIris&qid=1707058516&s=lighting&sprefix=philips%2Bhue%2Bwhite%2Band%2Bcolor%2Bambiance%2C%2Biris%2Clighting%2C158&sr=1-4&th=1
    * Iris is working fine but gives errors in logs
   2024-02-04 15:55:25,061 ERROR   : [ZiGateForwarder_9] ReadCluster - Error/unknow 4807/0b Cluster: 0000 Attribute: 0020 Status: 00 DataType: 42 DataSize: 0009 Data: 303a5057524f4e4030
2024-02-04 15:55:35,167 ERROR   : [ZiGateForwarder_9] ReadCluster - Error/unknow 4807/0b Cluster: 0000 Attribute: 0021 Status: 00 DataType: 23 DataSize: 0004 Data: 000004ad

Error is happening multiple time per minutes and never stops.

After a while this breaks my other zigbee devices.

1. Got to the Tools Menu
1. Select Plugin Raw Devices (json)
1. Export

This will create an export.json file t
This will create an export.json file that you can save.

json file is attached.

Let me know if you need any other information.
Many thanks in advance
Best regards,
Bernard.

# Donations and Sponsorship

We warmly invite Manufacturers and sellers to contribute by sending us samples of their devices for integration. Your support in this regard is greatly appreciated as it enables us to expand our compatibility and offer a more comprehensive solution.

We extend our heartfelt gratitude to our generous donors whose contributions enable us to acquire additional equipment for rigorous testing and seamless integration. With your support, we can further enhance the plugin's capabilities and deliver an even more powerful and versatile experience for our users.

Donate via PayPal https://paypal.me/pipiche
[iris_hue_pairing.txt](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/14157258/iris_hue_pairing.txt)
[iris_hue_pairing.txt](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/14157260/iris_hue_pairing.txt)

**Comment by pipiche38** [comment]
should be fixed with [3.211]

**Comment by berher1** [comment]
Error is gone, It's working fine now.
Many thanks!
