### ISSUE TITLE
[Model Certification] - frient Electricity Meter Interface 2, LED (EMIZB-141)

### ISSUE THREAD

**Issue by FanLin-ffms** [zigbeefordomoticz/z4d-certified-devices#52]
1.
    * **Product Name:** Electricity Meter Interface 2, LED (EMIZB-141)
    * **Brand:** frient
    * **URL on a web site:** https://frient.com/products/electricity-meter-interface-2-led

1.
    * **Provide the URL where you have purchase the device:** https://amazon.de

1. * **Finaly copy-paste all information provided in the log:**
[export.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/14403861/export.json)

**Comment by pipiche38** [comment]
Please make sure you are running on latest plugin version 7.1.xxx
Verify that you have the Certifed Db [4.226]

redo the pairing when you are at that level

**Comment by pipiche38** [comment]
please re-open the case if it doesn't work with 4.226
