### ISSUE TITLE
[Tuya Smart Plug Zigbee] - TS011F - no power reading

### ISSUE THREAD

**Issue by jportinga** [zigbeefordomoticz/z4d-certified-devices#53]
1. Please do provide device information such as Brand and Model name.  ELIVCO - Model SPA9
1. Provide the URL where you have purchase the device
    * Product Name  Tuya Smart Plug Zigbee
    * Brand ELIVCO
    * URL on a web site  : https://nl.aliexpress.com/item/1005005665178706.html?spm=a2g0o.order_list.order_list_main.10.50cb79d2IfSAR9&gatewayAdapt=glo2nld
    * What do you expect
    * The plug connects via Zigbee and displays voltage and current. However, it does not measure power usage
[export.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/14431906/export.json)
 

1. Document as much what works, what doesn't work, what do you miss, what do you need

1. Got to the Tools Menu
1. Select Plugin Raw Devices (json)
1. Export

This will create an export.json file that you can save.

# Donations and Sponsorship

We warmly invite Manufacturers and sellers to contribute by sending us samples of their devices for integration. Your support in this regard is greatly appreciated as it enables us to expand our compatibility and offer a more comprehensive solution.

We extend our heartfelt gratitude to our generous donors whose contributions enable us to acquire additional equipment for rigorous testing and seamless integration. With your support, we can further enhance the plugin's capabilities and deliver an even more powerful and versatile experience for our users.

Donate via PayPal https://paypal.me/pipiche

**Comment by pipiche38** [comment]
This plug is supported, as they are no description of what doesn't work we close this issue.

Make sure that you are running the latest version of the Plugin 7.1.009 [4.226] or higher

**Comment by jportinga** [comment]
The discription was..is
The plug connects via Zigbee and displays voltage and current.
 However, it does not measure power usage.

**Comment by pipiche38** [comment]
fix issue in config file: https://github.com/zigbeefordomoticz/z4d-certified-devices/actions/runs/8096411995

**Comment by pipiche38** [comment]
Please test with [4.227] if not working provides plugin log file as well as Liste of Raw Devices

**Comment by jportinga** [comment]
Thank you for the adjustment. After updating the plugin to 4.227 Everything is working fine. 
For your information: In another environment where the plugin was running version 4.224 it also worked.
**But not in versions 4.225 and 6.**
