### ISSUE TITLE
[Model Certification] - Garage door module with opening sensor

### ISSUE THREAD

**Issue by PHIL-IP** [zigbeefordomoticz/z4d-certified-devices#56]
1. Please do provide device information such as Brand and Model name.
   Product name : Door controler
   Model : PJ-ZGD01

2. Provide the URL where you have purchase the device
   https://fr.aliexpress.com/item/1005003635582496.html
    * What do you expect : Integrate  this module in Domoticz with contact + sensor

3. Data from the little orange icon
`{"Filename":"TS0601.json","Configuration":{"_comment":"","_version":"","_blakadder":"","_source":"","Ep":{"01":{"0000":"","0004":"","0005":"","ef00":"","0019":"","000a":"","Type":{}},"f2":{"Type":{}}},"Type":"","ClusterToBind":[],"ConfigureReporting":{},"ReadAttributes":{"0000":["0004","0000","0001","0005","0007","fffe"]},"Param":{},"GroupMembership":{}},"rawInfos":{"Version":"3","ZDeviceName":"Porte Garage","Status":"UNKNOW","SQN":"60","Ep":{"01":{"0000":{"0004":"_TZE204_nklqjk62","0000":3,"0001":74,"0005":"TS0601","0007":1,"fffe":0},"0004":{},"0005":{},"ef00":{},"0019":{},"000a":{}},"f2":{}},"Heartbeat":"224","RIA":"4","LQI":126,"Battery":{},"Model":"TS0601","ForceAckCommands":[],"MacCapa":"8e","IEEE":"a4c1384900532347","Type":{},"ProfileID":"0104","ZDeviceID":"0051","App Version":74,"Attributes List":{},"DeviceType":"FFD","HW Version":"","Last Cmds":[[1353,"02","be94","0100","01010000000000000600040000000100050007fffe"]],"LogicalType":"Router","Manufacturer":"1141","Manufacturer Name":"_TZE204_nklqjk62","NbEp":"2","PowerSource":"Main","ReadAttributes":{"Ep":{"01":{"0000":{"TimeStamp":1710340607,"iSQN":{"0004":1353,"0000":1353,"0001":1353,"0005":1353,"0007":1353,"fffe":1353},"Attributes":{"0004":"00","0000":"00","0001":"00","0005":"00","0007":"00","fffe":"00"},"ZigateRequest":{}}}}},"ReceiveOnIdle":"On","Stack Version":"","Stamp":{"time":1710341712.8372307,"Time":"2024-03-13 15:55:12","MsgType":"8011","LastSeen":1710341712},"ZCL Version":3,"Health":"Live","Capability":["Full-Function Device","Main Powered","Receiver during Idle","Standard security","NwkAddr should be allocated"],"ZDPSQN":"00","RollingLQI":[127,126,126,126,126,126,126,126,126,126,126],"WriteAttributes":{"Ep":{"01":{"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"Epv2":{"01":{"ProfileID":"0104","ZDeviceID":"0051","ClusterIn":{"0004":{},"0005":{},"ef00":{},"0000":{}},"ClusterOut":{"0019":{},"000a":{}}}},"ReqEpv2":{"01":1710340607.9169245},"ZDeviceVersion":"0001","ConfigSource":"8043","PairingInProgress":true,"_rawNodeDescriptor":"1141004200422a00008e424001","Max Buffer Size":"42","Max Rx":"0042","Max Tx":"0042","macapa":"8e","bitfield":"4001","server_mask":"2a00","descriptor_capability":"00","Tuya":{"TUYA_MCU_VERSION_RSP":"40","Valve 0x05":"00000e10","Valve 0x0b":"00"},"SQN_000a":"52","Param":{},"CheckParam":true}}`

1. Document as much what works, what doesn't work, what do you miss, what do you need
 The plugin see the module but nothing about some contact or sensor
[export.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/14589641/export.json)

Hope that you have all things you need.

Thanks in advance

**Comment by pipiche38** [comment]
Update blakadder https://github.com/blakadder/zigbee/pull/1164

**Comment by pipiche38** [comment]
Get up to [4.235]

you can get it by doing `sudo python3 -m pip install -r requirements.txt --upgrade`

and then restart the plugin

after that do the pairing

**Comment by pipiche38** [comment]
Ok. Understood.
Can you update to [4.238]
you can get it by doing sudo python3 -m pip install -r requirements.txt --upgrade

remove all widgets created in Domoticz for this device, make sure that the device do not exist in plugin

then restart

and redo the pairing from scratch
