### ISSUE TITLE
Ikea Tradfri , TRADFRIbulbE27WWclear250lm - not optimized

### ISSUE THREAD

**Issue by marktn** [zigbeefordomoticz/z4d-certified-devices#57]
Ikea Tradfri , TRADFRIbulbE27WWclear250lm
https://www.ikea.com/nl/nl/p/tradfri-led-lamp-e27-250-lumen-smart-draadloos-dimbaar-warm-wit-globe-40439254/

Working fine, no problems.

**Comment by pipiche38** [comment]
[export(1) (2).json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/14593442/export.1.2.json)
