### ISSUE TITLE
Hue philips LWA004 E27 - not optimized 

### ISSUE THREAD

**Issue by marktn** [zigbeefordomoticz/z4d-certified-devices#59]
Hue philips LWA004  - not optimized 
https://www.philips-hue.com/nl-nl/p/hue-white-ambiance-filament-a60---e27-slimme-lamp/8719514301429

Working fine, no problems.

**Comment by pipiche38** [comment]
[export(1) (2).json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/14593423/export.1.2.json)
