### ISSUE TITLE
[Model Certification] - Temp/Humi sensor _TZ3000_zl1kmjqx

### ISSUE THREAD

**Issue by Git-Bruno** [zigbeefordomoticz/z4d-certified-devices#61]
1. Product information
    * Product Name : Tuya Zigequation-Mini Capteur de Température et d'Humidité
    * URL on a web site
[https://fr.aliexpress.com/item/1005005454153400.htm](url)
    * What do you expect
2. Problem description
Device works fine but it appears as not optimezed in the Web UI
3. Export
JSON exported using the non-optimized device function in the Web UI 

[TZ3000_zl1kmjqx.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/14724369/TZ3000_zl1kmjqx.json)

**Comment by pipiche38** [comment]
kindly upgrade to Certified Db [4.244]
remove the existing device from Domoticz and the plugin (remove all related widgets from Dz and the device from plugin)

then restart the plugin and redo the pairing
