### ISSUE TITLE
TRV BAB-1413Pro-E

### ISSUE THREAD

**Issue by Snake40** [zigbeefordomoticz/z4d-certified-devices#65]
URL achat du TRV :

https://fr.aliexpress.com/item/1005006092397271.html?spm=a2g0o.detail.pcDetailBottomMoreOtherSeller.2.2c524662eCqvPh&gps-id=pcDetailBottomMoreOtherSeller&scm=1007.40050.354490.0&scm_id=1007.40050.354490.0&scm-url=1007.40050.354490.0&pvid=c543e937-9c5f-4c54-8b51-2c90ae18918b&_t=gps-id:pcDetailBottomMoreOtherSeller,scm-url:1007.40050.354490.0,pvid:c543e937-9c5f-4c54-8b51-2c90ae18918b,tpp_buckets:668%232846%238115%232000&pdp_npi=4%40dis%21EUR%2115.77%2115.77%21%21%21118.84%21118.84%21%40211b813b17148442512164784e5dfd%2112000035699767142%21rec%21FR%21834690355%21&utparam-url=scene%3ApcDetailBottomMoreOtherSeller%7Cquery_from%3A

Dans zigbeefordomoticz l'objet est déclaré "non optimisé" après une tentative d'appairage :

{"PluginInfos":{"HardwareID":7,"HomeFolder":"/opt/domoticz/userdata/plugins/Domoticz-Zigbee/","StartupFolder":"/opt/domoticz/","UserDataFolder":"/opt/domoticz/userdata/","WebRoot":"","Database":"/opt/domoticz/userdata/domoticz.db","Language":"fr","Version":"7.1","Author":"pipiche38","Name":"Zigbee","Address":"0.0.0.0","Port":"9999","SerialPort":"/dev/ttyACM0","Key":"Zigate","Mode1":"ZigpyEZSP","Mode2":"USB","Mode3":"False","Mode4":"9440","Mode6":"2","DomoticzVersion":"2024.4 (build 15960)","DomoticzHash":"0043123f8","DomoticzBuildTime":"2024-04-25 12:58:39","PluginBranch":"stable7","PluginVersion":"7.1.004","CertifiedDbVersion":"4.259","TimeStamp":1715878680,"available":"7.1.012","available-firmMajor":0,"available-firmMinor":0,"FirmwareVersion":"6.10.3.0 build 297","FirmwareUpdate":false,"PluginUpdate":true,"LogLevel":7,"Zigpy":true,"CoordinatorModel":"Unknown Silicon Labs","DisplayFirmwareVersion":"UNK - 6.10.3.0 build 297","CoordinatorIEEE":"e0798dfffe71910c","NetworkSize":"Total: 30 | Routers: 12 | End Devices: 18","NetworkDevices":{"1002":{"_TZE200_b6wax7g0":["TS0601-_TZE200_b6wax7g0"],"_TYZB01_ftdkanlj":["TS0222"],"_TZ3000_dowj6gyi":["TS0201"],"_TZ3210_mja6r5ix":["TS0505B"]},"1141":{"_TZ3000_gjnozsaz":["TS011F-plug"],"_TZ3000_dowj6gyi":["TS0201"],"_TZ3000_tqlv4ug4":["TS0001"],"_TZE204_t1blo2bj":["TS0601-_TZE200_t1blo2bj"],"_TZ3000_decxrtwa":["TS0203"],"_TZ3210_pzqmlfgj":["TS0505B"]}}},"Analytics":1,"Device":{"Version":"3","ZDeviceName":"","Status":"UNKNOW","SQN":"24","Ep":{"01":{"0000":{"0004":"_TZE204_pcdmj88b","0000":3,"0001":73,"0005":"TS0601","0007":3,"fffe":0,"ffe2":56,"ffe4":1},"0004":{},"0005":{},"ef00":{},"0019":{},"000a":{}}},"Heartbeat":"402","RIA":"4","LQI":255,"Battery":{},"Model":"TS0601","ForceAckCommands":[],"MacCapa":"80","IEEE":"a4c13856b3c43d87","Type":{},"ProfileID":"0104","ZDeviceID":"0051","App Version":73,"Attributes List":{},"DeviceType":"RFD","HW Version":"","Last Cmds":[],"LogicalType":"End Device","Manufacturer":"1141","Manufacturer Name":"_TZE204_pcdmj88b","NbEp":"1","PowerSource":"Battery","ReadAttributes":{"Ep":{"01":{"0000":{"TimeStamp":1715876672,"iSQN":{"0004":"00","0000":"00","0001":"00","0005":"00","0007":"00","fffe":"00"},"Attributes":{"0004":"00","0000":"00","0001":"00","0005":"00","0007":"00","fffe":"00","ffe2":"00","ffe4":"00"},"ZigateRequest":{}}}}},"ReceiveOnIdle":"Off","Stack Version":"","Stamp":{"time":1715878680.7828844,"Time":"2024-05-16 18:58:00","MsgType":"8011","LastSeen":1715878680},"ZCL Version":3,"Health":"Live","Capability":["Reduced-Function Device","Standard security","NwkAddr should be allocated"],"ZCLSQN":"3e","ZDPSQN":"04","RollingLQI":[255,255,255,255,255,255,255,255,255,255,255],"WriteAttributes":{"Ep":{"01":{"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"Epv2":{"01":{"ProfileID":"0104","ZDeviceID":"0051","ClusterIn":{"0004":{},"0005":{},"ef00":{},"0000":{}},"ClusterOut":{"0019":{},"000a":{}}}},"ReqEpv2":{"01":1715876669.1105824},"PairingInProgress":true,"ZDeviceVersion":"0001","ConfigSource":"8043","ZCL-IN-SQN":{"ef00":"24","0000":"dd","000a":"bf"},"Tuya":{"TUYA_MCU_VERSION_RSP":"40","Valve 0x05":"000000d2","Valve state":"64"},"SQN_000a":"bf","_rawNodeDescriptor":"1141004200422a000080424002","Max Buffer Size":"42","Max Rx":"0042","Max Tx":"0042","macapa":"80","bitfield":"4002","server_mask":"2a00","descriptor_capability":"00"}}

Je me tiens à ta disposition pour tout complément.
Merci.

**Comment by pipiche38** [comment]
Can you try the following:

(1) download the file https://github.com/zigbeefordomoticz/z4d-certified-devices/blob/a49dda1a975c2dc385c1c79034c6c10ef4a4dde9/z4d_certified_devices/Certified/Tuya/TS0601-eTRV6.json
(2) put the file under `Domoticz-Zigbee/Conf/Local-Devices/`
(3) edit the file and add the following `[ "TS0601", "_TZE204_pcdmj88b" ]` under the Identifier section

You should get something similar to that
 ``` 
"Identifier": [
        [ "TS0601", "_TZE200_bvu2wnxz" ],
        [ "TS0601", "_TZE200_6rdj8dzm" ],
        [ "TS0601", "_TZE200_gd4rvykv" ],
        [ "TS0601", "_TZE200_p3dbf6qs" ], 
        [ "TS0601", "_TZE200_rxntag7i" ],
        [ "TS0601", "_TZE204_pcdmj88b" ]
    ],
```


Restart the plugin (check if they are error when loading the Config files)

then when the plugin is ready try to pair the device and see what works and what doesn't


Here are some related links on the wiki which can help you

* https://github.com/zigbeefordomoticz/wiki/blob/master/en-eng/HowTo_Device-Customization.md
* https://github.com/zigbeefordomoticz/wiki/blob/master/en-eng/HowTo_Device-Customization-TS0601.md

**Comment by Snake40** [comment]
Bonjour.
L'appairage a été fait et il est déclaré "correct" dans le plugin.
3 des 4 widgets créés dans Domoticz ont été fonctionnellement identifiés. Je n'ai pas trouvé la fonction associée au widget "heating status". Je comprends qu'il est possible d'obtenir une personnalisation plus grande (ie avoir plus de widgets fonctionnels dans Domoticz) à condition de modifier le fichier de configuration. Je vais lire les contenus des liens que tu m'as communiqué pour essayer de comprendre et d'aller plus loin ...
Merci pour ton aide et ta réactivité.
Bonne journée.

**Comment by zigbeefordomoticz** [comment]
Il est probable que le heating status n’existe pas sur cette tête. Du coup il faudrait supprimer cela du fichier de config.Envoyé de mon iPadLe 17 mai 2024 à 10:20, Snake40 ***@***.***> a écrit :﻿
Bonjour.
L'appairage a été fait et il est déclaré "correct" dans le plugin.
3 des 4 widgets créés dans Domoticz ont été fonctionnellement identifiés. Je n'ai pas trouvé la fonction associée au widget "heating status". Je comprends qu'il est possible d'obtenir une personnalisation plus grande (ie avoir plus de widgets fonctionnels dans Domoticz) à condition de modifier le fichier de configuration. Je vais lire les contenus des liens que tu m'as communiqué pour essayer de comprendre et d'aller plus loin ...
Merci pour ton aide et ta réactivité.
Bonne journée.

**Comment by Snake40** [comment]
Pour un équipement zigbee donné et a priori inconnu est-il possible de capturer toutes les données zigbee émises ? Les identifier et les associer à des fonctions étant une autre question ...

**Comment by pipiche38** [comment]
you can add debug log like TuyaTS0601 or Tuya and check the plugin log file.

**Comment by Snake40** [comment]
Bonjour pipiche ...
Je suis toujours et sans succès, sur l'adaptation de mon TRV au plugin Domoticz ...
A la suite des manips que tu m'as dit de faire, j'ai bien récupéré le TRV dans Domoticz mais "a minima" (voir ci-dessus mon message d'il y a 3 semaines.). Je ne tiens pas particulièrement à récupérer, à paramétrer ou à modifier toutes les données zigbee diffusées par le TRV mais mon "minima opérationnel" est le suivant :
- avoir la température dans la pièce --> je l'ai ;
- avoir le réglage de la température de consigne --> je l'ai ;
- pouvoir me mettre en mode "manuel" --> je peux ;
- avoir le pourcentage d'ouverture de la vanne du radiateur (qui correspond au pourcentage de sortie du doigt de commande du TRV) --> je ne l'ai pas ...
Cela me gêne énormément car c'est le seul vrai moyen de savoir si et comment le TRV réagit à la température de consigne sans le déposer, ce qui permet de détecter une anomalie ou un dysfonctionnement (sur les 5 TRV MOES que j'ai intégré initialement, 3 s'avèrent en anomalie sur le pourcentage d'ouverture - confirmé lorsque je démonte le TRV - et c'est pourquoi je cherche un autre modèle).
L'info existe, c'est sûr ... J'ai essayé de comprendre comment était construit le fichier de configuration dans Domoticz, j'ai cherché sur internet des réponses pour tenter une transposition via une situation similaire ... mais j'ai dépassé ma limite de compréhension et je ne m'en sors pas ...
Peux tu me donner quelques éléments (simples ... très simples ...) qui pourraient me mettre sur la piste de la solution ?...
Je suis désolé de te relancer de nouveau sur ce thème, je suppose que tu as d'autres chats à fouetter ...
Cordialement.

**Comment by pipiche38** [comment]
To my knowledge the % of heating info do not exist.

Here are the today's decoded value from the community

[2, 'preset', tuya.valueConverterBasic.lookup(
                    {'schedule': tuya.enum(0), 'holiday': tuya.enum(1), 'manual': tuya.enum(2), 'comfort': tuya.enum(3), 'eco': tuya.enum(4)})],
                [4, 'current_heating_setpoint', tuya.valueConverter.divideBy10],
                [5, 'local_temperature', tuya.valueConverter.divideBy10],
                [6, 'battery', tuya.valueConverter.raw],
                [7, 'child_lock', tuya.valueConverter.lockUnlock],
                [21, 'holiday_temperature', tuya.valueConverter.divideBy10],
                [24, 'comfort_temperature', tuya.valueConverter.divideBy10],
                [25, 'eco_temperature', tuya.valueConverter.divideBy10],
                [28, 'schedule_monday', tuya.valueConverter.thermostatScheduleDayMultiDPWithDayNumber(1)],
                [29, 'schedule_tuesday', tuya.valueConverter.thermostatScheduleDayMultiDPWithDayNumber(2)],
                [30, 'schedule_wednesday', tuya.valueConverter.thermostatScheduleDayMultiDPWithDayNumber(3)],
                [31, 'schedule_thursday', tuya.valueConverter.thermostatScheduleDayMultiDPWithDayNumber(4)],
                [32, 'schedule_friday', tuya.valueConverter.thermostatScheduleDayMultiDPWithDayNumber(5)],
                [33, 'schedule_saturday', tuya.valueConverter.thermostatScheduleDayMultiDPWithDayNumber(6)],
                [34, 'schedule_sunday', tuya.valueConverter.thermostatScheduleDayMultiDPWithDayNumber(7)],
                [35, 'fault_alarm', tuya.valueConverter.errorOrBatteryLow],
                [36, 'frost_protection', tuya.valueConverter.onOff],
                [37, 'boost_heating', tuya.valueConverter.onOff],
                [39, 'scale_protection', tuya.valueConverter.onOff],
                [47, 'local_temperature_calibration', tuya.valueConverter.localTempCalibration2],
                [49, 'system_mode', tuya.valueConverterBasic.lookup({'off': tuya.enum(0), 'heat': tuya.enum(1)})],

**Comment by pipiche38** [comment]
The only information which seems to be available and which can match what you need is the heating status with teh datapoint 49 ( 0x31 )

So you can try by updating the config file and replacing

` "03": { "store_tuya_attribute": "HeatingMode", "sensor_type": "heatingstatus", "EvalExp": "int(not value)"},`
by
` "31": { "store_tuya_attribute": "HeatingMode", "sensor_type": "heatingstatus", "EvalExp": "int(value)"},`

**Comment by Snake40** [comment]
Bonjour.

Merci pour ta réponse et pour ton aide.

Lorsqu'initialement, tu m'as expliqué la procédure d'ajout de mon nouveau TRV et que j'ai lu par ailleurs les dernières évolutions du plugin, j'ai cru comprendre la tendance lourde que vous suiviez à savoir créer des fichiers de configurations facilement modifiables pour les objets zigbee, du moins pour les nouveaux. Ainsi, le fichier json "TS0601-eTRV6.json" que tu m'as fait ajouter dans le plugin concerne apparemment une famille de matériels répondant aux mêmes profils de données (TRV mais pas que ... puisque le "TS0601", "_TZE200_bvu2wnxz" correspond à un capteur de température et d'humidité).

Je pars du principe que tous les matériels dont on parle fonctionnent avec l'appli Tuya smart, ce qui suppose une communauté de profil de données pour tous les équipements fonctionnant avec ...
Le premier TRV que j'ai cherché à intégrer est celui-ci (TS0601-_TZE200_b6wax7g0) :
https://fr.aliexpress.com/item/1005002433465221.html?spm=a2g0o.order_list.order_list_main.656.21ef5e5bJ2CEGB&gatewayAdapt=glo2fra
A l'époque, ancienne version du plugin zigbee, tu as fait une modif. qui m'a permis de récupérer
- via Domoticz les wigets suivants :
  > un selector switch pilotant le mode de fonctionnement du TRV (4 positions pour ce que j'ai pu en juger),
  > un capteur de température donnant la température de la pièce,
 > un setpoint pilotant la température de consigne fixée pour la pièce,
 > un light/switch indiquant si une fenêtre est détectée ouverte dans la pièce,
 et ...
 > une donnée en pourcentage donnant la position du doigt de commande de la vanne du radiateur ... (le doigt totalement rentrée = 100% et le doigt totalement sorti = 0%, les sauts étant, apparemment, par tranches "grossières" de 20%).
- via le plugin les paramètres suivants :
   {'Disabled': 0, 'BRT100WindowsDetection': 1, 'BRT100ChildLock': 1, 'BRT100BoostDuration': 300, 'BRT100Calibration': 0, 'BRT100SetpointEco': 15, 'BRT100MaxSetpoint': 40, 'BRT100MinSetpoint': 5}

J'ai fouillé dans les fichiers du plugin zigbee de mon conteneur Domoticz et je n'ai pas réussi à trouver le fichier de configuration de ce TRV ; où est-il ?

Le TRV récemment ajouté a aujourd'hui
- dans Domoticz les widgets suivants :
  > un selector switch pilotant le mode de fonctionnement du TRV (3 positions pour ce que j'ai pu en juger),
  > un capteur de température donnant la température de la pièce,
 > un setpoint pilotant la température de consigne fixée pour la pièce,
et ...
 > un light/switch "heating status" dont je n'ai pas réussi à déterminer l'objet.
- via le plugin : aucun paramètre accessible.
- 
Lorsque je ne connais pas ou lorsque je ne comprends pas, je procède par analogies et homothéties. Dans le cas considéré l'ancien et le nouveau TRV ont quasiment la même notice d'emploi de l'application Tuya smart ... Je me dis, peut-être à tort, que leurs profils de données zigbee sont similaires sinon identiques ... d'où mon obstination à ne pas comprendre pourquoi, je n'arrive pas à avoir les mêmes données zigbee pour les 2 TRV. Une transposition du fichier de conf de l'ancien TRV vers le nouveau serait-elle pertinente ?

Désolé pour la longueur de mon message et merci pour ton écoute ...
Bonne journée.

**Comment by pipiche38** [comment]
Kindly use the forum or keybase where you can have interactive discussion via chat.

**Comment by pipiche38** [comment]
Pour avoir la vanne entre mes main, et connectée sur l'application Tuya, le % d'ouverture n'est pas disponible.
Donc si tu a besoin de cette information ce n'est pas avec cet equipement que tu y arriveras

**Comment by pipiche38** [comment]
Pour moi cette tete fonctionne, elle a pas mal de latence dans le sens, on passe une commande et il s'ecoule 1 ou 2 minutes avant que l'information soit dispo sur le plugin. mais ca semble etre lié au mécanisme de la tete. Du coup pas grand chose a faire

**Comment by Snake40** [comment]
Merci pour tes derniers efforts pour répondre à mes questions sur le TRV. Dont acte pour l'absence du paramètre d'ouverture de la vanne (je suis d'ailleurs revenu sur mon jugement initial concernant l'importance de ce paramètre car j'ai constaté que la valeur remontée par le TRV MOES était, pour le moins, "sujette à caution" ... pour ne pas dire "fantaisiste") mais mon propos principal portait sur le peu de paramètres accessibles remontés par le TRV via zigbeefordomoticz. A titre indicatif, je teste actuellement le couple "coordinateur SLZB-06 (en ethernet) / zigbee2mqtt (installation sous docker)" et tous les matériels que j'ai raccordés à ce jour, dernier TRV inclus, ont été reconnus sans difficulté avec un accès simple et quasi complet à tous les paramètres et données délivrables par les matériels installés. Parallèlement, je teste le couple "Home assistant (installation sous docker) / zigbee2mqtt") et je suis très impressionné par le potentiel de ce couple au regard du couple "Domoticz / plugin zigbeefordomoticz" même si ce potentiel n'est accessible qu'au prix de complexités significativement plus importantes ...Bonne journée.envoyé : 13 septembre 2024 à 17:49de : Pipiche ***@***.***>à : zigbeefordomoticz/z4d-certified-devices ***@***.***>cc : Snake40 ***@***.***>, Author ***@***.***>objet : Re: [zigbeefordomoticz/z4d-certified-devices] TRV BAB-1413Pro-E (Issue #65) Pour avoir la vanne entre mes main, et connectée sur l'application Tuya, le % d'ouverture n'est pas disponible. Donc si tu a besoin de cette information ce n'est pas avec cet equipement que tu y arriveras—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
