### ISSUE TITLE
icasa dimmer ICZB-R12D

### ISSUE THREAD

**Issue by atmfrenki** [zigbeefordomoticz/z4d-certified-devices#66]
(https://www.partsnl.nl/iczb-r12d-zigbee-dimmer-draaidimmer-72800110)
    * Product Name icasa dimmer ICZB-R12D
    * Brand icasa
    - It is now registred as a Non optimized device in the plugin. I i experience zigbee network issues. I suspect this device is the cause.

1. Document as much what works, what doesn't work, what do you miss, what do you need
-Dimming works
-On/OFF works
-It is correct added in domoticz

[export.json](https://github.com/user-attachments/files/15765980/export.json)

**Comment by pipiche38** [comment]
certified with [5.262]'

**Comment by atmfrenki** [comment]
Thanks!!
