### ISSUE TITLE
ONENUO Tuya Zigbee Smart Siren Alarm For Home

### ISSUE THREAD

**Issue by Rylfas** [zigbeefordomoticz/z4d-certified-devices#67]
1. ONENUO Tuya Zigbee Smart Siren Alarm For Home
1. Provide the URL where you have purchase the device
    * Smart Siren Alarm For Home
    * ONENUO 
    * [URL on a web site](https://www.aliexpress.com/item/1005006443766846.html?spm=a2g0o.order_list.order_list_main.23.43501802DZmd0I)
    * Pre-loaded 18 optional alarm sounds. each tone is volume adjustable between"Low""Middle""High"three level.
1. At the moment 1 alarm with low volume. No option to choose otherwise
[export(4).json](https://github.com/user-attachments/files/15847879/export.4.json)

1. Got to the Tools Menu
1. Select Plugin Raw Devices (json)
1. Export

This will create an export.json file that you can save.

# Donations and Sponsorship

We warmly invite Manufacturers and sellers to contribute by sending us samples of their devices for integration. Your support in this regard is greatly appreciated as it enables us to expand our compatibility and offer a more comprehensive solution.

We extend our heartfelt gratitude to our generous donors whose contributions enable us to acquire additional equipment for rigorous testing and seamless integration. With your support, we can further enhance the plugin's capabilities and deliver an even more powerful and versatile experience for our users.

Donate via PayPal https://paypal.me/pipiche

**Comment by pipiche38** [comment]
Alarm Duration, Alarm Level and Alarm Melody are defined in the Device Parameters

https://github.com/zigbeefordomoticz/wiki/blob/master/en-eng/HowTo_Device-parameters.md

**Comment by pipiche38** [comment]
Melody (TuyaAlarmMelody) is 1 by default and you can use the numbers from 1 to 18
Volume (TuyaAlarmLevel) is 0 by default and can be 0,1,2
Duration (TuyaAlarmDuration) is 10s by default you can go up to 1800s

**Comment by Rylfas** [comment]
> Melody (TuyaAlarmMelody) is 1 by default and you can use the numbers from 1 to 18 Volume (TuyaAlarmLevel) is 0 by default and can be 0,1,2 Duration (TuyaAlarmDuration) is 10s by default you can go up to 1800s

Merci once again!
