### ISSUE TITLE
[Model Certification] - LED E27 bulb ZigBee Light Link Extension RGB color change CCT control Glas - Amber

### ISSUE THREAD

**Issue by Chrominator** [zigbeefordomoticz/z4d-certified-devices#69]
1. Please do provide device information such as Brand and Model name.
GLEDOPTO

    item ID: 9324-A
    GTIN: 4260567172411
    SKU: GL-B-003P

1. Provide the URL where you have purchase the device
GLEDOPTO – Zigbee 3.0 Ampoule à Filament LED 7W E27 (2200k-6500k) Vintage Amber A60 CCT Fonctionne avec l'application Hu*e Tuya SmartThings Alexa Commande vocale 
    * [https://www.amazon.fr/dp/B0B24STL13?psc=1&ref=ppx_yo2ov_dt_b_product_details](https://www.amazon.fr/dp/B0B24STL13?psc=1&ref=ppx_yo2ov_dt_b_product_details)
    * Using it as a dimmer with several temperature colors

1. Document as much what works, what doesn't work, what do you miss, what do you need
Pairing Ok, not optimized in the pluggin. Use seems to be Ok in domoticz.
1. Got to the Tools Menu
1. Select Plugin Raw Devices (json)
1. Export

This will create an export.json file that you can save.
[export.json](https://github.com/user-attachments/files/16408906/export.json)
Thank you.

**Comment by pipiche38** [comment]
should be fixed with 5.290 of the Certified Devices.
