### ISSUE TITLE
[Model Certification] - AQARA Light Detection Sensor T1 GZCGQ1LM

### ISSUE THREAD

**Issue by Chrominator** [zigbeefordomoticz/z4d-certified-devices#73]
1. Please do provide device information such as Brand and Model name.
AQARA Light Detection Sensor T1 GZCGQ1LM
1. Provide the URL where you have purchase the device
    * Product Name : Light Detection Sensor T1
    * Brand : AQARA 
    * URL on a web site [https://fr.aliexpress.com/item/1005004974217500.html?spm=a2g0o.order_list.order_list_main.5.23975e5bmGLA3x&gatewayAdapt=glo2fra](https://fr.aliexpress.com/item/1005004974217500.html?spm=a2g0o.order_list.order_list_main.5.23975e5bmGLA3x&gatewayAdapt=glo2fra)
    * What do you expect : Object being optimized.

1. Document as much what works, what doesn't work, what do you miss, what do you need

Pairing Ok in Domoticz, Devices created (1 lux/lux + 1 general/voltage).
    Lux are reported, Voltage shows 3.2V.
    Object shown not optimized in Zigbeefordomoticz.

1. Got to the Tools Menu
1. Select Plugin Raw Devices (json)
1. Export

This will create an export.json file that you can save.
[export(1).json](https://github.com/user-attachments/files/17191866/export.1.json)

# Donations and Sponsorship

We warmly invite Manufacturers and sellers to contribute by sending us samples of their devices for integration. Your support in this regard is greatly appreciated as it enables us to expand our compatibility and offer a more comprehensive solution.

We extend our heartfelt gratitude to our generous donors whose contributions enable us to acquire additional equipment for rigorous testing and seamless integration. With your support, we can further enhance the plugin's capabilities and deliver an even more powerful and versatile experience for our users.

Donate via PayPal https://paypal.me/pipiche

**Comment by pipiche38** [comment]
Kindly update the certified Db to 5.318
