### ISSUE TITLE
[Model Certification] - SONOFF SNZB-04P Capteur de porte ou fenêtre Zigbee 3.0

### ISSUE THREAD

**Issue by Chrominator** [zigbeefordomoticz/z4d-certified-devices#75]
1. Please do provide device information such as Brand and Model name.
SONOFF SNZB-04P

2. Provide the URL where you have purchase the device
    * Product Name
    Capteur de porte ou fenêtre Zigbee 3.0
    * Brand
    SONOFF
    * URL on a web site
    [https://fr.aliexpress.com/item/1005007322140876.html?spm=a2g0o.productlist.main.3.5f8869c4BiZvO6&algo_pvid=56fc59d3-027f-4d0b-b7a7-6e8e8b8ea4d4&algo_exp_id=56fc59d3-027f-4d0b-b7a7-6e8e8b8ea4d4-1&pdp_npi=4%40dis%21EUR%2117.34%2111.79%21%21%2118.70%2112.72%21%40211b8f9a17279298986591055e885e%2112000040256558371%21sea%21FR%21193746028%21X&curPageLogUid=griZJoYR8jaT&utparam-url=scene%3Asearch%7Cquery_from%3A](https://fr.aliexpress.com/item/1005007322140876.html?spm=a2g0o.productlist.main.3.5f8869c4BiZvO6&algo_pvid=56fc59d3-027f-4d0b-b7a7-6e8e8b8ea4d4&algo_exp_id=56fc59d3-027f-4d0b-b7a7-6e8e8b8ea4d4-1&pdp_npi=4%40dis%21EUR%2117.34%2111.79%21%21%2118.70%2112.72%21%40211b8f9a17279298986591055e885e%2112000040256558371%21sea%21FR%21193746028%21X&curPageLogUid=griZJoYR8jaT&utparam-url=scene%3Asearch%7Cquery_from%3A)
    * What do you expect
    There is 3 devices created in Domoticz
    * 1 switch On/Off
    * 1 switch Open/Closed
    * 1 General Voltage with 0V

1. Document as much what works, what doesn't work, what do you miss, what do you need
I guess that the voltage is missing, there's also a tamper sensor in the back of the module which is not created in Domoticz.
Probably the cause of the non optimization.

1. Got to the Tools Menu
1. Select Plugin Raw Devices (json)
1. Export

This will create an export.json file that you can save.

[export(2).json](https://github.com/user-attachments/files/17239405/export.2.json)
# Donations and Sponsorship

We warmly invite Manufacturers and sellers to contribute by sending us samples of their devices for integration. Your support in this regard is greatly appreciated as it enables us to expand our compatibility and offer a more comprehensive solution.

We extend our heartfelt gratitude to our generous donors whose contributions enable us to acquire additional equipment for rigorous testing and seamless integration. With your support, we can further enhance the plugin's capabilities and deliver an even more powerful and versatile experience for our users.

Donate via PayPal https://paypal.me/pipiche

**Comment by pipiche38** [comment]
The device seems to not provide Voltage but only Battery Percentage.

Kindly update the Certified Db to 5.316 and redo the pairing from scratch (not sure if Tamper will work, but kindly test it and report the result)

**Comment by pipiche38** [comment]
If I summarize the Tamper is not functionning, the rest is ok ?

**Comment by Chrominator** [comment]
Correct

**Comment by pipiche38** [comment]
You need yo switch to the wip-stable7-7.1.13 branch

git checkout wip-stable7-7.1.13
git pull
sudo python3 -m pip install -r requirements.txt --upgrade

then restart the plugin, there is no need to redo the pairing. Kindly tell me how it behave after .

Would be great if you could also provide a new export.json after the test

**Comment by Chrominator** [comment]
Hi,

Failed:
![image](https://github.com/user-attachments/assets/ec35de5e-d625-4fcc-a8bf-08e274139c49)
Might be linked to the status of the branch (I'm not an expert).
![image](https://github.com/user-attachments/assets/b7e3b05d-d3b2-4c50-9f7a-d89d55f56a7a)

**Comment by pipiche38** [comment]
can you do:

```
git pull
git checkout wip-stable7-7.1.13
```

**Comment by Chrominator** [comment]
Another brand new SONOFF SNZB-04P paired:

![image](https://github.com/user-attachments/assets/5961cc40-9a27-4487-a462-2a6787e9c1eb)

Open/Closed ok.
No effet on the tamper, remains undefined.

[export(3).json](https://github.com/user-attachments/files/17449592/export.3.json)

**Comment by pipiche38** [comment]
From the export, it looks like the Tamper was On , correct ?

can you retrieve the certified Db 5.321 , and then check the behaviour (no need to re-pair)

**Comment by Chrominator** [comment]
You're done !
Great job, it works like a charm.
No alert when stick to the wall, else Tamper is activated.
Tamper status is independent of open/close status, acting as a second switch actually.
Works fine, thank you pipiche38.
