### ISSUE TITLE
[Model Certification] - Ewelink led bulb GU10 CK-BL702-AL-01(7009_Z102LG03-1)

### ISSUE THREAD

**Issue by ouiouiblog** [zigbeefordomoticz/z4d-certified-devices#77]
I bought that GU10 led on Ali Express  [https://fr.aliexpress.com/item/1005006099930203.html]

The plugin says that the device is not optimized. I can control it, but it seems to generate a bit of charge.
[export (1).json](https://github.com/user-attachments/files/17299246/export.1.json)

**Comment by pipiche38** [comment]
kindly update the certified db to 5.314
