### ISSUE TITLE
TRÅDFRI Ampoule LED E27 470 lumen, connecté sans fil à variateur d'intensité/blanc chaud transparent/globe

### ISSUE THREAD

**Issue by adruet29** [zigbeefordomoticz/z4d-certified-devices#78]
1. TRÅDFRI Ampoule LED E27 470 lumen, connecté sans fil à variateur d'intensité/blanc chaud transparent/globe
[1. Provide the URL where you have purchase the device
    * Product Name : TRÅDFRI Ampoule LED E27 470 lumen
    * Brand: IKEA
    * URL on a web site: https://www.ikea.com/fr/fr/p/tradfri-ampoule-led-e27-470-lumen-connecte-sans-fil-a-variateur-dintensite-blanc-chaud-transparent-globe-90539072/
    * What do you expect: it's working great, just reported as "non optimized"

This one should be easy, it works great (simple turn on/off as well as the dimming part), it is just reported as "non optimized", don't know if it's important for the plugin, but for we it's 100% ok.

Here are the raw objets exports: 
[export.json](https://github.com/user-attachments/files/17505818/export.json)

**Comment by pipiche38** [comment]
the export.json is not correct.

**Comment by adruet29** [comment]
Here is the export.json: 
[export.json](https://github.com/user-attachments/files/17549028/export.json)

**Comment by pipiche38** [comment]
Kindly update Certified Db to 5.325

**Comment by adruet29** [comment]
This is perfect, we can close the issue.
