### ISSUE TITLE
[Model Certification] - SENSOR Temp and Humidity with display

### ISSUE THREAD

**Issue by oli80330** [zigbeefordomoticz/z4d-certified-devices#79]
1. Please do provide device information such as Brand and Model name.
1. Provide the URL where you have purchase the device
    * Product Name : ?
    * Brand : ?
    * URL on a web site : https://fr.aliexpress.com/item/4000843004202.html?spm=a2g0o.order_list.order_list_main.31.1f1f5e5bPcUGOb&gatewayAdapt=glo2fra
    
    * What do you expect : TEMP and HUMIDITY, not only TEMP

1. Document as much what works, what doesn't work, what do you miss, what do you need

1. Got to the Tools Menu
1. Select Plugin Raw Devices (json)
1. Export

This will create an export.json file that you can save.
{"PluginInfos":{"HardwareID":70,"HomeFolder":"/home/pi/domoticz/plugins/Domoticz-Zigbee/","StartupFolder":"/home/pi/domoticz/","UserDataFolder":"/home/pi/domoticz/","WebRoot":"","Database":"/home/pi/domoticz/domoticz.db","Language":"fr","Version":"6.3","Author":"pipiche38","Name":"ZIGBEE","Address":"0.0.0.0","Port":"9999","SerialPort":"/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CCE0072-if00","Key":"Zigate","Mode1":"ZigpyZNP","Mode2":"USB","Mode3":"False","Mode4":"9440","Mode6":"2","DomoticzVersion":"2024.7","DomoticzHash":"b317cfab1","DomoticzBuildTime":"2024-07-13 16:59:31","PluginBranch":"stable6","PluginVersion":"6.3.015","TimeStamp":1730315747,"available":0,"available-firmMajor":0,"available-firmMinor":0,"FirmwareVersion":"Z-Stack Home 1.2 (build 20201127)","FirmwareUpdate":false,"PluginUpdate":false,"LogLevel":7,"Zigpy":true,"CoordinatorModel":"CC2531, Z-Stack Home 1.2 (znp)","CoordinatorFirmwareVersion":"Z-Stack Home 1.2 (build 20201127)","DisplayFirmwareVersion":"Znp - Z-Stack Home 1.2 (build 20201127)","CoordinatorIEEE":"00124b001cce0072","NetworkSize":"Total: 7 | Routers: 3 | End Devices: 4","NetworkDevices":{"1002":{"_TZ3000_wamqdr3f":["TS011F"]},"1141":{"_TZ3000_fllyghyj":["TS0201"],"_TZ3000_xr3htd96":["TS0201"]}}},"Analytics":1,"Device":{"Version":"3","ZDeviceName":"SDJ","Status":"inDB","SQN":"49","Ep":{"01":{"0402":{"0000":2360},"ClusterType":{"9679":"Temp"},"0001":{"0020":26,"0021":100},"0405":{"0000":66.9}}},"Heartbeat":"410","RIA":"4","LQI":68,"Battery":100,"Model":"","ForceAckCommands":[],"MacCapa":"80","IEEE":"847127fffec6ce78","Type":"Temp","ProfileID":{},"ZDeviceID":{},"App Version":"","Attributes List":{},"DeviceType":"RFD","HW Version":"","Last Cmds":[],"LogicalType":"End Device","Manufacturer":"","Manufacturer Name":"","NbEp":"","PowerSource":"Battery","ReadAttributes":{"Ep":{"01":{"0000":{"TimeStamp":1730313663,"iSQN":{"0004":"01","0000":"01","0001":"01","0005":"01","0007":"01","fffe":"01"},"Attributes":{},"ZigateRequest":{}},"0402":{"TimeStamp":1730315723,"iSQN":{"0000":"03"},"Attributes":{"0000":"00"},"ZigateRequest":{}},"0001":{"TimeStamp":1730315484,"iSQN":{},"Attributes":{"0020":"00","0021":"00"},"ZigateRequest":{}},"0405":{"TimeStamp":1730315724,"iSQN":{},"Attributes":{"0000":"00"},"ZigateRequest":{}}}}},"ReceiveOnIdle":"","Stack Version":"","Stamp":{"time":1730315725.2196252,"Time":"2024-10-30 20:15:25","MsgType":"8011","LastSeen":1730315725},"ZCL Version":"","Health":"Live","WriteAttributes":{"Ep":{"01":{"0402":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0001":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0405":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"Param":{},"Capability":["Reduced-Function Device","Standard security","NwkAddr should be allocated"],"ConfigureReporting":{"Ep":{"01":{"0402":{"TimeStamp":1730313673.1155725,"iSQN":{"0000":"02"},"Attributes":{},"ZigateRequest":{}}}}},"BatteryUpdateTime":1730315484,"BindingTable":[{"Devices":[],"SQN":0,"Status":"","TimeStamp":1730313673,"Time":1730313673}],"CertifiedDevice":false,"ConsistencyCheck":"ok","ZCL-IN-SQN":{"0402":"48","0405":"49","0001":"43"},"RollingLQI":[68,68,68,70,70,70,70,68,68,68,68],"PreviousStatus":"inDB","CheckParam":false}}

# Donations and Sponsorship

We warmly invite Manufacturers and sellers to contribute by sending us samples of their devices for integration. Your support in this regard is greatly appreciated as it enables us to expand our compatibility and offer a more comprehensive solution.

We extend our heartfelt gratitude to our generous donors whose contributions enable us to acquire additional equipment for rigorous testing and seamless integration. With your support, we can further enhance the plugin's capabilities and deliver an even more powerful and versatile experience for our users.

Donate via PayPal https://paypal.me/pipiche

**Comment by pipiche38** [comment]
kindly update to a more recent version of the plugin.
The export generated is uncomplete either due to the plugin version or missing information from the device

**Comment by oli80330** [comment]
It's OK with plugin V7 (Temp and humidity)
Thanks
