### ISSUE TITLE
[Model Certification] - EACHEN Interrupteur de Relais Intelligent Zigbee à 4 Canaux

### ISSUE THREAD

**Issue by diliak** [zigbeefordomoticz/z4d-certified-devices#8]
Platine 4 relais Zigbee avec interface gérable aussi en 433mHz.
Je n'utilise pas la partie 433 car elle est à priori influençable. J'ai eu des soucis de perturbations qui me changeait l'état des relais aléatoirement. 
Par contre, la partie zigbee fonctionne parfaitement mais est reconnue partiellement selon le plugin.

Gestion des 4 relais on-off. Personnellement, je n'en demande pas plus.
Je pilote deux volets Bubendorff en ayant câblé des fils soudés sur les boutons montée-descente.

https://www.amazon.fr/gp/product/B0928B2SDB/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1

Extrait du plugin :

{"PluginInfos":{"HardwareID":7,"HomeFolder":"/home/diliak/domoticz/plugins/Domoticz-Zigbee/","StartupFolder":"/home/diliak/domoticz/","UserDataFolder":"/home/diliak/domoticz/","WebRoot":"","Database":"/home/diliak/domoticz/domoticz.db","Language":"fr","Version":"7.1","Author":"pipiche38","Name":"Zigate","Address":"0.0.0.0","Port":"9999","SerialPort":"/dev/ttyUSB22","Key":"Zigate","Mode1":"V2","Mode2":"USB","Mode3":"False","Mode4":"9440","Mode6":"2","DomoticzVersion":"2023.2","DomoticzHash":"19efd039c","DomoticzBuildTime":"2023-07-21 17:23:44","PluginBranch":"stable7","PluginVersion":"7.1.001","CertifiedDbVersion":"2.78","TimeStamp":1690627786,"available":"7.1.001","available-firmMajor":"05","available-firmMinor":"0321","FirmwareVersion":"0321","FirmwareUpdate":false,"PluginUpdate":false,"LogLevel":7,"Zigpy":false,"CoordinatorModel":"ZiGate+ (V2)","CoordinatorFirmwareVersion":"0321","DisplayFirmwareVersion":"Zigate - 0321","CoordinatorIEEE":"00158d0005d2a895","NetworkSize":"Total: 13 | Routers: 7 | End Devices: 6","NetworkDevices":{"1002":{"_TZE200_b6wax7g0":["TS0601-_TZE200_b6wax7g0"],"_TZ3000_excgg5kb":["TS0004"],"_TZ3000_typdpbpg":["TS011F-plug"]},"1015":{"frient A/S":["SPLZB-131"]},"1037":{"LUMI":["lumi.weather"]},"1141":{"_TZ3000_typdpbpg":["TS011F-plug"]},"100b":{"Signify Netherlands B.V.":["LOM008"]}}},"Analytics":1,"Device":{"Version":"3","ZDeviceName":"Relais volets salon","Status":"inDB","SQN":"b6","Ep":{"01":{"0000":{"0004":"_TZ3000_excgg5kb","0005":"TS0004","0000":3,"0001":"80","0002":"0","0003":"1","0006":"None","0007":"1"},"0003":{},"0004":{},"0005":{},"0006":{"4001":"0","4002":"0","5000":"1","8000":"00","8001":"1","8002":"0","0000":"00"},"e000":{"d003":"AAAAAgAABAAABgAA","d001":"06","d002":"0a"},"e001":{"d010":0,"d030":0},"0019":{"0001":"ffffffff","0002":"00000050","0003":"0002","0004":"ffffffff","0005":"ffff","0006":"00","0007":"1141","0008":"ffff","0009":"0000"},"000a":{},"ClusterType":{"194":"Switch"}},"02":{"0004":{},"0005":{},"0006":{"4001":"0","4002":"0","0000":"00"},"e001":{"d010":0},"ClusterType":{"195":"Switch"}},"03":{"0004":{},"0005":{},"0006":{"4001":"0","4002":"0","0000":"00"},"e001":{"d010":0},"ClusterType":{"196":"Switch"}},"04":{"0004":{},"0005":{},"0006":{"4001":"0","4002":"0","0000":"00"},"e001":{"d010":0},"ClusterType":{"197":"Switch"}},"f2":{"0021":{}}},"Heartbeat":"3017","RIA":"4","LQI":55,"Battery":{},"Model":"TS0004","ForceAckCommands":[],"MacCapa":"8e","IEEE":"a4c138e5164c04cf","Type":"Switch","ProfileID":"a1e0","ZDeviceID":"0061","App Version":"80","Attributes List":{"Request":{"01":{"0000":1669756591.092504,"0003":1669756591.0925357,"0004":1669756591.0925648,"0005":1669756591.0925932,"0006":1669756591.0926216,"e000":1669756591.0926685,"e001":1669756591.0927038,"0019":1669756591.0927324,"000a":1669756591.0927613},"02":{"0004":1669756591.0927923,"0005":1669756591.092821,"0006":1669756591.0928495,"e001":1669756591.0928833},"03":{"0004":1669756591.092914,"0005":1669756591.092942,"0006":1669756591.09297,"e001":1669756591.093003},"04":{"0004":1669756591.0930333,"0005":1669756591.093062,"0006":1669756591.0930903,"e001":1669756591.0931387},"f2":{"0021":1669756591.0931845}}},"DeviceType":"FFD","HW Version":"1","Last Cmds":[[212,"02","7b9a","0100","0101000000000000010000"],[365,"02","7b9a","0100","0101000000000000010000"]],"LogicalType":"Router","Manufacturer":"1002","Manufacturer Name":"_TZ3000_excgg5kb","NbEp":"5","PowerSource":"Main","ReadAttributes":{"Ep":{"01":{"0000":{"TimeStamp":1690132265,"iSQN":{"4000":12767,"0004":12765,"0005":12765,"0000":365,"0001":12765,"0002":12765,"0003":12766,"0006":12766,"0007":12766,"000a":12766,"000f":12766,"0010":12767,"0015":12767,"f000":12767},"Attributes":{"4000":"86","0004":"00","0005":"00","0000":"00","0001":"00","0002":"00","0003":"00","0006":"00","0007":"00","000a":"86","000f":"86","0010":"86","0015":"86","f000":"86"},"ZigateRequest":{}},"e000":{"TimeStamp":1671575992,"iSQN":{},"Attributes":{"d003":"00","d001":"00","d002":"00"},"ZigateRequest":{}},"0006":{"TimeStamp":1690612606,"iSQN":{"4001":12761,"4002":12761,"0000":7292},"Attributes":{"4001":"00","4002":"00","5000":"00","8000":"00","8001":"00","8002":"00"},"ZigateRequest":{}},"e001":{"TimeStamp":1669747483,"iSQN":{},"Attributes":{"d010":"00","d030":"00"},"ZigateRequest":{}},"0019":{"TimeStamp":1669744289,"iSQN":{"0001":12759,"0002":12759,"0003":12759,"0004":12759,"0005":12759,"0006":12760,"0007":12760,"0008":12760,"0009":12760,"000a":12760},"Attributes":{"0001":"00","0002":"00","0003":"00","0004":"00","0005":"00","0006":"00","0007":"00","0008":"00","0009":"00","000a":"86"},"ZigateRequest":{}}},"02":{"0000":{"TimeStamp":1669744267,"iSQN":{"0004":12726,"0005":12726},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":1690612606,"iSQN":{"4001":12762,"4002":12762,"0000":7293},"Attributes":{"4001":"00","4002":"00"},"ZigateRequest":{}},"e001":{"TimeStamp":1669747483,"iSQN":{},"Attributes":{"d010":"00"},"ZigateRequest":{}}},"03":{"0000":{"TimeStamp":1669744267,"iSQN":{"0004":12727,"0005":12727},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":1690612606,"iSQN":{"4001":12763,"4002":12763,"0000":7294},"Attributes":{"4001":"00","4002":"00"},"ZigateRequest":{}},"e001":{"TimeStamp":1669747483,"iSQN":{},"Attributes":{"d010":"00"},"ZigateRequest":{}}},"04":{"0000":{"TimeStamp":1669744267,"iSQN":{"0004":12728,"0005":12728},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":1690612606,"iSQN":{"4001":12764,"4002":12764,"0000":7295},"Attributes":{"4001":"00","4002":"00"},"ZigateRequest":{}},"e001":{"TimeStamp":1669747484,"iSQN":{},"Attributes":{"d010":"00"},"ZigateRequest":{}}},"f2":{"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"ReceiveOnIdle":"On","Stack Version":"0","Stamp":{"time":1690626697.0097003,"Time":"2023-07-29 12:31:37","MsgType":"8011","LastSeen":1690626697,"LastPing":1690626691},"ZCL Version":3,"Health":"Live","NeighbourTableSize":6,"Max Rx":"0042","ConfigSource":"8043","_rawNodeDescriptor":"1141004200422a00008e424001","macapa":"8e","BindingTable":{"Devices":[{"a4c138e5164c04cf":{"sourceEp":"01","Cluster":"0003","targetIEEE":"00158d0005d2a895","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"a4c138e5164c04cf":{"sourceEp":"01","Cluster":"0004","targetIEEE":"00158d0005d2a895","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"a4c138e5164c04cf":{"sourceEp":"01","Cluster":"0005","targetIEEE":"00158d0005d2a895","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"a4c138e5164c04cf":{"sourceEp":"01","Cluster":"0006","targetIEEE":"00158d0005d2a895","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"a4c138e5164c04cf":{"sourceEp":"01","Cluster":"e000","targetIEEE":"00158d0005d2a895","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"a4c138e5164c04cf":{"sourceEp":"01","Cluster":"e001","targetIEEE":"00158d0005d2a895","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"a4c138e5164c04cf":{"sourceEp":"01","Cluster":"0000","targetIEEE":"00158d0005d2a895","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"a4c138e5164c04cf":{"sourceEp":"02","Cluster":"0004","targetIEEE":"00158d0005d2a895","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"a4c138e5164c04cf":{"sourceEp":"02","Cluster":"0005","targetIEEE":"00158d0005d2a895","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"a4c138e5164c04cf":{"sourceEp":"02","Cluster":"0006","targetIEEE":"00158d0005d2a895","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"a4c138e5164c04cf":{"sourceEp":"02","Cluster":"e001","targetIEEE":"00158d0005d2a895","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"a4c138e5164c04cf":{"sourceEp":"03","Cluster":"0004","targetIEEE":"00158d0005d2a895","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"a4c138e5164c04cf":{"sourceEp":"03","Cluster":"0005","targetIEEE":"00158d0005d2a895","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"a4c138e5164c04cf":{"sourceEp":"03","Cluster":"0006","targetIEEE":"00158d0005d2a895","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"a4c138e5164c04cf":{"sourceEp":"03","Cluster":"e001","targetIEEE":"00158d0005d2a895","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"a4c138e5164c04cf":{"sourceEp":"04","Cluster":"0004","targetIEEE":"00158d0005d2a895","targetNickName":"Zigbee Coordinator","targetEp":"01"}}],"SQN":0,"TimeStamp":1669744291.7392037,"BindingTableTableSize":16,"Status":"Success"},"CertifiedDevice":false,"Max Buffer Size":"42","Neighbours":[{"SQN":0,"Status":"","TimeStamp":1690136716,"Time":1690136716,"Devices":[{"0000":{"_relationshp":"Parent","_devicetype":"Coordinator","_depth":0,"_lnkqty":33,"_rxonwhenidl":"Rx-On","_IEEE":"00158d0005d2a895","_permitjnt":"??"}},{"7711":{"_relationshp":"Sibling","_devicetype":"Router","_depth":1,"_lnkqty":0,"_rxonwhenidl":"Rx-On","_IEEE":"001788010bdfd090","_permitjnt":"??"}},{"e7c0":{"_relationshp":"Sibling","_devicetype":"Router","_depth":1,"_lnkqty":48,"_rxonwhenidl":"Rx-On","_IEEE":"a4c1386308426699","_permitjnt":"??"}},{"95c0":{"_relationshp":"Sibling","_devicetype":"Router","_depth":0,"_lnkqty":0,"_rxonwhenidl":"Rx-On","_IEEE":"0015bc002f007874","_permitjnt":"??"}},{"6326":{"_relationshp":"Sibling","_devicetype":"Router","_depth":1,"_lnkqty":0,"_rxonwhenidl":"Rx-On","_IEEE":"a4c1380e0d99c0f7","_permitjnt":"??"}},{"17cd":{"_relationshp":"Sibling","_devicetype":"Router","_depth":1,"_lnkqty":103,"_rxonwhenidl":"Rx-On","_IEEE":"001788010bdfe5f7","_permitjnt":"??"}}]}],"WriteAttributes":{"Ep":{"01":{"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0003":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0004":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0005":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"e000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"e001":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0019":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"000a":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}},"02":{"0004":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0005":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"e001":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}},"03":{"0004":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0005":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"e001":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}},"04":{"0004":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0005":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"e001":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}},"f2":{"0021":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"Param":{},"Epv2":{"01":{"ClusterIn":{"0003":{},"0004":{},"0005":{},"0006":{},"e000":{},"e001":{},"0000":{}},"ClusterOut":{"0019":{},"000a":{}},"ProfileID":"0104","ZDeviceID":"0100"},"02":{"ClusterIn":{"0004":{},"0005":{},"0006":{},"e001":{}},"ClusterOut":{},"ProfileID":"0104","ZDeviceID":"0100"},"03":{"ClusterIn":{"0004":{},"0005":{},"0006":{},"e001":{}},"ClusterOut":{},"ProfileID":"0104","ZDeviceID":"0100"},"04":{"ClusterIn":{"0004":{},"0005":{},"0006":{},"e001":{}},"ClusterOut":{},"ProfileID":"0104","ZDeviceID":"0100"},"f2":{"ClusterIn":{},"ClusterOut":{"0021":{}},"ProfileID":"a1e0","ZDeviceID":"0061"}},"Max Tx":"0042","Log_UnknowDeviceFlag":1690217784.7737234,"SWBUILD_1":"None","server_mask":"2a00","Capability":["Full-Function Device","Main Powered","Receiver during Idle","Standard security","NwkAddr should be allocated"],"Bind":{"01":{"0003":{"Target":"0000","Stamp":1669744286,"Phase":"binded","Status":"00","i_sqn":12736},"0004":{"Target":"0000","Stamp":1669744286,"Phase":"binded","Status":"00","i_sqn":12737},"0005":{"Target":"0000","Stamp":1669744286,"Phase":"binded","Status":"00","i_sqn":12738},"0006":{"Target":"0000","Stamp":1669744286,"Phase":"binded","Status":"00","i_sqn":12739},"e000":{"Target":"0000","Stamp":1669744286,"Phase":"binded","Status":"00","i_sqn":12740},"e001":{"Target":"0000","Stamp":1669744286,"Phase":"binded","Status":"00","i_sqn":12741},"0000":{"Target":"0000","Stamp":1669744287,"Phase":"binded","Status":"00","i_sqn":12742}},"02":{"0004":{"Target":"0000","Stamp":1669744287,"Phase":"binded","Status":"00","i_sqn":12743},"0005":{"Target":"0000","Stamp":1669744287,"Phase":"binded","Status":"00","i_sqn":12744},"0006":{"Target":"0000","Stamp":1669744287,"Phase":"binded","Status":"00","i_sqn":12745},"e001":{"Target":"0000","Stamp":1669744287,"Phase":"binded","Status":"00","i_sqn":12746}},"03":{"0004":{"Target":"0000","Stamp":1669744287,"Phase":"binded","Status":"00","i_sqn":12747},"0005":{"Target":"0000","Stamp":1669744287,"Phase":"binded","Status":"00","i_sqn":12748},"0006":{"Target":"0000","Stamp":1669744288,"Phase":"binded","Status":"00","i_sqn":12749},"e001":{"Target":"0000","Stamp":1669744288,"Phase":"binded","Status":"00","i_sqn":12750}},"04":{"0004":{"Target":"0000","Stamp":1669744288,"Phase":"binded","Status":"00","i_sqn":12751},"0005":{"Target":"0000","Stamp":1669744288,"Phase":"binded","Status":"8c","i_sqn":12752},"0006":{"Target":"0000","Stamp":1669744288,"Phase":"binded","Status":"8c","i_sqn":12753},"e001":{"Target":"0000","Stamp":1669744288,"Phase":"binded","Status":"8c","i_sqn":12754}}},"ConfigureReporting":{"Ep":{"01":{"0006":{"TimeStamp":1669744286,"iSQN":{"0000":12755},"Attributes":{"0000":"00"},"ZigateRequest":{}}},"02":{"0006":{"TimeStamp":1669744286,"iSQN":{"0000":12756},"Attributes":{"0000":"00"},"ZigateRequest":{}}},"03":{"0006":{"TimeStamp":1669744286,"iSQN":{"0000":12757},"Attributes":{"0000":"00"},"ZigateRequest":{}}},"04":{"0006":{"TimeStamp":1669744286,"iSQN":{"0000":12758},"Attributes":{"0000":"00"},"ZigateRequest":{}}}}},"bitfield":"4001","descriptor_capability":"00","RoutingTable":[],"ConsistencyCheck":"ok","CheckParam":false,"RollingLQI":[53,54,55,55],"SQN_000a":"b6"}}

**Comment by pipiche38** [comment]
This device is already in the Certified database. It could be that you have paired this device prior its integration.
So simply remove it from Domoticz by removing all related widgets .
restart the plugin, check that the device do not exist in the plugin, and then re-do the pairing

**Comment by diliak** [comment]
Thank you Pipiche, it's solved !

**Comment by pipiche38** [comment]
thanks for the feedback
