### ISSUE TITLE
[Model Certification] - SENSOR TEMP and Humidity (TS0601)

### ISSUE THREAD

**Issue by oli80330** [zigbeefordomoticz/z4d-certified-devices#80]
1. Please do provide device information such as Brand and Model name.
1. Provide the URL where you have purchase the device
    * Product Name : ?
    * Brand : « _TZE204_yjjdcqsq »
    * URL on a web site : https://fr.aliexpress.com/item/4000843004202.html?spm=a2g0o.order_list.order_list_main.31.1f1f5e5bPcUGOb&gatewayAdapt=glo2fra
    
    * What do you expect : TEMP and HUMIDITY in Domoticz, item is not intergrated in Domoticz

1. Document as much what works, what doesn't work, what do you miss, what do you need

1. Got to the Tools Menu
1. Select Plugin Raw Devices (json)
1. Export

{"PluginInfos":{"HardwareID":70,"HomeFolder":"/home/pi/domoticz/plugins/Domoticz-Zigbee/","StartupFolder":"/home/pi/domoticz/","UserDataFolder":"/home/pi/domoticz/","WebRoot":"","Database":"/home/pi/domoticz/domoticz.db","Language":"fr","Version":"6.3","Author":"pipiche38","Name":"ZIGBEE","Address":"0.0.0.0","Port":"9999","SerialPort":"/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CCE0072-if00","Key":"Zigate","Mode1":"ZigpyZNP","Mode2":"USB","Mode3":"False","Mode4":"9440","Mode6":"2","DomoticzVersion":"2024.7","DomoticzHash":"b317cfab1","DomoticzBuildTime":"2024-07-13 16:59:31","PluginBranch":"stable6","PluginVersion":"6.3.015","TimeStamp":1730315972,"available":0,"available-firmMajor":0,"available-firmMinor":0,"FirmwareVersion":"Z-Stack Home 1.2 (build 20201127)","FirmwareUpdate":false,"PluginUpdate":false,"LogLevel":7,"Zigpy":true,"CoordinatorModel":"CC2531, Z-Stack Home 1.2 (znp)","CoordinatorFirmwareVersion":"Z-Stack Home 1.2 (build 20201127)","DisplayFirmwareVersion":"Znp - Z-Stack Home 1.2 (build 20201127)","CoordinatorIEEE":"00124b001cce0072","NetworkSize":"Total: 7 | Routers: 3 | End Devices: 4","NetworkDevices":{"1002":{"_TZ3000_wamqdr3f":["TS011F"]},"1141":{"_TZ3000_fllyghyj":["TS0201"],"_TZ3000_xr3htd96":["TS0201"]}}},"Analytics":1,"Device":{"Version":"3","ZDeviceName":"T1","Status":"UNKNOW","SQN":"96","Ep":{"01":{"0000":{"0004":"_TZE204_yjjdcqsq","0000":"3","0001":"73","0005":"TS0601","0007":"3","fffe":"0","ffe2":"56","ffe4":"0","ffdf":"4\u0003i7\u0003i:\u0003i=\u0003i\u0006f\u0006\u0012\u0006e"}}},"Heartbeat":"85","RIA":"7","LQI":76,"Battery":{},"Model":"TS0601","ForceAckCommands":[],"MacCapa":"80","IEEE":"a4c1385db7a01074","Type":{},"ProfileID":{},"ZDeviceID":{},"App Version":"73","Attributes List":{},"DeviceType":"RFD","HW Version":"","Last Cmds":[],"LogicalType":"End Device","Manufacturer":"","Manufacturer Name":"_TZE204_yjjdcqsq","NbEp":"1","PowerSource":"","ReadAttributes":{"Ep":{"01":{"0000":{"TimeStamp":1730315522,"iSQN":{"0004":"00","0000":"00","0001":"00","0005":"00","0007":"00","fffe":"00"},"Attributes":{"0004":"00","0000":"00","0001":"00","0005":"00","0007":"00","fffe":"00","ffe2":"00","ffe4":"00","ffdf":"00"},"ZigateRequest":{}}}}},"ReceiveOnIdle":"","Stack Version":"","Stamp":{"time":1730315965.6959426,"Time":"2024-10-30 20:19:25","MsgType":"8011","LastSeen":1730315965},"ZCL Version":"3","Health":"Live","Capability":["Reduced-Function Device","Standard security","NwkAddr should be allocated"],"ZCLSQN":"00","ZDPSQN":"01","RollingLQI":[68,68,68,68,68,63,63,55,55,76,76],"WriteAttributes":{"Ep":{"01":{"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"PairingInProgress":true,"Epv2":{"01":{"ClusterIn":{},"ClusterOut":{},"ProfileID":{},"ZDeviceID":{}}},"ZCL-IN-SQN":{"ef00":"96","0000":"9a","000a":"94"},"SQN_000a":"94","ConsistencyCheck":"Bad Pairing","Param":{},"CheckParam":true}}

# Donations and Sponsorship

We warmly invite Manufacturers and sellers to contribute by sending us samples of their devices for integration. Your support in this regard is greatly appreciated as it enables us to expand our compatibility and offer a more comprehensive solution.

We extend our heartfelt gratitude to our generous donors whose contributions enable us to acquire additional equipment for rigorous testing and seamless integration. With your support, we can further enhance the plugin's capabilities and deliver an even more powerful and versatile experience for our users.

Donate via PayPal https://paypal.me/pipiche

**Comment by pipiche38** [comment]
you are using an out-dated version of the plugin 

> "PluginBranch":"stable6","PluginVersion":"6.3.015"

Kindly update to the latest version "stable7", and this device should be supported.
