### ISSUE TITLE
[Model Certification] - IKEA - INSPELNING Smart plug

### ISSUE THREAD

**Issue by Euton2020** [zigbeefordomoticz/z4d-certified-devices#84]
Bonjour,

Nom du produit : INSPELNING Smart plug
Marque : IKEA
URL produit : https://www.ikea.com/fr/fr/p/inspelning-fiche-connecte-compteur-denergie-40569839/

{"Filename":"INSPELNING Smart plug.json","Configuration":{"_comment":"","_version":"","_blakadder":"","_source":"","Ep":{"01":{"1000":"","0000":"","0003":"","0004":"","0005":"","0006":"","0008":"","0702":"","0b04":"","fc7c":"","fc85":"","0019":"","Type":"LvlControl/Power/Meter/Power/Meter/Ampere"},"f2":{"0021":"","Type":{}}},"Type":"","ClusterToBind":["fc7c","0004","0000","0005","1000","0006","0008","fc85","0b04","0003","0702"],"ConfigureReporting":{"0006":{"0000":{"Change":{},"DataType":"10","MaxInterval":"012c","MinInterval":"0001","TimeOut":"0000"}},"0008":{"0000":{"Change":"05","DataType":"20","MaxInterval":"012c","MinInterval":"0005","TimeOut":"0000"}},"0b04":{"0505":{"Change":"0001","DataType":"21","MaxInterval":"012c","MinInterval":"0001","TimeOut":"0000"},"0508":{"Change":"0001","DataType":"21","MaxInterval":"012c","MinInterval":"0001","TimeOut":"0000"},"050b":{"Change":"0001","DataType":"29","MaxInterval":"012c","MinInterval":"0005","TimeOut":"0000"}},"0702":{"0400":{"Change":{},"DataType":{},"MaxInterval":{},"MinInterval":{},"TimeOut":"0000"}}},"ReadAttributes":{"0019":[],"0702":["0300","0302","0301","0000","0200","0303","0306","fffd"],"0006":["4000","4001","4002","4003","fffd","0000"],"0008":["0000"],"0000":["0000","0001","0002","0003","0004","0005","0006","0007","0008","0009","000a","000b","4000","fffd"],"0b04":["0505","0508","050b","0600","0601","0602","0603","0604","0605","fffd","0000"]},"Param":{},"GroupMembership":{}},"rawInfos":{"Version":"3","ZDeviceName":"","Status":"inDB","SQN":"4f","Ep":{"01":{"1000":{},"0000":{"4000":"2.4.34","0004":"IKEA of Sweden","0005":"INSPELNING Smart plug","0000":8,"0001":2,"0002":114,"0003":1,"0006":"20240215","0007":1,"0008":0,"0009":5,"000a":"E2222","000b":"www.ikea.com","fffd":3},"0003":{},"0004":{},"0005":{},"0006":{"4000":"01","4001":0,"4002":0,"4003":255,"0000":"01","fffd":2},"0008":{"0000":254},"0702":{"0000":0,"0200":"Ok","0300":"kW","0301":1,"0302":1000,"0303":251,"0306":0,"fffd":2},"0b04":{"0505":23.7,"0000":"00000009","0508":0.033,"050b":0,"0600":1,"0601":10,"0602":1,"0603":1000,"0604":1,"0605":10,"fffd":3},"fc7c":{},"fc85":{"0000":"00","0001":"01"},"0019":{},"ClusterType":{"217":"LvlControl","218":"Power","219":"Meter","220":"Power","221":"Meter","222":"Ampere"}},"f2":{"0021":{}}},"Heartbeat":"5356","RIA":"4","LQI":220,"Battery":{},"Model":"INSPELNING Smart plug","ForceAckCommands":[],"MacCapa":"8e","IEEE":"8c65a3fffe1055cf","Type":"Switch/LvlControl/Power/Meter/Ampere","ProfileID":"a1e0","ZDeviceID":"0061","App Version":2,"Attributes List":{"Ep":{"01":{"1000":{"fffd":"21"},"0000":{"4000":"42","0000":"20","0001":"20","0002":"20","0003":"20","0004":"42","0005":"42","0006":"42","0007":"30","0008":"30","0009":"30","000a":"41","000b":"42","fffd":"21"},"0003":{"0000":"21","fffd":"21"},"0004":{"0000":"18","fffd":"21"},"0005":{"0000":"20","0001":"20","0002":"21","0003":"10","0004":"18","fffd":"21"},"0006":{"4000":"10","4001":"21","4002":"21","4003":"30","0000":"10","fffd":"21"},"0008":{"4000":"20","0000":"20","0001":"21","000f":"18","0010":"21","0011":"20","fffd":"21"},"0702":{"0000":"25","0200":"18","0300":"30","0301":"22","0302":"22","0303":"18","0306":"18","fffd":"21"},"0b04":{"0000":"1b","0505":"21","0508":"21","050b":"29","0600":"21","0601":"21","0602":"21","0603":"21","0604":"21","0605":"21","fffd":"21"},"fc7c":{},"fc85":{},"0019":{}}}},"DeviceType":"FFD","HW Version":1,"Last Cmds":[],"LogicalType":"Router","Manufacturer":"117c","Manufacturer Name":"IKEA of Sweden","NbEp":"2","PowerSource":"Main","ReadAttributes":{"Ep":{"01":{"0019":{"TimeStamp":1732281698,"iSQN":{"0000":"5e","0001":"5e","0002":"5e","0003":"5f","0004":"5f","0005":"5f","0006":"60","0007":"60","0008":"60","0009":"61","000a":"61","fffd":"61","fffe":"62"},"Attributes":{"0000":"86","0001":"86","0003":"86","0004":"86","0006":"86","0007":"86","0009":"86","000a":"86","fffe":"86"},"ZigateRequest":{}},"0702":{"TimeStamp":1732347205,"iSQN":{"0000":"63","0001":"63","0002":"63","0003":"64","0004":"64","0005":"64","0006":"65","0007":"65","0008":"65","0009":"66","000a":"66","000b":"66","000c":"67","000d":"67","000e":"67","000f":"68","0010":"68","0011":"68","0012":"69","0013":"69","0014":"69","0015":"6a","0016":"6a","0017":"6a","0018":"6b","0019":"6b","001a":"6b","001b":"6c","001c":"6c","001d":"6c","001e":"6d","001f":"6d","0020":"6d","0021":"6e","0022":"6e","0100":"6e","0101":"6f","0102":"6f","0103":"6f","0104":"70","0105":"70","0106":"70","0107":"71","0108":"71","0109":"71","010a":"72","010b":"72","010c":"72","010d":"73","010e":"73","010f":"73","0110":"74","0111":"74","0112":"74","0113":"75","0114":"75","0115":"75","0116":"76","0117":"76","0118":"76","0119":"77","011a":"77","011b":"77","011c":"78","011d":"78","011e":"78","011f":"79","0200":"79","0300":"79","0301":"7a","0302":"7a","0303":"7a","0304":"7b","0305":"7b","0306":"7b","0307":"7c","0308":"7c","0400":"7c","0430":"7d","0800":"7d","0801":"7d","fffd":"7e","fffe":"7e"},"Attributes":{"0300":"00","0302":"00","0301":"00","0000":"00","0001":"86","0003":"86","0004":"86","0006":"86","0007":"86","0009":"86","000a":"86","000c":"86","000d":"86","000f":"86","0010":"86","0012":"86","0013":"86","0015":"86","0016":"86","0018":"86","0019":"86","001b":"86","001c":"86","001e":"86","001f":"86","0021":"86","0022":"86","0101":"86","0102":"86","0104":"86","0105":"86","0107":"86","0108":"86","010a":"86","010b":"86","010d":"86","010e":"86","0110":"86","0111":"86","0113":"86","0114":"86","0116":"86","0117":"86","0119":"86","011a":"86","011c":"86","011d":"86","011f":"86","0200":"00","0303":"00","0304":"86","0305":"86","0306":"00","0307":"86","0308":"86","0430":"86","0800":"86","fffd":"00","fffe":"86"},"ZigateRequest":{}},"0006":{"TimeStamp":1732368201,"iSQN":{"4000":"7f","4001":"7f","4002":"80","4003":"80","fffd":"80","fffe":"81","0000":"04"},"Attributes":{"4000":"00","4001":"00","4002":"00","4003":"00","fffd":"00","fffe":"86","0000":"00"},"ZigateRequest":{}},"0008":{"TimeStamp":1732368295,"iSQN":{"0000":"05"},"Attributes":{"0000":"00"},"ZigateRequest":{}},"0000":{"TimeStamp":1732316521,"iSQN":{"4000":"8a","8000":"8a","0000":"83","0001":"83","0002":"83","0003":"84","0004":"84","0005":"84","0006":"85","0007":"85","0008":"85","0009":"86","000a":"86","000b":"86","000c":"87","000d":"87","000e":"87","0010":"88","0011":"88","0012":"88","0013":"89","0014":"89","0015":"89","fffd":"8a","fffe":"8b","ffdf":"8b","ffe0":"8b","ffe1":"8c","ffe2":"8c","ffe4":"8c"},"Attributes":{"4000":"00","8000":"86","0000":"00","0001":"00","0002":"00","0003":"00","0004":"00","0005":"00","0006":"00","0007":"00","0008":"00","0009":"00","000a":"00","000b":"00","000c":"86","000d":"86","0010":"86","0011":"86","0013":"86","0014":"86","fffd":"00","fffe":"86","ffdf":"86","ffe1":"86","ffe2":"86"},"ZigateRequest":{}},"0b04":{"TimeStamp":1732368400,"iSQN":{"0000":"8d","0300":"8d","0301":"8d","0302":"8e","0303":"8e","0304":"8e","0305":"8f","0306":"8f","0307":"8f","0308":"90","0309":"90","030a":"90","030b":"91","030c":"91","030d":"91","030e":"92","030f":"92","0310":"92","0311":"93","0312":"93","0400":"93","0401":"94","0402":"94","0403":"94","0404":"95","0405":"95","0501":"95","0502":"96","0503":"96","0505":"96","0506":"97","0507":"97","0508":"97","0509":"98","050a":"98","050b":"98","050c":"99","050d":"99","050e":"99","050f":"9a","0510":"9a","0511":"9a","0512":"9b","0513":"9b","0514":"9b","0515":"9c","0516":"9c","0517":"9c","0600":"9d","0601":"9d","0602":"9d","0603":"9e","0604":"9e","0605":"9e","fffd":"9f","fffe":"9f"},"Attributes":{"0302":"86","0303":"86","0305":"86","0306":"86","0308":"86","0309":"86","030b":"86","030c":"86","030e":"86","030f":"86","0311":"86","0312":"86","0401":"86","0402":"86","0404":"86","0405":"86","0502":"86","0503":"86","0505":"00","0506":"86","0507":"86","0508":"00","0509":"86","050a":"86","050b":"00","050c":"86","050d":"86","050f":"86","0510":"86","0512":"86","0513":"86","0515":"86","0516":"86","0600":"00","0601":"00","0602":"00","0603":"00","0604":"00","0605":"00","fffd":"00","fffe":"86","0000":"00","0300":"86"},"ZigateRequest":{}}}}},"ReceiveOnIdle":"On","Stack Version":114,"Stamp":{"time":1732368400.2364628,"Time":"2024-11-23 14:26:40","MsgType":"8102","LastSeen":1732368352},"ZCL Version":8,"Health":"Live","_rawNodeDescriptor":"117c005200522c00008e524001","CertifiedDevice":false,"bitfield":"4001","Max Tx":"0052","descriptor_capability":"00","RSSI":-46,"Capability":["Full-Function Device","Main Powered","Receiver during Idle","Standard security","NwkAddr should be allocated"],"Max Buffer Size":"52","WriteAttributes":{"Ep":{"01":{"1000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0003":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0004":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0005":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0008":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0702":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0b04":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"fc7c":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"fc85":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0019":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}},"f2":{"0021":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"ConfigSource":"8043","Bind":{"01":{"1000":{"Target":"0000","Stamp":1732281696,"Phase":"binded","Status":"00","i_sqn":"1c"},"0000":{"Target":"0000","Stamp":1732281695,"Phase":"binded","Status":"00","i_sqn":"14"},"0003":{"Target":"0000","Stamp":1732281695,"Phase":"binded","Status":"00","i_sqn":"15"},"0004":{"Target":"0000","Stamp":1732281696,"Phase":"binded","Status":"00","i_sqn":"16"},"0005":{"Target":"0000","Stamp":1732281696,"Phase":"binded","Status":"00","i_sqn":"17"},"0006":{"Target":"0000","Stamp":1732281696,"Phase":"binded","Status":"00","i_sqn":"18"},"0008":{"Target":"0000","Stamp":1732281696,"Phase":"binded","Status":"00","i_sqn":"19"},"0702":{"Target":"0000","Stamp":1732281696,"Phase":"binded","Status":"00","i_sqn":"1a"},"0b04":{"Target":"0000","Stamp":1732281696,"Phase":"binded","Status":"00","i_sqn":"1b"},"fc7c":{"Target":"0000","Stamp":1732281696,"Phase":"binded","Status":"00","i_sqn":"1d"},"fc85":{"Target":"0000","Stamp":1732281697,"Phase":"binded","Status":"00","i_sqn":"1e"}},"f2":{"0021":{"Target":"0000","Stamp":1732281697,"Phase":"binded","Status":"82","i_sqn":"1f"}}},"ConfigureReporting":{"Ep":{"01":{"0006":{"TimeStamp":1732281683.7128317,"iSQN":{"0000":"5a"},"Attributes":{"0000":"00"},"ZigateRequest":{}},"0008":{"TimeStamp":1732281683.71468,"iSQN":{"0000":"5b"},"Attributes":{"0000":"00"},"ZigateRequest":{}},"0702":{"TimeStamp":1732281683.7162364,"iSQN":{"0000":"5c","0400":"5c"},"Attributes":{"0400":"86"},"ZigateRequest":{}},"0b04":{"TimeStamp":1732281683.7183828,"iSQN":{"0505":"5d","0508":"5d","050b":"5d"},"Attributes":{"0505":"00","0508":"00","050b":"00"},"ZigateRequest":{}}}}},"ReadConfigureReporting":{"Ep":{"01":{"0006":{"0000":{"TimeStamp":1732281920.7640572,"Status":"00","DataType":"10","MinInterval":"0001","MaxInterval":"012c"}},"0008":{"0000":{"TimeStamp":1732281920.889067,"Status":"00","DataType":"20","MinInterval":"0005","MaxInterval":"012c","Change":"05"}},"0b04":{"0505":{"TimeStamp":1732281921.1478758,"Status":"00","DataType":"21","MinInterval":"0001","MaxInterval":"012c","Change":"0001"},"0508":{"TimeStamp":1732281921.1482432,"Status":"00","DataType":"21","MinInterval":"0001","MaxInterval":"012c","Change":"0001"},"050b":{"TimeStamp":1732281921.1485107,"Status":"00","DataType":"29","MinInterval":"0005","MaxInterval":"012c","Change":"0001"}},"0702":{"0400":{"TimeStamp":1732281921.0062702,"Status":"86"}}}},"TimeStamp":1732281921.148498},"SWBUILD_1":"20240215","macapa":"8e","Log_UnknowDeviceFlag":1732316537.0711312,"OTAClient":{"ManufacturerCode":"117c","ImageType":"9f3e","CurrentImageVersion":"02040034"},"Max Rx":"0052","BindingTable":{"SQN":0,"Status":"Success","TimeStamp":1732281721.8537729,"BindingTableSize":11,"Devices":[{"8c65a3fffe1055cf":{"sourceEp":"01","Cluster":"0000","targetIEEE":"e0798dfffe9cbb6a","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"8c65a3fffe1055cf":{"sourceEp":"01","Cluster":"0003","targetIEEE":"e0798dfffe9cbb6a","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"8c65a3fffe1055cf":{"sourceEp":"01","Cluster":"0004","targetIEEE":"e0798dfffe9cbb6a","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"8c65a3fffe1055cf":{"sourceEp":"01","Cluster":"0005","targetIEEE":"e0798dfffe9cbb6a","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"8c65a3fffe1055cf":{"sourceEp":"01","Cluster":"0006","targetIEEE":"e0798dfffe9cbb6a","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"8c65a3fffe1055cf":{"sourceEp":"01","Cluster":"0008","targetIEEE":"e0798dfffe9cbb6a","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"8c65a3fffe1055cf":{"sourceEp":"01","Cluster":"0702","targetIEEE":"e0798dfffe9cbb6a","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"8c65a3fffe1055cf":{"sourceEp":"01","Cluster":"0b04","targetIEEE":"e0798dfffe9cbb6a","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"8c65a3fffe1055cf":{"sourceEp":"01","Cluster":"1000","targetIEEE":"e0798dfffe9cbb6a","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"8c65a3fffe1055cf":{"sourceEp":"01","Cluster":"fc7c","targetIEEE":"e0798dfffe9cbb6a","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"8c65a3fffe1055cf":{"sourceEp":"01","Cluster":"fc85","targetIEEE":"e0798dfffe9cbb6a","targetNickName":"Zigbee Coordinator","targetEp":"01"}}]},"server_mask":"2c00","Epv2":{"01":{"ProfileID":"0104","ZDeviceID":"010a","ClusterIn":{"1000":{},"0000":{},"0003":{},"0004":{},"0005":{},"0006":{},"0008":{},"0702":{},"0b04":{},"fc7c":{},"fc85":{}},"ClusterOut":{"0019":{}}},"f2":{"ProfileID":"a1e0","ZDeviceID":"0061","ClusterIn":{"0021":{}},"ClusterOut":{"0021":{}}}},"ConsistencyCheck":"ok","ErrorManagement":0,"RollingLQI":[220,216,216,216,216,220,216,216,216,216,220],"ZDeviceVersion":"0001","ReqEpv2":{},"RollingRSSI":[-45,-46,-46,-46,-46,-45,-46,-46,-46,-46],"ZCL-IN-SQN":{"0000":"05","0006":"04","0008":"05","0019":"10"},"ZCLSQN":"05","RoutingTable":[{"SQN":0,"Status":"Success","TimeStamp":1732359727,"Time":1732359726,"RoutingTableTableSize":16,"Devices":[{"0000":{"Status":"Active (0)","MemoryConstrained":1,"ManyToOne":1,"RouteRecordRequired":0,"NextHopNwkId":"0000"}}]}],"ZDPSQN":"01"}}

**Comment by pipiche38** [comment]
can you update to 5.336 (certified Db). You need to redo the pairing from scratch, so remove all widgets created in domoticz for that device, then check that the device do not remain in the plugin, and redo the pairing

**Comment by Euton2020** [comment]
Good morning,

I'm having problems updating my database.
I'm looking for

**Comment by pipiche38** [comment]
`sudo python3 -m pip install z4d-certified-devices --upgrade`

**Comment by Euton2020** [comment]
done with `--break-system-packages` and ti's ok

**Comment by pipiche38** [comment]
I don't see why should need `--break-system-packages`, but I guess you managed it.

**Comment by Euton2020** [comment]
re Hello,
the object is well optimized but no variation in value is reflected in the Devices.
for `--break-system-packages` it's for `"Raspbian GNU/Linux 12"`

**Comment by pipiche38** [comment]
please enabled debugs as shown here and put some power on the plug after a while pleas eprovide the log here
![Screenshot 2024-11-23 at 17 02 27](https://github.com/user-attachments/assets/770012ad-3f05-4d7b-ae03-e70561f386e6)

you can also contact us on https://keybase.io/team/zigate fpor instant messanging in French

**Comment by pipiche38** [comment]
Should need the Plugin 7.1.015, and then do a firmware update and get at least '02040045'.

This version has been tested and provided the right firmware
https://github.com/Koenkk/zigbee-OTA/raw/master/images/IKEA/inspelning-smart-plug-soc_release_prod_v33816645_02579ff4-6fec-42f6-8957-4048def87def.ota

**Comment by Euton2020** [comment]
ok for updating the socket in 17 mins and 17 secs with firmware 33816645

**Comment by pipiche38** [comment]
All good in Plugin 7.1.015 and [5.348]

Thanks for your support and patience
