### ISSUE TITLE
[Model Certification] - Aqara WXKG17LM

### ISSUE THREAD

**Issue by ptilib** [zigbeefordomoticz/z4d-certified-devices#85]
1. Please do provide device information such as Brand and Model name.
1. Provide the URL where you have purchase the device
    * Product Name: Aqara WXKG17LM - Wireless remote switch E1 (double rocker)
    * Brand Aqara
    * URL on a web site: 
    https://zigbee.blakadder.com/Aqara_WXKG17LM.html
    https://www.zigbee2mqtt.io/devices/WXKG17LM.html
    https://fr.aliexpress.com/item/1005004384069042.html
    * What do you expect: Double rockers to work. Possibility to change from click mode fast / multi

1. Document as much what works, what doesn't work, what do you miss, what do you need

1. Got to the Tools Menu
1. Select Plugin Raw Devices (json)
1. Export

This will create an export.json file that you can save.
Filename: "lumi.remote.acn004.json"
Configuration: Object {"_comment":"","_version":"","_blakadder":"","_source":"","Ep":{"01":{"0000":"","0001":"","0003":"","0012":"","fcc0":"","0006":"","0019":"","Type":"Voltage/Switch"},"02":{"0012":"","0006":"","Type":"Switch"},"03":{"0012":"","0006":"","Type":"Switch"}},"Type":"","ClusterToBind":["0000","0001"],"ConfigureReporting":{},"ReadAttributes":{"0000":["0000","0001","0002","0003","0004","0005","0007","000d","0012","fffd"],"0001":["0020","fffd"],"0019":["0000","0001","0002","0003","0004","0005","0006","0007","0008","0009","fffd"],"0006":[],"fcc0":["00f7"],"0012":["0055"]},"Param":{},"GroupMembership":{}}
rawInfos: Object {"Version":"3","ZDeviceName":"","Status":"inDB","SQN":"7d","Ep":{"01":{"0000":{"0001":9,"0005":"lumi.remote.acn004","0004":"LUMI","0000":3,"0002":2,"0003":0,"0007":3,"000d":"880/00089651","0012":"01","fffd":1},"0001":{"0020":29,"fffd":1},"0003":{},"0012":{"0055":"0001"},"fcc0":{"00f7":"\u0001!h\u000b\u0003(\u0019\u0004!\u0000\u0000\u0005!\u0001\u0000\b!\t\u0000\n!\u0000\u0000\f \u001ed \u0001"},"0006":{},"0019":{"0000":"00212effff04ec0b","0001":4294967295,"0002":9,"0003":2,"0004":4294967295,"0005":65535,"0006":0,"0007":4447,"0008":65535,"0009":0,"fffd":1},"ClusterType":{"257":"Voltage","258":"Switch"}},"02":{"0012":{"0055":"0001"},"0006":{},"ClusterType":{"259":"Switch"}},"03":{"0012":{},"0006":{},"ClusterType":{"260":"Switch"}}},"Heartbeat":"402","RIA":"4","LQI":255,"Battery":{},"Model":"lumi.remote.acn004","ForceAckCommands":[],"MacCapa":"80","IEEE":"54ef441000dc39a3","Type":"Voltage/Switch","ProfileID":"0104","ZDeviceID":"0000","App Version":9,"Attributes List":{"Ep":{"01":{"0000":{"0000":"20","0001":"20","0002":"20","0003":"20","0004":"42","0005":"42","0007":"30","000d":"42","0012":"10","fffd":"21"},"0001":{"0020":"20","fffd":"21"},"0003":{"0000":"21","fffd":"21"},"0012":{"0055":"21","fffd":"21"},"fcc0":{"0001":"21","0002":"21","0003":"30","0004":"21","0005":"20","0006":"41","0007":"41","0008":"41","0009":"20","00f6":"21","00f7":"41","00fa":"10","00fc":"10","00fe":"41","00ff":"41","0125":"20","0135":"20","0136":"21","0800":"20","0801":"41","0802":"41","fffd":"21"},"0019":{"0000":"f0","0001":"23","0002":"23","0003":"21","0004":"23","0005":"21","0006":"30","0007":"21","0008":"21","0009":"21","fffd":"21"}},"02":{"0012":{"0055":"21","fffd":"21"}},"03":{"0012":{"0055":"21","fffd":"21"}}}},"DeviceType":"RFD","HW Version":0,"Last Cmds":[],"LogicalType":"End Device","Manufacturer":"115f","Manufacturer Name":"LUMI","NbEp":"3","PowerSource":"Battery","ReadAttributes":{"Ep":{"01":{"0000":{"TimeStamp":"24/11/2024 20:53:01","iSQN":{"4000":"22","8000":"22","0000":"1b","0001":"1b","0002":"1b","0003":"1c","0004":"1c","0005":"1c","0006":"1d","0007":"1d","0008":"1d","0009":"1e","000a":"1e","000b":"1e","000c":"1f","000d":"1f","000e":"1f","0010":"20","0011":"20","0012":"20","0013":"21","0014":"21","0015":"21","fffd":"22","fffe":"23","ffdf":"23","ffe0":"23","ffe1":"24","ffe2":"24","ffe4":"24","ff01":"25","ff02":"25"},"Attributes":{"4000":"86","8000":"86","0000":"00","0001":"00","0002":"00","0003":"00","0004":"00","0005":"00","0006":"86","0007":"00","0008":"86","0009":"86","000a":"86","000c":"86","000d":"00","000e":"86","0010":"86","0011":"86","0012":"00","0013":"86","0014":"86","fffd":"00","fffe":"86","ffdf":"86","ffe1":"86","ffe2":"86","ff01":"86"},"ZigateRequest":{}},"0001":{"TimeStamp":"24/11/2024 20:52:36","iSQN":{"0000":"04","0001":"04","0010":"04","0011":"05","0012":"05","0013":"05","0020":"06","0021":"06","0030":"06","0031":"07","0032":"07","0033":"07","0034":"08","0035":"08","0036":"08","0037":"09","0038":"09","0039":"09","003a":"0a","003b":"0a","003c":"0a","003d":"0b","003e":"0b","fffd":"0b","fffe":"0c"},"Attributes":{"0000":"86","0001":"86","0011":"86","0012":"86","0020":"00","0021":"86","0031":"86","0032":"86","0034":"86","0035":"86","0037":"86","0038":"86","003a":"86","003b":"86","003d":"86","003e":"86","fffd":"00","fffe":"86"},"ZigateRequest":{}},"0019":{"TimeStamp":"24/11/2024 20:52:41","iSQN":{"0000":"0d","0001":"0d","0002":"0d","0003":"0e","0004":"0e","0005":"0e","0006":"0f","0007":"0f","0008":"0f","0009":"10","000a":"10","fffd":"10","fffe":"11"},"Attributes":{"0000":"00","0001":"00","0002":"00","0003":"00","0004":"00","0005":"00","0006":"00","0007":"00","0008":"00","0009":"00","000a":"86","fffd":"00","fffe":"86"},"ZigateRequest":{}},"0006":{"TimeStamp":"24/11/2024 20:52:16","iSQN":{"4000":"12","4001":"12","4002":"13","4003":"13","0000":"12","fffd":"13","fffe":"14"},"Attributes":{},"ZigateRequest":{}},"fcc0":{"TimeStamp":"24/11/2024 20:52:19","iSQN":{},"Attributes":{"00f7":"00"},"ZigateRequest":{}},"0012":{"TimeStamp":"24/11/2024 21:08:37","iSQN":{},"Attributes":{"0055":"00"},"ZigateRequest":{}}},"02":{"0006":{"TimeStamp":"24/11/2024 20:52:16","iSQN":{"4000":"15","4001":"15","4002":"16","4003":"16","0000":"15","fffd":"16","fffe":"17"},"Attributes":{},"ZigateRequest":{}},"0012":{"TimeStamp":"24/11/2024 21:08:36","iSQN":{},"Attributes":{"0055":"00"},"ZigateRequest":{}}},"03":{"0006":{"TimeStamp":"24/11/2024 20:52:16","iSQN":{"4000":"18","4001":"18","4002":"19","4003":"19","0000":"18","fffd":"19","fffe":"1a"},"Attributes":{},"ZigateRequest":{}}}}},"ReceiveOnIdle":"Off","Stack Version":2,"Stamp":{"time":1732478917.1639903,"Time":"2024-11-24 21:08:37","MsgType":"8102","LastSeen":"24/11/2024 21:08:34"},"ZCL Version":3,"Health":"Live","Capability":["Reduced-Function Device","Standard security","NwkAddr should be allocated"],"ZDPSQN":"0d","ErrorManagement":0,"RSSI":-45,"RollingRSSI":[-40,-40,-40,-40,-40,-40,-41,-42,-44,-45],"RollingLQI":[255,255,255,255,255,255,255,255,255,255,255],"WriteAttributes":{"Ep":{"01":{"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0001":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0003":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0012":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"fcc0":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0019":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}},"02":{"0012":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}},"03":{"0012":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"_rawNodeDescriptor":"115f004200422a000080424002","Max Buffer Size":"42","Max Rx":"0042","Max Tx":"0042","macapa":"80","bitfield":"4002","server_mask":"2a00","descriptor_capability":"00","PairingInProgress":false,"Epv2":{"01":{"ProfileID":"0104","ZDeviceID":"0000","ClusterIn":{"0000":{},"0001":{},"0003":{},"0012":{},"fcc0":{}},"ClusterOut":{"0003":{},"0006":{},"0019":{}}},"02":{"ProfileID":"0104","ZDeviceID":"0000","ClusterIn":{"0012":{}},"ClusterOut":{"0006":{}}},"03":{"ProfileID":"0104","ZDeviceID":"0000","ClusterIn":{"0012":{}},"ClusterOut":{"0006":{}}}},"ZDeviceVersion":"0000","ConfigSource":"8043","PairingTime":1732477936.1052954,"Bind":{"01":{"0000":{"Target":"0000","Stamp":"24/11/2024 20:52:17","Phase":"binded","Status":"00","i_sqn":"05"},"0001":{"Target":"0000","Stamp":"24/11/2024 20:52:17","Phase":"binded","Status":"00","i_sqn":"06"},"0003":{"Target":"0000","Stamp":"24/11/2024 20:52:19","Phase":"binded","Status":"8c","i_sqn":"07"},"0012":{"Target":"0000","Stamp":"24/11/2024 20:52:19","Phase":"binded","Status":"8c","i_sqn":"08"},"fcc0":{"Target":"0000","Stamp":"24/11/2024 20:52:21","Phase":"binded","Status":"8c","i_sqn":"09"}},"02":{"0012":{"Target":"0000","Stamp":"24/11/2024 20:52:22","Phase":"binded","Status":"8c","i_sqn":"0a"}},"03":{"0012":{"Target":"0000","Stamp":"24/11/2024 20:52:23","Phase":"binded","Status":"8c","i_sqn":"0b"}}},"BindingTable":{"SQN":0,"Status":"Success","TimeStamp":"24/11/2024 20:52:24","BindingTableSize":2,"Devices":[{"54ef441000dc39a3":{"sourceEp":"01","Cluster":"0000","targetIEEE":"00212effff04ec0b","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"54ef441000dc39a3":{"sourceEp":"01","Cluster":"0001","targetIEEE":"00212effff04ec0b","targetNickName":"Zigbee Coordinator","targetEp":"01"}}]},"ConfigureReporting":{"Ep":{"01":{"0001":{"TimeStamp":"24/11/2024 20:52:16","iSQN":{"0000":"00","0020":"00","0021":"00"},"Attributes":{"0000":"86","0020":"8d","0021":"86"},"ZigateRequest":{}},"0006":{"TimeStamp":"24/11/2024 20:52:16","iSQN":{"0000":"01"},"Attributes":{},"ZigateRequest":{}}},"02":{"0006":{"TimeStamp":"24/11/2024 20:52:16","iSQN":{"0000":"02"},"Attributes":{},"ZigateRequest":{}}},"03":{"0006":{"TimeStamp":"24/11/2024 20:52:16","iSQN":{"0000":"03"},"Attributes":{},"ZigateRequest":{}}}}},"ZCLSQN":"31","CertifiedDevice":false}

# Donations and Sponsorship

We warmly invite Manufacturers and sellers to contribute by sending us samples of their devices for integration. Your support in this regard is greatly appreciated as it enables us to expand our compatibility and offer a more comprehensive solution.

We extend our heartfelt gratitude to our generous donors whose contributions enable us to acquire additional equipment for rigorous testing and seamless integration. With your support, we can further enhance the plugin's capabilities and deliver an even more powerful and versatile experience for our users.

Donate via PayPal https://paypal.me/pipiche

**Comment by pipiche38** [comment]
Kindly update the plugin to latest version 7.1.014 and 5.345
you need to redo the pairing from scratch, so please remove the Switch widgets created during the previous pairing. Make sure the device is not known in the plugin (check via the WebUI > Device Management)

**Comment by ptilib** [comment]
Hello,

Thank you @pipiche38 for the very quick reply.

I have removed the device.
Updated to 7.1.014 and 5.345.
I added the device again.
I can see that it is tagged as "Optimized".
I can see the widget created in Domoticz.

But at this stage, pressing the buttons on the switch (there are 2) is not reported in Domoticz and actions assigned to the widget in Domoticz are not executed.

I also see that 3 clusters are generated but it's a 2 buttons switch so I'm a bit puzzled there too - but I'm very new to Zigbee.

Here is the JSON copied when I click on the optimized green icon:
{"Filename":"lumi.remote.acn004.json","Configuration":{"_comment":"","_version":"","_blakadder":"","_source":"","Ep":{"01":{"0000":"","0001":"","0003":"","000a":"","0006":"","fcc0":"","0012":"","Type":"DButton_3"},"02":{"0012":"","0006":"","Type":{}},"03":{"0012":"","0006":"","Type":{}}},"Type":"","ClusterToBind":[],"ConfigureReporting":{},"ReadAttributes":{"0000":["0001","0002","0003","0004","0005","0007"],"0001":["0020"],"fcc0":["00f7"],"0012":["0055"]},"Param":{},"GroupMembership":{}},"rawInfos":{"Version":"3","ZDeviceName":"Aqara","Status":"inDB","SQN":"88","Ep":{"01":{"0000":{"0001":9,"0002":2,"0003":0,"0004":"LUMI","0005":"lumi.remote.acn004","0007":3},"0001":{"0020":28},"0003":{},"000a":{},"0006":{},"fcc0":{"00f7":"\u0001!f\u000b\u0003(\u0019\u0004!\u0000\u0000\u0005!\u0001\u0000\b!\t\u0000\n!\u0000\u0000\f \u001ed \u0002"},"Type":"DButton_3","ClusterType":{"255":"DButton_3"},"0012":{"0055":"0001"}},"02":{"0012":{"0055":"0001"},"0006":{},"Type":""},"03":{"0012":{"0055":"0001"},"0006":{},"Type":""}},"Heartbeat":"62","RIA":"0","LQI":255,"Battery":60,"Model":"lumi.remote.acn004","ForceAckCommands":[],"MacCapa":"80","IEEE":"54ef441000dc39a3","Type":"DButton_3","ProfileID":"0104","ZDeviceID":"0000","App Version":9,"Attributes List":{},"DeviceType":"RFD","HW Version":0,"Last Cmds":[],"LogicalType":"End Device","Manufacturer":"115f","Manufacturer Name":"LUMI","NbEp":"3","PowerSource":"Battery","ReadAttributes":{"Ep":{"01":{"0000":{"TimeStamp":1732549771,"iSQN":{"0001":"01","0002":"01","0003":"01","0004":"02","0005":"02","0006":"02","0007":"03","000a":"03","ff01":"03","ff02":"04"},"Attributes":{"0001":"00","0002":"00","0003":"00","0004":"00","0005":"00","0006":"86","0007":"00","000a":"86","ff02":"86"},"ZigateRequest":{}},"0001":{"TimeStamp":1732549766,"iSQN":{"0020":"00"},"Attributes":{"0020":"00"},"ZigateRequest":{}},"fcc0":{"TimeStamp":1732549780,"iSQN":{},"Attributes":{"00f7":"00"},"ZigateRequest":{}},"0012":{"TimeStamp":1732550014,"iSQN":{},"Attributes":{"0055":"00"},"ZigateRequest":{}}},"02":{"0012":{"TimeStamp":1732550010,"iSQN":{},"Attributes":{"0055":"00"},"ZigateRequest":{}}},"03":{"0012":{"TimeStamp":1732549899,"iSQN":{},"Attributes":{"0055":"00"},"ZigateRequest":{}}}}},"ReceiveOnIdle":"Off","Stack Version":2,"Stamp":{"time":1732550014.7000613,"Time":"2024-11-25 16:53:34","MsgType":"8102","LastSeen":1732550002},"ZCL Version":"","Health":"Live","Capability":["Reduced-Function Device","Standard security","NwkAddr should be allocated"],"ZDPSQN":"11","ErrorManagement":0,"RSSI":-48,"RollingRSSI":[-46,-46,-48,-49,-49,-48,-46,-48,-46,-48],"RollingLQI":[255,255,255,255,255,255,255,255,255,255,255],"ConfigSource":"DeviceConf","Param":{"Disabled":0,"BindingTableRequest":0,"AqaraOppleMode":1,"AqaraMultiClick":1},"WriteAttributes":{"Ep":{"01":{"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0001":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0003":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"000a":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"fcc0":{"TimeStamp":1732549978,"iSQN":{"0125":"0b","0009":"0a"},"Attributes":{"0125":"00","0009":"00"},"ZigateRequest":{"0125":{"Status":"requested","DataType":"20","EPin":"01","EPout":"01","manuf_id":"115f","manuf_spec":"01","data":"01","ackIsDisabled":false},"0009":{"Status":"requested","DataType":"20","EPin":"01","EPout":"01","manuf_id":"115f","manuf_spec":"01","data":"01","ackIsDisabled":false}}},"0012":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}},"02":{"0012":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}},"03":{"0012":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"_rawNodeDescriptor":"115f004200422a000080424002","Max Buffer Size":"42","Max Rx":"0042","Max Tx":"0042","macapa":"80","bitfield":"4002","server_mask":"2a00","descriptor_capability":"00","Epv2":{"01":{"ProfileID":"0104","ZDeviceID":"0000","ClusterIn":{"0000":{},"0001":{},"0003":{},"0012":{},"fcc0":{}},"ClusterOut":{"0003":{},"0006":{},"0019":{}}},"02":{"ProfileID":"0104","ZDeviceID":"0000","ClusterIn":{"0012":{}},"ClusterOut":{"0006":{}}},"03":{"ProfileID":"0104","ZDeviceID":"0000","ClusterIn":{"0012":{}},"ClusterOut":{"0006":{}}}},"PairingInProgress":false,"PairingTime":1732549763.0996957,"ZCLSQN":"0b","CheckParam":false,"CertifiedDevice":true,"ZDeviceVersion":"0000","ReqEpv2":{"02":1732549764.9750152,"03":1732549765.9725316},"BatteryUpdateTime":1732549767,"BatteryVoltage_TimeStamp":1732549767.002979,"WebBind":{"02":{"0006":{"83a8":{"SourceIEEE":"54ef441000dc39a3","Target":"83a8","TargetIEEE":"70b3d52b600eed6c","TargetEp":"01","Stamp":1732550014,"Phase":"requested","i_sqn":"10","Status":""}}},"03":{"0006":{"2ae7":{"SourceIEEE":"54ef441000dc39a3","Target":"2ae7","TargetIEEE":"70b3d52b600eecba","TargetEp":"01","Stamp":1732550014,"Phase":"requested","i_sqn":"11","Status":""}}}}}}

**Comment by pipiche38** [comment]
Can you enable some debug parameters (as shown in the screenshot)

- Input
- LUMI

Then you do some action on the button and you drop here the plugin log which can be found in Logs/PluginZigbee_xx.log

thanks

**Comment by ptilib** [comment]
Hello,

Sorry I don't see a screenshot and I don't know what to activate in the debugs.

**Comment by pipiche38** [comment]
<img width="1383" alt="Screenshot 2024-11-25 at 17 20 38" src="https://github.com/user-attachments/assets/4f804a2e-17f3-4180-a893-676609cd30a1">

**Comment by pipiche38** [comment]
This is just an extract while I was looking for the all logs, especially to see th pairing,and from this extract I do not see any communication from the device !

**Comment by ptilib** [comment]
OK Sorry for the confusion.
Here is the full file.
I have removed and re-paired the device between 17h49 and 17h51
And pressed the button in short press, double press, long press, plenty of times after.

[PluginZigbee_19.log](https://github.com/user-attachments/files/17906368/PluginZigbee_19.log)

**Comment by pipiche38** [comment]
Thanks, I have some investigations to do, but at least the device is talking and we received data

**Comment by pipiche38** [comment]
I need to do a fix in the plugin code. Will revert to you when done and where to find it.

**Comment by pipiche38** [comment]
Kindly do the following

(1) switch to the specific branch hotfix-lumi-lumi.remote.acn004

```
git pull
git checkout hotfix-lumi-lumi.remote.acn004
```

from the plugin home directory
`sudo python3 -m pip install -r requirements.txt --upgrade`

restart the plugin, and redo the pairing from scratch (you should get 3 Switch selector, one for each switch and the 3rd one is when you are pressing the 2 together)

**Comment by ptilib** [comment]
Hello,

Thank you for the quick feedback.
I tested and it seems to work as required.
Left, right and both button recognized and going to action goes into Domoticz.

AqaraMultiClick by default on 2 - it recognized single, double and long click.
AqaraMultiClick changed to 1 and it only recognizes single click but with a (slightly) better latency.

Thank you very much.

**Comment by pipiche38** [comment]
Glad to see it works.
It will be merged at a point of time in 7.1.015

Will keep you posted, until kindly stay on that branch
