### ISSUE TITLE
[Model Certification] - Personal device not optimzed

### ISSUE THREAD

**Issue by Polo9222** [zigbeefordomoticz/z4d-certified-devices#86]
Hello everybody,

I have created my own Zigbee device using a development board (cc2530+2591) programmed with PTVO. I have linked it through Z4D to Domoticz. On this device there are 3 DS18B20 temperature probes and 2 output on relays. 
This device has been connected and recognized immediatly up to Domoticz in which it has been created the 5 corresponding domoticz devices ( 3 t° and 2 switches ). Everything is functionning properly.

 I have been in the Domoticz Z4D plugin interface to have a look to this device in detail and it appears that **"the device is not optimized for the plugin"** . There is no error warning.

As far as it works fine, this is not a problem for me until now . 
My questions are : 
- Is it a problem for a device (that seems to work fine) not to be optimized ?
-  Shall I do something in PTVO not to have this warning ?

Let me join the information given when I clic on the "non optimized icon" :
[FRisquet.txt](https://github.com/user-attachments/files/17936785/FRisquet.txt)

I will be very interested by your reply.

Let me thank you for all your work on the topics , I really appretiate your great job

Paul

**Comment by pipiche38** [comment]
You can place the following in the Conf/Local-Devices folder under the name "Polo-Frisquet.json"

The filename is constructed from the Zigbee model name you have defined in PTVO ( Cluster 0x0000 Attribute 0x0005)


```
{
    "_comment":"",
    "_version":"",
    "_blakadder":"",
    "_source":"",
    "Ep":{
        "01":{"0000":"","0402":"","Type":"Temp"},
        "02":{"0402":"","0000":"","Type":"Temp"},
        "03":{"0402":"","0000":"","Type":"Temp"},
        "04":{"0006":"","0000":"","Type":"Switch"},
        "05":{"0006":"","0000":"","Type":"Switch"}},
    "Type":"",
    "ClusterToBind":["0006","0402","0000"],
    "ConfigureReporting":{
        "0402":{ "0000":{ "Change":"0003","DataType":"29","MaxInterval":"003c","MinInterval":"003c","TimeOut":"0000"}},
        "0006":{ "0000":{ "Change":"01","DataType":"10","MaxInterval":"003c","MinInterval":"003c","TimeOut":"0000"}}},
    "ReadAttributes":{
        "0000":["0000","0001","0002","0003","0004","0005","0006","0007","0010","0011","8000","4000"],
        "0402":["0000"],
        "0006":["0000"]
    },
    "Param":{},
    "GroupMembership":{}
}

```

More informations can be found https://github.com/zigbeefordomoticz/wiki/blob/a9dbc5a2fadf88b6d445d535dd7bfeffff286c7e/en-eng/HowTo_Device-Customization.md

**Comment by Polo9222** [comment]
Thanks Pipiche for your  detailed and usefull reply : (just a little comment, the last « , » (comma) is to be suppressed not to have an error). This gave me the obligation to read  « HowTo_Device-Customization.md » !

 

I will try not to bother you next time :  I will try to do an rain detector with rain intensity information.

 

Best regards

 

Paul

 

De : Pipiche ***@***.***> 
Envoyé : mercredi 27 novembre 2024 19:17
À : zigbeefordomoticz/z4d-certified-devices ***@***.***>
Cc : Polo9222 ***@***.***>; Author ***@***.***>
Objet : Re: [zigbeefordomoticz/z4d-certified-devices] [Model Certification] - Personal device not optimzed (Issue #86)

 

You can place the following in the Conf/Local-Devices folder under the name "Polo-Frisquet.json"

The filename is constructed from the Zigbee model name you have defined in PTVO ( Cluster 0x0000 Attribute 0x0005)

{
    "_comment":"",
    "_version":"",
    "_blakadder":"",
    "_source":"",
    "Ep":{
        "01":{"0000":"","0402":"","Type":"Temp"},
        "02":{"0402":"","0000":"","Type":"Temp"},
        "03":{"0402":"","0000":"","Type":"Temp"},
        "04":{"0006":"","0000":"","Type":"Switch"},
        "05":{"0006":"","0000":"","Type":"Switch"}},
    "Type":"",
    "ClusterToBind":["0006","0402","0000"],
    "ConfigureReporting":{
        "0402":{ "0000":{ "Change":"0003","DataType":"29","MaxInterval":"003c","MinInterval":"003c","TimeOut":"0000"}},
        "0006":{ "0000":{ "Change":"01","DataType":"10","MaxInterval":"003c","MinInterval":"003c","TimeOut":"0000"}}},
    "ReadAttributes":{
        "0000":["0000","0001","0002","0003","0004","0005","0006","0007","0010","0011","8000","4000"],
        "0402":["0000"],
        "0006":["0000"]
    },
}
 

More informations can be found https://github.com/zigbeefordomoticz/wiki/blob/a9dbc5a2fadf88b6d445d535dd7bfeffff286c7e/en-eng/HowTo_Device-Customization.md

**Comment by zigbeefordomoticz** [comment]
Right , no coma on the last statement Envoyé de mon iPhoneLe 27 nov. 2024 à 23:12, Polo9222 ***@***.***> a écrit :﻿
Thanks Pipiche for your  detailed and usefull reply : (just a little comment, the last « , » (comma) is to be suppressed not to have an error). This gave me the obligation to read  « HowTo_Device-Customization.md » !



 



I will try not to bother you next time :  I will try to do an rain detector with rain intensity information.



 



Best regards



 



Paul



 



De : Pipiche ***@***.***> 

Envoyé : mercredi 27 novembre 2024 19:17

À : zigbeefordomoticz/z4d-certified-devices ***@***.***>

Cc : Polo9222 ***@***.***>; Author ***@***.***>

Objet : Re: [zigbeefordomoticz/z4d-certified-devices] [Model Certification] - Personal device not optimzed (Issue #86)



 



You can place the following in the Conf/Local-Devices folder under the name "Polo-Frisquet.json"



The filename is constructed from the Zigbee model name you have defined in PTVO ( Cluster 0x0000 Attribute 0x0005)



{

    "_comment":"",

    "_version":"",

    "_blakadder":"",

    "_source":"",

    "Ep":{

        "01":{"0000":"","0402":"","Type":"Temp"},

        "02":{"0402":"","0000":"","Type":"Temp"},

        "03":{"0402":"","0000":"","Type":"Temp"},

        "04":{"0006":"","0000":"","Type":"Switch"},

        "05":{"0006":"","0000":"","Type":"Switch"}},

    "Type":"",

    "ClusterToBind":["0006","0402","0000"],

    "ConfigureReporting":{

        "0402":{ "0000":{ "Change":"0003","DataType":"29","MaxInterval":"003c","MinInterval":"003c","TimeOut":"0000"}},

        "0006":{ "0000":{ "Change":"01","DataType":"10","MaxInterval":"003c","MinInterval":"003c","TimeOut":"0000"}}},

    "ReadAttributes":{

        "0000":["0000","0001","0002","0003","0004","0005","0006","0007","0010","0011","8000","4000"],

        "0402":["0000"],

        "0006":["0000"]

    },

}

 



More informations can be found https://github.com/zigbeefordomoticz/wiki/blob/a9dbc5a2fadf88b6d445d535dd7bfeffff286c7e/en-eng/HowTo_Device-Customization.md

**Comment by pipiche38** [comment]
I suggest to close the issue as resolved.
In all cases, if the device shows as non-optimized in principle there is no real impact. What can happen is that the plugin is doing more work than expected, which can eventually influence the load.

**Comment by Polo9222** [comment]
Tout à fait .

Merci

 

De : Pipiche ***@***.***> 
Envoyé : jeudi 28 novembre 2024 11:52
À : zigbeefordomoticz/z4d-certified-devices ***@***.***>
Cc : Polo9222 ***@***.***>; Author ***@***.***>
Objet : Re: [zigbeefordomoticz/z4d-certified-devices] [Model Certification] - Personal device not optimzed (Issue #86)

 

I suggest to close the issue as resolved.
In all cases, if the device shows as non-optimized in principle there is no real impact. What can happen is that the plugin is doing more work than expected, which can eventually influence the load.
