### ISSUE TITLE
[Model Certification] - IKEA Tradfri - LED2104R3 - TRADFRI bulb GU10 WW 345lm - not optimized

### ISSUE THREAD

**Issue by JTowser** [zigbeefordomoticz/z4d-certified-devices#87]
IKEA TRADFRI bulb GU10 WW 345lm seems to be not optimized.

[IKEA Link](https://www.ikea.com/nl/nl/p/tradfri-led-lamp-gu10-345-lumen-smart-draadloos-dimbaar-warm-wit-00541300/)

Article nr. 005.413.00

Product is working ok, altough giving this error.

Tested on Plugin Version 7.1.016

[export.json](https://github.com/user-attachments/files/18096072/export.json)

**Comment by pipiche38** [comment]
Should be ok with [5.349]
