### ISSUE TITLE
Bitron Home IR Movement Sensor 902010/122

### ISSUE THREAD

**Issue by jbraakhekke** [zigbeefordomoticz/z4d-certified-devices#89]
[1.](url) Please do provide device information such as Brand and Model name.
1. Provide the URL where you have purchase the device
    * IR Movement Sensor
    * Bitron Home
    * URL on a web site
[export.json](https://github.com/user-attachments/files/18266816/export.json)

    * What do you expect

1. Document as much what works, what doesn't work, what do you miss, what do you need

Device is labeled as 'door' instead of 'movement sensor'

**Comment by pipiche38** [comment]
kindly update to Certified Db 5.353 and you must redo the pairing from scratch

**Comment by jbraakhekke** [comment]
The sensor is now labeled correctly. Thank you!

**Comment by pipiche38** [comment]
supr, thanks for the feedbacks
