### ISSUE TITLE
Energy Meter DAC2161C

### ISSUE THREAD

**Issue by IW2FAG-11** [zigbeefordomoticz/z4d-certified-devices#9]
Device information such as Brand and Model name.

Solar PV bidirectional ZigBee Energy Meter Tuya Smart App Monitor 80A  Din Rail 110V 220V 50/60hz ZigBee 

1. Provide the URL where you have purchase the device
    * Smart Meter DAC2161
  
    *Dongguan Pinjia Tecnology Co.Ltd.

    * [URL on a web site](https://it.aliexpress.com
 /item/1005005321670658.html?spm=a2g0o.store_pc_groupList.8148356.3.43ca15a2Rylehy&pdp_npi=3%40dis%21EUR%21%E2%82%AC%2070%2C84%21%E2%82%AC%2034%2C71%21%21%21%21%21%40211b88ef16920193987205163edaaa%2112000033312854375%21sh%21IT%21181587864)
 
    * Voltage, Current, Power, Power Faactor, Active Povwer, Frequency. Bidirectional mode.
       [  With Relay to open circuit on allarm (Over/Under   Voltage, current, frequency) ]

Plugin 7.1.0002

[export.zip](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/12335052/export.zip)

Any information ... :P 
https://www.zigbee2mqtt.io/devices/DAC2161C.html

**Comment by IW2FAG-11** [comment]
It is recognized by the plugin, but does not add widgets to Domoticz. Bullseye on Rpi3B+ Domoticz 2023.1

I switched from buster to Bullseye, I reinstalled DtgBot, Monit, and other applications to manage a custom montor to display PARAMETERS of my IOT to be able to update to the latest version of the plugin.

**Comment by pipiche38** [comment]
Did you solved it ?

**Comment by IW2FAG-11** [comment]
No, problem is olready present

**Comment by IW2FAG-11** [comment]
No, problem is already present

**Comment by pipiche38** [comment]
WIP https://zigbee.blakadder.com/DAC2161C.html

**Comment by pipiche38** [comment]
please upgrade to [2.89] 

`sudo python3 -m pip install -r requirements.txt --upgrade`


and then restart the pairing from scratch

**Comment by IW2FAG-11** [comment]
Thanks now is working - Plugin: 7.1.002 [2.89] - 
I see some information.
I don't see net frequency and power factor. But at moment are enough.
And this item can monitor energy in two direction.
Thanks.

added also....
sudo python3 -m pip install git+https://github.com/zigbeefordomoticz/z4d-certified-devices

**Comment by pipiche38** [comment]
Can you check that values are correct. I'm not aware of frequency and power factor.
Can you drop an export.json so I see if they are other data available?

**Comment by IW2FAG-11** [comment]
I'm tryng now...... let's me attach load

**Comment by IW2FAG-11** [comment]
PF (PowerFactor  0,999/ 1.000) Not catched
Frequency (50.00/50.004) Not catched
Switch (On/Off), Voltage, Current, Power ->  looks perfect.
Energy (cunsumed) is not the same.  I read 0,01 on meter and 3 time bigger on domoticz widget.
[export(1).zip](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/12342047/export.1.zip)
This item can programm alse two allarm to disconnect. 

I found many implementations of the dispositive strsso, the ones shown below are others
https://www.zigbee2mqtt.io/devices/TS0601_din_1.html
https://github.com/Koenkk/zigbee2mqtt/issues/13097

**Comment by IW2FAG-11** [comment]
Energy (cunsumed) is not the same. I read 0,01 on meter and 3 time bigger on domoticz widget. 
Slorry...... rounding effect on device display 000000,01 instead of 0,006KWh in widget

**Comment by IW2FAG-11** [comment]
[Tuya Wifi Zigbee 110V 220V 80A Smart monofase bidirezionale misuratore di energia bidirezionale Timer consumo energetico Monitor KWh Meter - AliExpress.pdf](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/12342455/Tuya.Wifi.Zigbee.110V.220V.80A.Smart.monofase.bidirezionale.misuratore.di.energia.bidirezionale.Timer.consumo.energetico.Monitor.KWh.Meter.-.AliExpress.pdf)
And documentation.

**Comment by pipiche38** [comment]
for PF and Frequency, I have no clue how/what to get.
I have updated the config file for the device, I guess this should fixed the Meter one.

I have also updated a converter, so the MeterId should correctly be decoded. But it is only available on the export.json

In your case, the MeterId: 22492633

In all, do an update to get [2.90] and just restart the plugin, to see if the meter works correctly.

As the Alarm are concerned, my issue is what should I do with them ? So in case you want a more closer integration I would be happy to do it, but you will have to guide me and tell what you would like.

**Comment by IW2FAG-11** [comment]
Thanks for all. 
I'll try to find some info to ghet Freqency and PF.
At present moment is all OK (upgraded to 2.90).
Allarm is not essential, and i think is not accessible from RF.
I will try to make some scripts in LUA or DZEvent to handle the line.
For example if the line voltage goes out of range (CEI 0-21) I will disconnect my loads and use local generation, or if the load exceeds certain values.
If I can recover the way to read the grid frequency, I will let you know.
Also this information would always serve as a basis for alarming.
I'm poking around in a few files to see if I can figure something out.
I will confirm that the MeterId: 22492633, coappears on the display.
Other information that is there is a 17 03.12 which I guess is the FW version.
Thank you again for your speed in responding.
[export(2).zip](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/12345048/export.2.zip)

**Comment by pipiche38** [comment]
BTW, thanks for the Paypal transaction. really appreciate

**Comment by IW2FAG-11** [comment]
You make a great Job.

Does the information in the following table that I found make sense to be able to extract other data from the meter ?

[Clipboard01.zip](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/12371579/Clipboard01.zip)

**Comment by pipiche38** [comment]
This looks very interesting, but from the latest export.json you provided, I didn't get much
I wonder if some of the attribute must be read.

You can add tuya0601 and tuya debuging parameters, that will add some tuya related debug in the log, you might get something there.

I'm out for the 2 next days.

**Comment by pipiche38** [comment]
I hope to be able to work on it next week. I think the device reached my mailbox, so I should be able to find some time in one of the next evenings

**Comment by IW2FAG-11** [comment]
I have not yet collected anything else from the plugin, I have been busy with other activities, as the device is currently on the table to be tested and not yet connected with my IoT network.
I had to switch to BullsEye for the necessary phyton upgrade and since I had other scripts of mine that didn't run with the "new" 3.9 I had to resit everything first. 
I use Domoticz+ZigbeeforDomoticz for thermometers and occupancy sensors, as well as Tasmotized or EspEasy devices for active control of loads to make the most of my PV system.
I would need the zigbee power meteri zigbee power meter to replace a device I built myself and for now it only measures panel currents and house consumption. I had built the device for myself years ago in a small din rail box. So far it has done its job very well and even withstood two lightning strikes that broke my video surveillance recorders.

Translated with www.DeepL.com/Translator (free version)

**Comment by IW2FAG-11** [comment]
I updated Domoticz to rev. 2023.2, updated the plugin to 7.103(2.100). 
Now with my Coordinator the topology that had been missing for some time is back visible.
I attach logs of the Tuya plugin. 
[PluginZigbee_09.log](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/12520929/PluginZigbee_09.log)
![IMG_0679](https://github.com/zigbeefordomoticz/z4d-certified-devices/assets/69007986/7533922a-e90c-461b-b8b4-7d0a08954a43)
![Uploading IMG_8710.JPG…]()

**Comment by IW2FAG-11** [comment]
Upsssss 
[errors.zip](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/12521411/errors.zip)

**Comment by pipiche38** [comment]
Hops sorry for the errors, this should be solved with [2.102] 

As the other parameters, I'm not getting any information from the log. It might be the case that the Tuya GW and Smart Application might query directly the information, but then I would need to get the device itself, in order to test it with the Tuya gateway and sniff the zigbee trafic.

When I'll have a bit more funding, I would eventually purchase one.

**Comment by IW2FAG-11** [comment]
ok dear... i need an other one.If You want i'll buy one for you and when you finish you can resend to me. Inviato da meIl giorno 5 set 2023, alle ore 22:29, Pipiche ***@***.***> ha scritto:﻿
Hops sorry for the errors, this should be solved with [2.102]
As the other parameters, I'm not getting any information from the log. It might be the case that the Tuya GW and Smart Application might query directly the information, but then I would need to get the device itself, in order to test it with the Tuya gateway and sniff the zigbee trafic.
When I'll have a bit more funding, I would eventually purchase one.

**Comment by pipiche38** [comment]
@IW2FAG-11  please reach me patrick-@-pichon.me
